
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 11 2025 17:36:29 IST (Oct 11 2025 12:06:29 UTC)

// Verification Directory fv/collision_avoidance_car 

module add_unsigned_4(A, B, Z);
  input [31:0] A;
  input [7:0] B;
  output [31:0] Z;
  wire [31:0] A;
  wire [7:0] B;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_17, n_18, n_19, n_21, n_24, n_25, n_26, n_28;
  wire n_29, n_30, n_32, n_35, n_36, n_37, n_38, n_40;
  wire n_41, n_42, n_45, n_46, n_47, n_50, n_51, n_54;
  wire n_55, n_58, n_59, n_62, n_63, n_64, n_67, n_68;
  wire n_71, n_72, n_75, n_76, n_79, n_80, n_83, n_84;
  wire n_87;
  OAI21X1 g940(.A0 (A[31]), .A1 (n_76), .B0 (n_87), .Y (Z[31]));
  NAND2XL g941(.A (A[31]), .B (n_76), .Y (n_87));
  OAI21X1 g942(.A0 (A[27]), .A1 (n_72), .B0 (n_84), .Y (Z[27]));
  OAI21X1 g943(.A0 (A[23]), .A1 (n_71), .B0 (n_83), .Y (Z[23]));
  NAND2XL g944(.A (A[27]), .B (n_72), .Y (n_84));
  NAND2XL g945(.A (A[23]), .B (n_71), .Y (n_83));
  OAI21X1 g946(.A0 (A[19]), .A1 (n_68), .B0 (n_80), .Y (Z[19]));
  OAI21X1 g947(.A0 (A[15]), .A1 (n_67), .B0 (n_79), .Y (Z[15]));
  NAND2XL g948(.A (A[19]), .B (n_68), .Y (n_80));
  NAND2XL g949(.A (A[15]), .B (n_67), .Y (n_79));
  OA21XL g950(.A0 (A[30]), .A1 (n_63), .B0 (n_76), .Y (Z[30]));
  OAI21X1 g951(.A0 (A[11]), .A1 (n_64), .B0 (n_75), .Y (Z[11]));
  NAND2XL g952(.A (A[30]), .B (n_63), .Y (n_76));
  NAND2XL g953(.A (A[11]), .B (n_64), .Y (n_75));
  OA21XL g954(.A0 (A[26]), .A1 (n_59), .B0 (n_72), .Y (Z[26]));
  OA21XL g955(.A0 (A[22]), .A1 (n_58), .B0 (n_71), .Y (Z[22]));
  NAND2XL g956(.A (A[26]), .B (n_59), .Y (n_72));
  NAND2XL g957(.A (A[22]), .B (n_58), .Y (n_71));
  OA21XL g958(.A0 (A[18]), .A1 (n_55), .B0 (n_68), .Y (Z[18]));
  OA21XL g959(.A0 (A[14]), .A1 (n_54), .B0 (n_67), .Y (Z[14]));
  NAND2XL g960(.A (A[18]), .B (n_55), .Y (n_68));
  NAND2XL g961(.A (A[14]), .B (n_54), .Y (n_67));
  OA21XL g962(.A0 (A[10]), .A1 (n_50), .B0 (n_64), .Y (Z[10]));
  OAI21X1 g963(.A0 (A[29]), .A1 (n_51), .B0 (n_62), .Y (Z[29]));
  NAND2XL g964(.A (A[10]), .B (n_50), .Y (n_64));
  NOR2BX1 g965(.AN (A[29]), .B (n_51), .Y (n_63));
  NAND2XL g966(.A (A[29]), .B (n_51), .Y (n_62));
  AOI21X1 g967(.A0 (n_4), .A1 (n_46), .B0 (n_59), .Y (Z[25]));
  AOI21X1 g968(.A0 (n_1), .A1 (n_45), .B0 (n_58), .Y (Z[21]));
  NOR2XL g969(.A (n_4), .B (n_46), .Y (n_59));
  NOR2XL g970(.A (n_1), .B (n_45), .Y (n_58));
  AOI21X1 g971(.A0 (n_5), .A1 (n_42), .B0 (n_55), .Y (Z[17]));
  AOI21X1 g972(.A0 (n_3), .A1 (n_41), .B0 (n_54), .Y (Z[13]));
  NOR2XL g973(.A (n_5), .B (n_42), .Y (n_55));
  NOR2XL g974(.A (n_3), .B (n_41), .Y (n_54));
  OA21XL g975(.A0 (A[28]), .A1 (n_47), .B0 (n_51), .Y (Z[28]));
  AOI21XL g976(.A0 (n_2), .A1 (n_36), .B0 (n_50), .Y (Z[9]));
  NAND2XL g977(.A (A[28]), .B (n_47), .Y (n_51));
  NOR2XL g978(.A (n_2), .B (n_36), .Y (n_50));
  OA21XL g979(.A0 (A[24]), .A1 (n_38), .B0 (n_46), .Y (Z[24]));
  OA21XL g980(.A0 (A[20]), .A1 (n_40), .B0 (n_45), .Y (Z[20]));
  NOR2BX1 g981(.AN (n_38), .B (n_13), .Y (n_47));
  NAND2XL g982(.A (A[24]), .B (n_38), .Y (n_46));
  NAND2XL g983(.A (A[20]), .B (n_40), .Y (n_45));
  OA21XL g984(.A0 (A[16]), .A1 (n_0), .B0 (n_42), .Y (Z[16]));
  OA21XL g985(.A0 (A[12]), .A1 (n_37), .B0 (n_41), .Y (Z[12]));
  NAND2XL g986(.A (A[16]), .B (n_0), .Y (n_42));
  NAND2XL g987(.A (A[12]), .B (n_37), .Y (n_41));
  NOR2BX1 g988(.AN (n_0), .B (n_11), .Y (n_40));
  OA21XL g989(.A0 (A[8]), .A1 (n_35), .B0 (n_36), .Y (Z[8]));
  NOR3BX1 g990(.AN (n_0), .B (n_14), .C (n_11), .Y (n_38));
  NOR2BX1 g991(.AN (n_35), .B (n_15), .Y (n_37));
  NAND2XL g992(.A (A[8]), .B (n_35), .Y (n_36));
  ADDFX1 g995(.A (A[7]), .B (B[7]), .CI (n_32), .CO (n_35), .S (Z[7]));
  ADDFX1 g996(.A (A[6]), .B (B[6]), .CI (n_29), .CO (n_32), .S (Z[6]));
  OAI21X1 g997(.A0 (n_18), .A1 (n_28), .B0 (n_30), .Y (Z[5]));
  NAND2XL g998(.A (n_18), .B (n_28), .Y (n_30));
  OAI221X1 g999(.A0 (n_7), .A1 (n_26), .B0 (n_8), .B1 (n_7), .C0
       (n_10), .Y (n_29));
  NAND2XL g1000(.A (n_8), .B (n_26), .Y (n_28));
  OAI21XL g1001(.A0 (n_24), .A1 (n_17), .B0 (n_25), .Y (Z[4]));
  NAND2BX1 g1002(.AN (n_9), .B (n_24), .Y (n_26));
  NAND2XL g1003(.A (n_17), .B (n_24), .Y (n_25));
  ADDFX1 g1004(.A (A[3]), .B (B[3]), .CI (n_21), .CO (n_24), .S (Z[3]));
  ADDFX1 g1005(.A (A[2]), .B (B[2]), .CI (n_19), .CO (n_21), .S (Z[2]));
  ADDFX1 g1006(.A (A[1]), .B (B[1]), .CI (n_6), .CO (n_19), .S (Z[1]));
  NAND2BX1 g1007(.AN (n_7), .B (n_10), .Y (n_18));
  NAND2BX1 g1008(.AN (n_9), .B (n_8), .Y (n_17));
  AOI2BB1X1 g1009(.A0N (B[0]), .A1N (A[0]), .B0 (n_6), .Y (Z[0]));
  NAND4XL g1010(.A (A[9]), .B (A[8]), .C (A[11]), .D (A[10]), .Y
       (n_15));
  NAND4XL g1011(.A (A[20]), .B (A[21]), .C (A[23]), .D (A[22]), .Y
       (n_14));
  NAND4XL g1012(.A (A[25]), .B (A[24]), .C (A[27]), .D (A[26]), .Y
       (n_13));
  NAND4XL g1013(.A (A[12]), .B (A[13]), .C (A[15]), .D (A[14]), .Y
       (n_12));
  NAND4XL g1014(.A (A[17]), .B (A[16]), .C (A[19]), .D (A[18]), .Y
       (n_11));
  NAND2XL g1015(.A (B[5]), .B (A[5]), .Y (n_10));
  NOR2XL g1016(.A (B[4]), .B (A[4]), .Y (n_9));
  NAND2XL g1017(.A (B[4]), .B (A[4]), .Y (n_8));
  NOR2XL g1018(.A (B[5]), .B (A[5]), .Y (n_7));
  AND2X1 g1019(.A (B[0]), .B (A[0]), .Y (n_6));
  CLKINVX1 g1020(.A (A[17]), .Y (n_5));
  CLKINVX1 g1021(.A (A[25]), .Y (n_4));
  CLKINVX1 g1022(.A (A[13]), .Y (n_3));
  CLKINVX1 g1023(.A (A[9]), .Y (n_2));
  CLKINVX1 g1024(.A (A[21]), .Y (n_1));
  NOR3BX1 g2(.AN (n_35), .B (n_12), .C (n_15), .Y (n_0));
endmodule

module add_signed(A, B, Z);
  input [15:0] A;
  input [8:0] B;
  output [15:0] Z;
  wire [15:0] A;
  wire [8:0] B;
  wire [15:0] Z;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_29, n_31, n_32, n_33, n_35, n_36, n_38;
  wire n_39, n_41, n_42, n_44, n_45, n_46, n_48, n_49;
  wire n_50, n_52, n_53, n_54, n_56, n_57, n_58, n_60;
  wire n_61, n_62, n_64, n_65, n_68, n_69, n_97, n_99;
  wire n_101, n_102;
  OAI21XL g370(.A0 (n_68), .A1 (n_20), .B0 (n_69), .Y (Z[15]));
  NAND2XL g371(.A (n_68), .B (n_20), .Y (n_69));
  ADDFXL g372(.A (A[14]), .B (n_97), .CI (n_65), .CO (n_68), .S
       (Z[14]));
  ADDFHX1 g373(.A (n_101), .B (A[13]), .CI (n_64), .CO (n_65), .S
       (Z[13]));
  OAI2BB1X1 g374(.A0N (A[12]), .A1N (n_101), .B0 (n_61), .Y (n_64));
  OAI21XL g375(.A0 (n_60), .A1 (n_18), .B0 (n_62), .Y (Z[12]));
  NAND2XL g376(.A (n_60), .B (n_18), .Y (n_62));
  OAI21X1 g377(.A0 (A[12]), .A1 (n_99), .B0 (n_60), .Y (n_61));
  OAI2BB1X1 g378(.A0N (A[11]), .A1N (n_99), .B0 (n_57), .Y (n_60));
  OAI21XL g379(.A0 (n_56), .A1 (n_21), .B0 (n_58), .Y (Z[11]));
  NAND2XL g380(.A (n_56), .B (n_21), .Y (n_58));
  OAI21X1 g381(.A0 (A[11]), .A1 (n_99), .B0 (n_56), .Y (n_57));
  OAI2BB1X1 g382(.A0N (A[10]), .A1N (n_99), .B0 (n_53), .Y (n_56));
  OAI21XL g383(.A0 (n_52), .A1 (n_22), .B0 (n_54), .Y (Z[10]));
  NAND2XL g384(.A (n_52), .B (n_22), .Y (n_54));
  OAI21X1 g385(.A0 (A[10]), .A1 (n_97), .B0 (n_52), .Y (n_53));
  OAI2BB1X1 g386(.A0N (A[9]), .A1N (n_97), .B0 (n_49), .Y (n_52));
  OAI21XL g387(.A0 (n_48), .A1 (n_19), .B0 (n_50), .Y (Z[9]));
  NAND2XL g388(.A (n_48), .B (n_19), .Y (n_50));
  OAI21X1 g389(.A0 (A[9]), .A1 (n_97), .B0 (n_48), .Y (n_49));
  OAI2BB1X1 g390(.A0N (A[8]), .A1N (n_97), .B0 (n_45), .Y (n_48));
  OAI21XL g391(.A0 (n_44), .A1 (n_15), .B0 (n_46), .Y (Z[8]));
  NAND2XL g392(.A (n_15), .B (n_44), .Y (n_46));
  OAI21X1 g393(.A0 (A[8]), .A1 (B[8]), .B0 (n_44), .Y (n_45));
  OAI21X2 g394(.A0 (n_7), .A1 (n_42), .B0 (n_2), .Y (n_44));
  MXI2XL g395(.A (n_42), .B (n_41), .S0 (n_13), .Y (Z[7]));
  CLKINVX1 g396(.A (n_41), .Y (n_42));
  OAI2BB1X1 g397(.A0N (A[6]), .A1N (B[6]), .B0 (n_39), .Y (n_41));
  CLKXOR2X1 g398(.A (n_38), .B (n_12), .Y (Z[6]));
  OAI21X1 g399(.A0 (A[6]), .A1 (B[6]), .B0 (n_38), .Y (n_39));
  OAI2BB1X1 g400(.A0N (A[5]), .A1N (B[5]), .B0 (n_36), .Y (n_38));
  XOR2XL g401(.A (n_10), .B (n_35), .Y (Z[5]));
  OAI21X1 g402(.A0 (A[5]), .A1 (B[5]), .B0 (n_35), .Y (n_36));
  OAI21X2 g403(.A0 (n_9), .A1 (n_33), .B0 (n_3), .Y (n_35));
  MXI2XL g404(.A (n_33), .B (n_32), .S0 (n_14), .Y (Z[4]));
  CLKINVX1 g405(.A (n_32), .Y (n_33));
  OAI21X1 g406(.A0 (n_6), .A1 (n_31), .B0 (n_4), .Y (n_32));
  AOI21X1 g409(.A0 (n_5), .A1 (n_29), .B0 (n_23), .Y (n_31));
  XOR2XL g410(.A (n_29), .B (n_24), .Y (Z[2]));
  OAI2BB1X1 g411(.A0N (A[1]), .A1N (B[1]), .B0 (n_26), .Y (n_29));
  OAI21X1 g412(.A0 (n_8), .A1 (n_16), .B0 (n_27), .Y (Z[1]));
  NAND2XL g413(.A (n_8), .B (n_16), .Y (n_27));
  OAI21X1 g414(.A0 (A[1]), .A1 (B[1]), .B0 (n_25), .Y (n_26));
  INVX1 g415(.A (n_8), .Y (n_25));
  ADDHXL g416(.A (B[2]), .B (A[2]), .CO (n_23), .S (n_24));
  OA21XL g417(.A0 (B[0]), .A1 (A[0]), .B0 (n_8), .Y (Z[0]));
  MXI2XL g418(.A (n_101), .B (n_102), .S0 (A[10]), .Y (n_22));
  MXI2XL g419(.A (n_101), .B (n_102), .S0 (A[11]), .Y (n_21));
  MXI2XL g420(.A (n_101), .B (n_102), .S0 (A[15]), .Y (n_20));
  MXI2XL g421(.A (n_101), .B (n_102), .S0 (A[9]), .Y (n_19));
  MXI2XL g422(.A (n_101), .B (n_102), .S0 (A[12]), .Y (n_18));
  CLKXOR2X1 g423(.A (A[4]), .B (B[4]), .Y (n_14));
  CLKXOR2X1 g424(.A (B[7]), .B (A[7]), .Y (n_13));
  CLKXOR2X1 g425(.A (A[1]), .B (B[1]), .Y (n_16));
  XOR2XL g426(.A (A[6]), .B (B[6]), .Y (n_12));
  CLKXOR2X1 g427(.A (B[3]), .B (A[3]), .Y (n_11));
  XOR2XL g428(.A (A[5]), .B (B[5]), .Y (n_10));
  MXI2XL g429(.A (n_101), .B (n_102), .S0 (A[8]), .Y (n_15));
  NOR2XL g430(.A (A[4]), .B (B[4]), .Y (n_9));
  NAND2XL g431(.A (B[0]), .B (A[0]), .Y (n_8));
  NOR2XL g432(.A (A[7]), .B (B[7]), .Y (n_7));
  NOR2XL g433(.A (A[3]), .B (B[3]), .Y (n_6));
  OR2XL g434(.A (A[2]), .B (B[2]), .Y (n_5));
  NAND2XL g435(.A (B[3]), .B (A[3]), .Y (n_4));
  NAND2XL g436(.A (A[4]), .B (B[4]), .Y (n_3));
  NAND2XL g437(.A (A[7]), .B (B[7]), .Y (n_2));
  XNOR2XL g2(.A (n_31), .B (n_11), .Y (Z[3]));
  INVX1 fopt449(.A (n_102), .Y (n_101));
  CLKINVX1 fopt453(.A (n_102), .Y (n_99));
  CLKINVX1 fopt457(.A (n_102), .Y (n_97));
  INVX1 fopt458(.A (B[8]), .Y (n_102));
endmodule

module csa_tree_add_153_58_group_2(in_0, in_1, in_2, out_0);
  input [7:0] in_0, in_1;
  input [31:0] in_2;
  output [31:0] out_0;
  wire [7:0] in_0, in_1;
  wire [31:0] in_2;
  wire [31:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_24, n_25;
  wire n_26, n_27, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_51, n_52, n_53, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_119, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_133, n_135, n_136, n_137;
  wire n_139, n_140, n_141, n_143, n_144, n_146, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_155, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_222, n_224, n_225;
  wire n_226, n_227, n_228, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_236, n_237, n_238, n_239, n_240, n_242, n_243;
  wire n_244, n_246, n_247, n_248, n_249, n_250, n_251, n_253;
  wire n_254, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_270, n_271, n_272;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  wire n_298, n_300, n_301, n_302, n_303, n_304, n_305, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_314, n_316, n_317;
  wire n_318, n_319, n_320, n_321, n_322, n_323, n_324, n_325;
  wire n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_338, n_339, n_340, n_341;
  wire n_343, n_344, n_345, n_346, n_347, n_348, n_349, n_350;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_357, n_358;
  wire n_359, n_360, n_361, n_362, n_363, n_364, n_365, n_366;
  wire n_367, n_369, n_370, n_371, n_372, n_373, n_374, n_375;
  wire n_376, n_377, n_378, n_379, n_380, n_381, n_394, n_396;
  wire n_397, n_398, n_452, n_453, n_454, n_456, n_462, n_463;
  wire n_472, n_473, n_474, n_488, n_490, n_491, n_492, n_494;
  wire n_496, n_498, n_499, n_524, n_527, n_528, n_529, n_530;
  OAI21X1 g4032(.A0 (n_381), .A1 (in_2[31]), .B0 (n_398), .Y
       (out_0[31]));
  OAI21X1 g4033(.A0 (n_380), .A1 (in_2[26]), .B0 (n_397), .Y
       (out_0[26]));
  OAI21X1 g4034(.A0 (n_371), .A1 (in_2[19]), .B0 (n_396), .Y
       (out_0[19]));
  NAND2XL g4035(.A (n_381), .B (in_2[31]), .Y (n_398));
  NAND2XL g4036(.A (n_380), .B (in_2[26]), .Y (n_397));
  NAND2XL g4037(.A (n_371), .B (in_2[19]), .Y (n_396));
  OAI21XL g4038(.A0 (in_2[17]), .A1 (n_359), .B0 (n_394), .Y
       (out_0[17]));
  NAND2X1 g4039(.A (in_2[17]), .B (n_359), .Y (n_394));
  MXI2X1 g4040(.A (in_2[28]), .B (n_53), .S0 (n_367), .Y (out_0[28]));
  MXI2X1 g4041(.A (in_2[22]), .B (n_61), .S0 (n_374), .Y (out_0[22]));
  MXI2XL g4042(.A (n_373), .B (n_372), .S0 (n_239), .Y (out_0[15]));
  NOR2BX1 g4043(.AN (n_381), .B (n_379), .Y (out_0[30]));
  NOR2BX1 g4044(.AN (n_380), .B (n_376), .Y (out_0[25]));
  NOR2BX1 g4045(.AN (n_371), .B (n_369), .Y (out_0[18]));
  OAI21XL g4046(.A0 (in_2[21]), .A1 (n_353), .B0 (n_370), .Y
       (out_0[21]));
  OAI21X1 g4047(.A0 (in_2[23]), .A1 (n_357), .B0 (n_375), .Y
       (out_0[23]));
  MXI2X1 g4048(.A (n_361), .B (n_362), .S0 (in_2[24]), .Y (out_0[24]));
  MXI2X1 g4049(.A (n_364), .B (n_365), .S0 (in_2[20]), .Y (out_0[20]));
  OAI21XL g4050(.A0 (in_2[29]), .A1 (n_356), .B0 (n_378), .Y
       (out_0[29]));
  OAI21XL g4051(.A0 (in_2[27]), .A1 (n_355), .B0 (n_377), .Y
       (out_0[27]));
  NOR2XL g4052(.A (n_352), .B (in_2[30]), .Y (n_379));
  NAND2X1 g4053(.A (in_2[29]), .B (n_356), .Y (n_378));
  NAND2X1 g4054(.A (in_2[27]), .B (n_355), .Y (n_377));
  NOR2XL g4055(.A (n_354), .B (in_2[25]), .Y (n_376));
  NAND2X1 g4056(.A (in_2[23]), .B (n_357), .Y (n_375));
  NAND2BX1 g4057(.AN (n_111), .B (n_363), .Y (n_374));
  NAND2X1 g4058(.A (n_352), .B (in_2[30]), .Y (n_381));
  NAND2X1 g4059(.A (n_354), .B (in_2[25]), .Y (n_380));
  INVXL g4060(.A (n_372), .Y (n_373));
  NAND2X1 g4061(.A (in_2[21]), .B (n_353), .Y (n_370));
  NOR2XL g4062(.A (n_366), .B (in_2[18]), .Y (n_369));
  NOR2BX1 g4064(.AN (n_359), .B (n_358), .Y (out_0[16]));
  NAND2X1 g4066(.A (n_360), .B (n_158), .Y (n_367));
  OAI21X1 g4067(.A0 (n_349), .A1 (n_293), .B0 (n_292), .Y (n_372));
  NAND2X1 g4068(.A (n_366), .B (in_2[18]), .Y (n_371));
  INVX1 g4069(.A (n_364), .Y (n_365));
  INVX1 g4070(.A (n_363), .Y (n_364));
  INVX1 g4071(.A (n_361), .Y (n_362));
  INVX1 g4072(.A (n_360), .Y (n_361));
  NOR2XL g4073(.A (n_350), .B (in_2[16]), .Y (n_358));
  NOR2X1 g4074(.A (n_85), .B (n_351), .Y (n_366));
  NOR2X1 g4075(.A (n_126), .B (n_351), .Y (n_363));
  NOR2X1 g4076(.A (n_165), .B (n_351), .Y (n_360));
  NAND2X1 g4077(.A (in_2[16]), .B (n_350), .Y (n_359));
  NAND2X1 g4078(.A (n_159), .B (n_350), .Y (n_357));
  NAND2X1 g4079(.A (n_179), .B (n_350), .Y (n_356));
  NAND2X1 g4080(.A (n_183), .B (n_350), .Y (n_355));
  NOR2X1 g4081(.A (n_182), .B (n_351), .Y (n_354));
  NAND2X1 g4082(.A (n_155), .B (n_350), .Y (n_353));
  NOR2X1 g4083(.A (n_190), .B (n_351), .Y (n_352));
  INVX2 g4084(.A (n_351), .Y (n_350));
  AOI21X4 g4085(.A0 (n_341), .A1 (n_346), .B0 (n_344), .Y (n_351));
  AOI21XL g4087(.A0 (n_346), .A1 (n_49), .B0 (n_338), .Y (n_349));
  AOI21X1 g4089(.A0 (n_320), .A1 (n_456), .B0 (n_325), .Y (n_348));
  AOI21X1 g4093(.A0 (n_327), .A1 (n_27), .B0 (n_322), .Y (n_347));
  OAI21X4 g4095(.A0 (n_333), .A1 (n_337), .B0 (n_345), .Y (n_346));
  AOI21X2 g4098(.A0 (n_339), .A1 (n_332), .B0 (n_340), .Y (n_345));
  OAI2BB1X1 g4099(.A0N (n_297), .A1N (n_338), .B0 (n_302), .Y (n_344));
  AOI21X1 g4104(.A0 (n_47), .A1 (n_336), .B0 (n_463), .Y (n_343));
  MXI2XL g4105(.A (n_336), .B (n_317), .S0 (n_316), .Y (out_0[8]));
  AND2X1 g4106(.A (n_297), .B (n_49), .Y (n_341));
  OAI21X1 g4107(.A0 (n_323), .A1 (n_321), .B0 (n_328), .Y (n_340));
  OAI21X1 g4109(.A0 (n_25), .A1 (n_318), .B0 (n_329), .Y (n_339));
  OAI21X1 g4110(.A0 (n_311), .A1 (n_324), .B0 (n_309), .Y (n_338));
  NAND2X2 g4111(.A (n_336), .B (n_331), .Y (n_337));
  CLKINVX2 g4113(.A (n_317), .Y (n_336));
  NAND2XL g4114(.A (n_329), .B (n_319), .Y (n_335));
  NAND2XL g4115(.A (n_323), .B (n_327), .Y (n_334));
  NOR2X1 g4118(.A (n_311), .B (n_48), .Y (n_49));
  CLKINVX1 g4119(.A (n_332), .Y (n_333));
  NOR2X2 g4120(.A (n_326), .B (n_321), .Y (n_332));
  CLKAND2X2 g4121(.A (n_47), .B (n_319), .Y (n_331));
  NOR2XL g4122(.A (n_325), .B (n_48), .Y (n_330));
  INVXL g4124(.A (n_326), .Y (n_327));
  CLKINVX1 g4125(.A (n_324), .Y (n_325));
  INVXL g4126(.A (n_323), .Y (n_322));
  NAND2BXL g4127(.AN (n_294), .B (n_306), .Y (n_329));
  NAND2XL g4128(.A (n_295), .B (n_305), .Y (n_328));
  AND2X1 g4129(.A (n_308), .B (n_296), .Y (n_326));
  NAND2BX1 g4130(.AN (n_307), .B (n_21), .Y (n_324));
  OR2X1 g4131(.A (n_308), .B (n_296), .Y (n_323));
  INVX1 g4132(.A (n_48), .Y (n_320));
  CLKINVX1 g4134(.A (n_318), .Y (n_319));
  NAND2XL g4136(.A (n_462), .B (n_47), .Y (n_316));
  NOR2X2 g4137(.A (n_295), .B (n_305), .Y (n_321));
  NOR2BX1 g4138(.AN (n_307), .B (n_21), .Y (n_48));
  NOR2BX1 g4139(.AN (n_294), .B (n_306), .Y (n_318));
  AOI21X2 g4140(.A0 (n_301), .A1 (n_303), .B0 (n_304), .Y (n_317));
  NAND2BX1 g4143(.AN (n_311), .B (n_309), .Y (n_314));
  NAND2XL g4146(.A (n_300), .B (n_288), .Y (n_47));
  NOR2X1 g4150(.A (n_270), .B (n_282), .Y (n_311));
  NOR2BX1 g4151(.AN (n_303), .B (n_304), .Y (n_310));
  NAND2XL g4152(.A (n_270), .B (n_282), .Y (n_309));
  AOI21XL g4153(.A0 (n_279), .A1 (n_251), .B0 (n_285), .Y (n_308));
  AOI21XL g4154(.A0 (n_278), .A1 (n_268), .B0 (n_286), .Y (n_307));
  MXI2X1 g4155(.A (n_266), .B (n_251), .S0 (n_11), .Y (n_306));
  XNOR2X1 g4156(.A (n_258), .B (n_24), .Y (n_305));
  NOR2X1 g4157(.A (n_527), .B (n_287), .Y (n_304));
  NAND2XL g4158(.A (n_527), .B (n_287), .Y (n_303));
  AOI2BB1X1 g4159(.A0N (n_226), .A1N (n_292), .B0 (n_228), .Y (n_302));
  OAI21X2 g4160(.A0 (n_271), .A1 (n_281), .B0 (n_272), .Y (n_301));
  MXI2X1 g4162(.A (n_289), .B (n_290), .S0 (n_16), .Y (n_300));
  NAND2BX1 g4164(.AN (n_293), .B (n_292), .Y (n_298));
  NOR2XL g4165(.A (n_226), .B (n_293), .Y (n_297));
  XNOR3X1 g4166(.A (n_217), .B (n_264), .C (n_257), .Y (n_296));
  NAND2BX1 g4167(.AN (n_283), .B (n_291), .Y (n_295));
  AOI21X1 g4168(.A0 (n_276), .A1 (n_284), .B0 (n_280), .Y (n_294));
  NOR2XL g4171(.A (n_225), .B (n_261), .Y (n_293));
  NAND2XL g4172(.A (n_225), .B (n_261), .Y (n_292));
  OAI2BB1XL g4173(.A0N (n_232), .A1N (n_264), .B0 (n_257), .Y (n_291));
  INVX1 g4175(.A (n_289), .Y (n_290));
  MXI2X1 g4176(.A (n_275), .B (n_262), .S0 (n_197), .Y (n_289));
  AOI21X1 g4178(.A0 (n_208), .A1 (n_277), .B0 (n_211), .Y (n_288));
  MXI2X1 g4179(.A (n_277), .B (n_17), .S0 (n_13), .Y (n_287));
  NOR2XL g4180(.A (n_46), .B (n_216), .Y (n_286));
  NOR2XL g4181(.A (n_274), .B (n_195), .Y (n_285));
  NAND2X1 g4182(.A (n_16), .B (n_197), .Y (n_284));
  NOR2XL g4183(.A (n_232), .B (n_264), .Y (n_283));
  NOR2XL g4185(.A (n_16), .B (n_197), .Y (n_280));
  NAND2XL g4186(.A (n_195), .B (n_274), .Y (n_279));
  NAND2XL g4187(.A (n_46), .B (n_216), .Y (n_278));
  OAI21X1 g4189(.A0 (n_267), .A1 (n_254), .B0 (n_253), .Y (n_282));
  AOI21X1 g4190(.A0 (n_260), .A1 (n_22), .B0 (n_12), .Y (n_281));
  INVX1 g4191(.A (n_17), .Y (n_277));
  INVXL g4192(.A (n_275), .Y (n_276));
  CLKINVX1 g4193(.A (n_262), .Y (n_275));
  INVX1 g4194(.A (n_263), .Y (n_274));
  NAND2BX1 g4199(.AN (n_246), .B (n_524), .Y (n_272));
  NOR2BX1 g4200(.AN (n_246), .B (n_524), .Y (n_271));
  XNOR3XL g4201(.A (n_175), .B (n_184), .C (n_238), .Y (n_270));
  INVXL g4204(.A (n_258), .Y (n_268));
  INVX1 g4205(.A (n_259), .Y (n_267));
  INVX1 g4206(.A (n_251), .Y (n_266));
  NOR2BX1 g4207(.AN (n_22), .B (n_12), .Y (n_265));
  XNOR3X1 g4208(.A (n_75), .B (n_194), .C (n_242), .Y (n_264));
  OAI21X1 g4209(.A0 (n_19), .A1 (n_210), .B0 (n_20), .Y (n_263));
  OAI21X1 g4210(.A0 (n_234), .A1 (n_235), .B0 (n_240), .Y (n_262));
  OAI21X1 g4215(.A0 (n_227), .A1 (n_238), .B0 (n_230), .Y (n_261));
  OAI21X1 g4216(.A0 (n_237), .A1 (n_212), .B0 (n_213), .Y (n_260));
  OAI2BB1X1 g4217(.A0N (n_114), .A1N (n_236), .B0 (n_137), .Y (n_259));
  MXI2X1 g4218(.A (n_250), .B (n_236), .S0 (n_143), .Y (n_258));
  OAI21X1 g4219(.A0 (n_45), .A1 (n_249), .B0 (n_248), .Y (n_257));
  NOR2XL g4224(.A (n_528), .B (n_15), .Y (n_254));
  NAND2XL g4225(.A (n_528), .B (n_15), .Y (n_253));
  AOI21X1 g4226(.A0 (n_200), .A1 (n_242), .B0 (n_201), .Y (n_46));
  XOR3X1 g4228(.A (n_196), .B (n_45), .C (n_243), .Y (n_251));
  INVX1 g4231(.A (n_236), .Y (n_250));
  NOR2BX1 g4232(.AN (n_196), .B (n_243), .Y (n_249));
  NAND2BXL g4233(.AN (n_196), .B (n_243), .Y (n_248));
  AOI21XL g4234(.A0 (n_204), .A1 (n_8), .B0 (n_219), .Y (n_247));
  AOI21X1 g4235(.A0 (n_136), .A1 (n_231), .B0 (n_116), .Y (n_246));
  MXI2XL g4238(.A (n_218), .B (n_231), .S0 (n_144), .Y (n_244));
  ADDFHX1 g4239(.A (n_453), .B (n_0), .CI (n_169), .CO (n_242), .S
       (n_243));
  NAND2BX1 g4243(.AN (n_104), .B (n_220), .Y (n_240));
  NOR2XL g4244(.A (n_228), .B (n_226), .Y (n_239));
  NOR2BX1 g4245(.AN (n_104), .B (n_220), .Y (n_235));
  AOI21X1 g4247(.A0 (n_113), .A1 (n_209), .B0 (n_131), .Y (n_238));
  AOI21X1 g4248(.A0 (n_215), .A1 (n_473), .B0 (n_214), .Y (n_237));
  XNOR3X1 g4249(.A (n_76), .B (n_191), .C (n_530), .Y (n_236));
  ADDFHX1 g4253(.A (n_128), .B (n_90), .CI (n_151), .CO (n_233), .S
       (n_234));
  CLKBUFX2 g4254(.A (n_217), .Y (n_232));
  INVX1 g4255(.A (n_218), .Y (n_231));
  NAND2XL g4258(.A (n_175), .B (n_184), .Y (n_230));
  AND2X1 g4260(.A (in_2[15]), .B (n_224), .Y (n_228));
  NOR2XL g4261(.A (n_175), .B (n_184), .Y (n_227));
  NOR2XL g4262(.A (in_2[15]), .B (n_224), .Y (n_226));
  ADDFXL g4268(.A (in_2[14]), .B (n_88), .CI (n_160), .CO (n_224), .S
       (n_225));
  NOR2BX1 g4269(.AN (n_215), .B (n_214), .Y (n_222));
  OAI21X2 g4273(.A0 (n_452), .A1 (n_174), .B0 (n_180), .Y (n_220));
  AOI21X1 g4274(.A0 (n_146), .A1 (n_172), .B0 (n_181), .Y (n_219));
  XNOR3X1 g4275(.A (n_77), .B (n_139), .C (n_146), .Y (n_218));
  MXI2X1 g4276(.A (n_202), .B (n_185), .S0 (n_5), .Y (n_217));
  AOI21X1 g4278(.A0 (n_115), .A1 (n_185), .B0 (n_121), .Y (n_216));
  NOR2XL g4280(.A (n_203), .B (n_206), .Y (n_211));
  NAND2XL g4281(.A (n_7), .B (n_186), .Y (n_215));
  NOR2XL g4282(.A (n_7), .B (n_186), .Y (n_214));
  NAND2BX1 g4283(.AN (n_187), .B (n_529), .Y (n_213));
  NOR2BX1 g4284(.AN (n_187), .B (n_529), .Y (n_212));
  NAND2XL g4285(.A (n_203), .B (n_206), .Y (n_208));
  XNOR3X1 g4288(.A (n_124), .B (n_3), .C (n_149), .Y (n_210));
  XOR3X1 g4289(.A (in_2[12]), .B (n_82), .C (n_141), .Y (n_209));
  AOI21X2 g4290(.A0 (n_112), .A1 (n_170), .B0 (n_130), .Y (n_45));
  INVX1 g4292(.A (n_185), .Y (n_202));
  ADDFX1 g4294(.A (n_66), .B (n_86), .CI (n_69), .CO (n_205), .S
       (n_206));
  ADDFHXL g4295(.A (n_95), .B (n_87), .CI (n_91), .CO (n_203), .S
       (n_204));
  NOR2XL g4296(.A (n_75), .B (n_194), .Y (n_201));
  NAND2XL g4297(.A (n_194), .B (n_75), .Y (n_200));
  ADDFX1 g4301(.A (n_65), .B (n_63), .CI (n_98), .CO (n_196), .S
       (n_197));
  ADDFHX2 g4302(.A (n_64), .B (n_89), .CI (n_67), .CO (n_194), .S
       (n_195));
  NAND3BX1 g4303(.AN (n_161), .B (in_2[29]), .C (n_164), .Y (n_190));
  OAI21X1 g4304(.A0 (n_92), .A1 (n_123), .B0 (n_474), .Y (n_189));
  MXI2XL g4305(.A (n_93), .B (n_92), .S0 (n_474), .Y (n_193));
  AOI21X1 g4306(.A0 (n_119), .A1 (n_2), .B0 (n_133), .Y (n_192));
  OAI21X1 g4307(.A0 (n_4), .A1 (n_163), .B0 (n_1), .Y (n_191));
  AOI21X1 g4309(.A0 (in_2[3]), .A1 (n_97), .B0 (n_173), .Y (n_187));
  XNOR3X1 g4310(.A (in_2[3]), .B (n_110), .C (n_96), .Y (n_186));
  OAI21X1 g4311(.A0 (n_4), .A1 (n_168), .B0 (n_171), .Y (n_185));
  OAI2BB1X1 g4312(.A0N (in_2[12]), .A1N (n_81), .B0 (n_10), .Y (n_184));
  NOR2XL g4313(.A (n_127), .B (n_165), .Y (n_183));
  NAND2XL g4314(.A (in_2[24]), .B (n_164), .Y (n_182));
  NOR2XL g4315(.A (n_77), .B (n_139), .Y (n_181));
  NAND2XL g4316(.A (n_103), .B (n_140), .Y (n_180));
  NOR2XL g4317(.A (n_161), .B (n_165), .Y (n_179));
  NOR2X1 g4322(.A (n_103), .B (n_140), .Y (n_174));
  AOI21X1 g4324(.A0 (n_60), .A1 (n_96), .B0 (n_110), .Y (n_173));
  NAND2XL g4325(.A (n_77), .B (n_139), .Y (n_172));
  NAND2XL g4326(.A (n_4), .B (n_168), .Y (n_171));
  MXI2X1 g4327(.A (n_149), .B (n_150), .S0 (n_124), .Y (n_170));
  OAI21X1 g4328(.A0 (n_100), .A1 (n_153), .B0 (n_152), .Y (n_169));
  OAI21X1 g4329(.A0 (n_106), .A1 (n_157), .B0 (n_162), .Y (n_175));
  CLKINVX1 g4331(.A (n_530), .Y (n_166));
  INVX1 g4335(.A (n_165), .Y (n_164));
  ADDHX1 g4336(.A (n_52), .B (n_69), .CO (n_163), .S (n_168));
  NAND2XL g4337(.A (n_106), .B (n_157), .Y (n_162));
  NAND2XL g4338(.A (in_2[23]), .B (n_159), .Y (n_165));
  NAND2XL g4339(.A (in_2[28]), .B (n_158), .Y (n_161));
  OAI22X1 g4340(.A0 (n_109), .A1 (n_122), .B0 (n_51), .B1 (n_106), .Y
       (n_160));
  NOR2BX1 g4341(.AN (in_2[20]), .B (n_126), .Y (n_155));
  AOI2BB1XL g4342(.A0N (in_2[1]), .A1N (n_72), .B0 (n_123), .Y
       (out_0[1]));
  NOR2XL g4343(.A (in_2[8]), .B (n_125), .Y (n_153));
  NAND2XL g4344(.A (in_2[8]), .B (n_125), .Y (n_152));
  NOR3X1 g4345(.A (n_61), .B (n_111), .C (n_126), .Y (n_159));
  NOR2BX1 g4346(.AN (in_2[27]), .B (n_127), .Y (n_158));
  MXI2XL g4347(.A (in_2[13]), .B (n_51), .S0 (n_109), .Y (n_157));
  AOI2BB2X2 g4348(.A0N (in_2[7]), .A1N (n_62), .B0 (in_2[7]), .B1
       (n_70), .Y (n_151));
  INVX1 g4351(.A (n_149), .Y (n_150));
  MXI2XL g4352(.A (n_101), .B (n_44), .S0 (n_80), .Y (n_144));
  MXI2XL g4356(.A (n_74), .B (n_73), .S0 (n_105), .Y (n_143));
  OAI21X1 g4357(.A0 (in_2[8]), .A1 (n_100), .B0 (n_129), .Y (n_149));
  MXI2XL g4358(.A (n_42), .B (n_71), .S0 (n_84), .Y (n_148));
  MXI2X1 g4360(.A (n_93), .B (n_92), .S0 (in_2[5]), .Y (n_146));
  NAND2BX1 g4364(.AN (n_105), .B (n_73), .Y (n_137));
  NAND2XL g4365(.A (n_80), .B (n_44), .Y (n_136));
  NAND2BXL g4366(.AN (in_2[12]), .B (n_82), .Y (n_135));
  NOR2XL g4369(.A (n_84), .B (n_42), .Y (n_133));
  NOR2XL g4371(.A (n_79), .B (n_107), .Y (n_131));
  NOR2XL g4372(.A (n_78), .B (n_488), .Y (n_130));
  NAND2X1 g4373(.A (in_2[8]), .B (n_100), .Y (n_129));
  NAND2X1 g4375(.A (n_99), .B (in_2[11]), .Y (n_141));
  CLKAND2X3 g4376(.A (in_2[5]), .B (n_92), .Y (n_140));
  NAND2X1 g4377(.A (in_2[6]), .B (n_97), .Y (n_128));
  NAND2X2 g4378(.A (in_2[4]), .B (n_72), .Y (n_139));
  CLKINVX1 g4379(.A (n_125), .Y (n_124));
  AND2X1 g4380(.A (n_51), .B (n_106), .Y (n_122));
  NOR2XL g4381(.A (n_83), .B (n_102), .Y (n_121));
  NAND2XL g4383(.A (n_84), .B (n_42), .Y (n_119));
  NOR2XL g4386(.A (n_80), .B (n_44), .Y (n_116));
  NAND2XL g4387(.A (n_83), .B (n_102), .Y (n_115));
  NAND2XL g4388(.A (n_105), .B (n_74), .Y (n_114));
  NAND2XL g4389(.A (n_79), .B (n_107), .Y (n_113));
  NAND2XL g4390(.A (n_78), .B (n_488), .Y (n_112));
  NAND3X1 g4391(.A (in_2[24]), .B (in_2[25]), .C (in_2[26]), .Y
       (n_127));
  NAND3BX1 g4392(.AN (n_85), .B (in_2[19]), .C (in_2[18]), .Y (n_126));
  NOR2X1 g4394(.A (n_68), .B (n_491), .Y (n_125));
  AND2X1 g4395(.A (in_2[1]), .B (n_72), .Y (n_123));
  CLKINVX1 g4400(.A (n_101), .Y (n_44));
  CLKINVX1 g4401(.A (n_100), .Y (n_101));
  CLKINVX1 g4402(.A (n_98), .Y (n_99));
  CLKINVX2 g4404(.A (n_97), .Y (n_96));
  CLKINVX1 g4405(.A (n_94), .Y (n_95));
  CLKINVX1 g4408(.A (n_40), .Y (n_94));
  CLKINVX2 g4409(.A (n_93), .Y (n_92));
  NAND2XL g4410(.A (in_2[20]), .B (in_2[21]), .Y (n_111));
  NAND2XL g4411(.A (in_0[1]), .B (in_1[2]), .Y (n_110));
  NAND2XL g4412(.A (in_0[6]), .B (n_41), .Y (n_109));
  NAND2XL g4413(.A (in_0[1]), .B (in_1[5]), .Y (n_91));
  NAND2XL g4414(.A (in_0[0]), .B (in_1[2]), .Y (n_108));
  NAND2X2 g4415(.A (in_0[0]), .B (n_41), .Y (n_90));
  NAND2XL g4416(.A (in_0[7]), .B (in_1[5]), .Y (n_107));
  NAND2XL g4417(.A (in_0[7]), .B (in_1[6]), .Y (n_106));
  NAND2X1 g4418(.A (in_0[2]), .B (n_41), .Y (n_89));
  NAND2XL g4419(.A (in_0[5]), .B (in_1[6]), .Y (n_105));
  NAND2XL g4420(.A (in_0[1]), .B (in_1[6]), .Y (n_104));
  AND2X1 g4421(.A (in_0[4]), .B (in_1[2]), .Y (n_103));
  AND2X1 g4422(.A (in_0[7]), .B (n_41), .Y (n_88));
  NAND2X2 g4423(.A (in_0[0]), .B (in_1[6]), .Y (n_87));
  NAND2XL g4424(.A (in_0[5]), .B (in_1[5]), .Y (n_102));
  NAND2XL g4425(.A (in_0[5]), .B (in_1[2]), .Y (n_86));
  NAND2X4 g4426(.A (in_0[4]), .B (n_490), .Y (n_100));
  NAND2X1 g4427(.A (in_0[7]), .B (n_496), .Y (n_98));
  CLKAND2X2 g4428(.A (in_0[2]), .B (in_1[1]), .Y (n_97));
  NAND2X1 g4429(.A (in_0[5]), .B (in_1[1]), .Y (n_40));
  NAND2X2 g4430(.A (in_0[1]), .B (n_492), .Y (n_93));
  INVXL g4431(.A (n_82), .Y (n_81));
  INVX1 g4432(.A (n_74), .Y (n_73));
  CLKINVX1 g4437(.A (n_71), .Y (n_42));
  INVXL g4438(.A (n_70), .Y (n_71));
  NAND2XL g4440(.A (in_0[3]), .B (in_2[7]), .Y (n_68));
  NAND2XL g4441(.A (in_2[17]), .B (in_2[16]), .Y (n_85));
  NAND2XL g4442(.A (in_0[4]), .B (in_1[5]), .Y (n_67));
  NAND2X1 g4443(.A (in_0[2]), .B (in_1[5]), .Y (n_66));
  NAND2XL g4444(.A (in_1[6]), .B (in_0[2]), .Y (n_65));
  NAND2XL g4446(.A (in_0[2]), .B (in_1[2]), .Y (n_84));
  NAND2XL g4447(.A (in_0[3]), .B (n_41), .Y (n_83));
  NAND2X1 g4448(.A (in_0[3]), .B (in_1[6]), .Y (n_64));
  NAND2X1 g4449(.A (in_0[5]), .B (n_41), .Y (n_82));
  NAND2XL g4450(.A (in_0[0]), .B (in_1[5]), .Y (n_80));
  NAND2XL g4451(.A (in_0[6]), .B (in_1[6]), .Y (n_79));
  NAND2XL g4452(.A (in_0[3]), .B (in_1[5]), .Y (n_63));
  NAND2X1 g4453(.A (in_0[6]), .B (in_1[2]), .Y (n_78));
  NAND2XL g4454(.A (in_0[3]), .B (in_1[2]), .Y (n_77));
  NAND2XL g4455(.A (in_0[4]), .B (n_41), .Y (n_76));
  NAND2XL g4456(.A (in_0[4]), .B (in_1[6]), .Y (n_75));
  NAND2XL g4457(.A (in_0[6]), .B (in_1[5]), .Y (n_74));
  NAND2X1 g4458(.A (in_0[1]), .B (in_1[7]), .Y (n_43));
  CLKAND2X2 g4459(.A (in_0[0]), .B (n_496), .Y (n_72));
  NAND2XL g4460(.A (in_0[3]), .B (in_1[1]), .Y (n_62));
  NAND2X2 g4461(.A (in_0[3]), .B (n_498), .Y (n_70));
  NAND2X2 g4462(.A (in_0[6]), .B (n_492), .Y (n_69));
  INVX1 g4463(.A (in_2[22]), .Y (n_61));
  INVXL g4464(.A (in_2[3]), .Y (n_60));
  BUFX3 g4468(.A (in_1[7]), .Y (n_41));
  INVXL g4476(.A (in_2[28]), .Y (n_53));
  CLKINVX1 g4477(.A (in_2[10]), .Y (n_52));
  CLKINVX1 g4478(.A (in_2[13]), .Y (n_51));
  XOR2XL g4486(.A (n_349), .B (n_298), .Y (out_0[14]));
  XOR2XL g4487(.A (n_348), .B (n_314), .Y (out_0[13]));
  XNOR2XL g4488(.A (n_347), .B (n_26), .Y (out_0[11]));
  XOR2XL g4489(.A (n_456), .B (n_330), .Y (out_0[12]));
  XNOR2XL g4490(.A (n_27), .B (n_334), .Y (out_0[10]));
  XOR2XL g4491(.A (n_343), .B (n_335), .Y (out_0[9]));
  NAND2BXL g4492(.AN (n_339), .B (n_337), .Y (n_27));
  NOR2BXL g4493(.AN (n_328), .B (n_321), .Y (n_26));
  OR2X1 g4494(.A (n_288), .B (n_300), .Y (n_25));
  CLKXOR2X1 g4495(.A (n_46), .B (n_216), .Y (n_24));
  NAND2BX1 g4497(.AN (n_244), .B (n_192), .Y (n_22));
  XOR3X1 g4498(.A (n_528), .B (n_15), .C (n_259), .Y (n_21));
  OR2XL g4499(.A (n_205), .B (n_233), .Y (n_20));
  AND2XL g4500(.A (n_205), .B (n_233), .Y (n_19));
  XNOR2X1 g4501(.A (n_219), .B (n_204), .Y (n_18));
  XNOR3XL g4502(.A (n_104), .B (n_220), .C (n_234), .Y (n_17));
  XOR3X1 g4503(.A (n_205), .B (n_233), .C (n_210), .Y (n_16));
  XNOR2X1 g4504(.A (n_209), .B (n_6), .Y (n_15));
  NOR2BX1 g4505(.AN (n_213), .B (n_212), .Y (n_14));
  CLKXOR2X1 g4506(.A (n_206), .B (n_203), .Y (n_13));
  NOR2BX1 g4507(.AN (n_244), .B (n_192), .Y (n_12));
  MXI2X1 g4508(.A (n_263), .B (n_274), .S0 (n_195), .Y (n_11));
  NAND2BX1 g4509(.AN (n_141), .B (n_135), .Y (n_10));
  XOR3X1 g4511(.A (n_103), .B (n_140), .C (n_452), .Y (n_8));
  NAND2BX1 g4512(.AN (n_108), .B (in_2[2]), .Y (n_7));
  XNOR2XL g4513(.A (n_107), .B (n_79), .Y (n_6));
  XNOR2X1 g4514(.A (n_102), .B (n_83), .Y (n_5));
  NAND2BX1 g4515(.AN (n_40), .B (in_2[9]), .Y (n_4));
  XNOR2X1 g4516(.A (n_43), .B (n_78), .Y (n_3));
  CLKXOR2X1 g4517(.A (n_72), .B (in_2[4]), .Y (n_2));
  NAND2BX1 g4518(.AN (n_69), .B (in_2[10]), .Y (n_1));
  AND2X1 g4519(.A (in_0[7]), .B (in_1[2]), .Y (n_0));
  CLKXOR2X1 g4525(.A (in_2[6]), .B (n_96), .Y (n_452));
  XNOR2X1 g4526(.A (n_40), .B (in_2[9]), .Y (n_453));
  XNOR2X1 g4527(.A (n_454), .B (n_281), .Y (out_0[6]));
  NOR2BXL g3(.AN (n_272), .B (n_271), .Y (n_454));
  CLKBUFX2 fopt(.A (n_346), .Y (n_456));
  INVXL fopt4529(.A (n_463), .Y (n_462));
  INVXL fopt4530(.A (n_25), .Y (n_463));
  OAI2BB1XL g4536(.A0N (n_76), .A1N (n_166), .B0 (n_191), .Y (n_472));
  OAI2BB1X1 g4537(.A0N (n_92), .A1N (n_123), .B0 (n_189), .Y (n_473));
  XNOR2X1 g4538(.A (in_2[2]), .B (n_108), .Y (n_474));
  XNOR2XL g4540(.A (n_237), .B (n_14), .Y (out_0[4]));
  CLKBUFX2 fopt4548(.A (n_43), .Y (n_488));
  INVX2 fopt4549(.A (n_491), .Y (n_490));
  CLKINVX1 fopt4550(.A (in_1[1]), .Y (n_491));
  CLKINVX2 fopt4551(.A (n_494), .Y (n_492));
  INVX1 fopt4553(.A (in_1[1]), .Y (n_494));
  INVX1 fopt4555(.A (n_499), .Y (n_496));
  INVX1 fopt4556(.A (n_499), .Y (n_498));
  INVX1 fopt4557(.A (in_1[1]), .Y (n_499));
  XOR2XL g4575(.A (n_301), .B (n_310), .Y (out_0[7]));
  XOR2XL g4576(.A (n_260), .B (n_265), .Y (out_0[5]));
  CLKXOR2X1 g2(.A (n_18), .B (n_8), .Y (n_524));
  XOR2XL g4577(.A (n_473), .B (n_222), .Y (out_0[3]));
  XOR2XL g4578(.A (n_123), .B (n_193), .Y (out_0[2]));
  AOI2BB1X1 g4579(.A0N (n_204), .A1N (n_8), .B0 (n_247), .Y (n_527));
  OAI21X1 g4580(.A0 (n_76), .A1 (n_166), .B0 (n_472), .Y (n_528));
  XNOR2X1 g4581(.A (n_148), .B (n_2), .Y (n_529));
  MX2X1 g4582(.A (n_99), .B (n_98), .S0 (in_2[11]), .Y (n_530));
endmodule

module collision_avoidance_car(clk, rst, front_obstacle_detected,
     left_obstacle_detected, right_obstacle_detected,
     front_obstacle_slow, lane_clear_left, lane_clear_right,
     destination_reached, speed_limit_zone, acceleration, steering,
     indicators, current_speed_out, distance_travelled_out,
     total_power_consumed_out);
  input clk, rst, front_obstacle_detected, left_obstacle_detected,
       right_obstacle_detected, front_obstacle_slow, lane_clear_left,
       lane_clear_right, destination_reached;
  input [1:0] speed_limit_zone;
  output [1:0] acceleration, steering, indicators;
  output [7:0] current_speed_out;
  output [31:0] distance_travelled_out, total_power_consumed_out;
  wire clk, rst, front_obstacle_detected, left_obstacle_detected,
       right_obstacle_detected, front_obstacle_slow, lane_clear_left,
       lane_clear_right, destination_reached;
  wire [1:0] speed_limit_zone;
  wire [1:0] acceleration, steering, indicators;
  wire [7:0] current_speed_out;
  wire [31:0] distance_travelled_out, total_power_consumed_out;
  wire [31:0] distance_travelled;
  wire [7:0] current_speed;
  wire [15:0] integral_error_accumulator;
  wire [31:0] total_power_consumed;
  wire [2:0] front_obstacle_history;
  wire [2:0] left_obstacle_history;
  wire [2:0] right_obstacle_history;
  wire [1:0] speed_limit_zone_reg;
  wire [10:0] next_state;
  wire [10:0] current_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       \acceleration[0]_1483 , destination_reached_reg;
  wire front_obstacle_slow_reg, lane_clear_left_reg,
       lane_clear_right_reg, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_140, n_141, n_142, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_172;
  wire n_173, n_174, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_215, n_216, n_217, n_218;
  wire n_219, n_221, n_223, n_224, n_225, n_226, n_229, n_230;
  wire n_231, n_232, n_234, n_236, n_237, n_238, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_295, n_296, n_297, n_298;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_305, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_312, n_313, n_314;
  wire n_315, n_316, n_317, n_318, n_319, n_320, n_321, n_322;
  wire n_323, n_324, n_325, n_326, n_327, n_328, n_329, n_330;
  wire n_331, n_332, n_333, n_334, n_335, n_336, n_337, n_338;
  wire n_339, n_340, n_341, n_342, n_343, n_344, n_345, n_346;
  wire n_347, n_348, n_349, n_350, n_351, n_352, n_353, n_354;
  wire n_355, n_356, n_357, n_358, n_359, n_360, n_361, n_362;
  wire n_363, n_364, n_365, n_366, n_367, n_368, n_369, n_370;
  wire n_371, n_372, n_373, n_374, n_375, n_376, n_377, n_378;
  wire n_379, n_380, n_381, n_382, n_383, n_384, n_385, n_386;
  wire n_387, n_388, n_389, n_390, n_391, n_392, n_396, n_398;
  wire n_404, n_405, n_406, n_407, n_408, n_409, n_410, n_411;
  wire n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_427, n_428;
  wire n_429, n_430, n_431, n_432, n_433, n_434, n_435, n_436;
  wire n_437, n_438, n_439, n_440, n_441, n_442, n_443, n_444;
  wire n_445, n_446, n_447, n_448, n_449, n_450, n_451, n_452;
  wire n_453, n_454, n_455, n_456, n_457, n_458, n_459, n_460;
  wire n_461, n_462, n_463, n_464, n_465, n_466, n_467, n_468;
  wire n_469, n_470, n_471, n_472, n_473, n_474, n_475, n_476;
  wire n_477, n_478, n_479, n_480, n_481, n_482, n_483, n_484;
  wire n_485, n_486, n_487, n_488, n_489, n_490, n_491, n_492;
  wire n_493, n_494, n_495, n_496, n_497, n_498, n_499, n_500;
  wire n_501, n_502, n_503, n_504, n_505, n_510, n_517, n_518;
  wire n_519, n_525, n_528, n_531, n_534, n_536, n_544, n_548;
  wire n_551, n_559, n_560, n_561, n_569, n_571, n_572, n_957;
  wire n_958, n_959, n_969, n_972, n_978, n_980, n_987, n_1224;
  wire n_1225;
  assign total_power_consumed_out[0] = 1'b0;
  add_unsigned_4 add_152_54(.A (distance_travelled), .B
       (current_speed), .Z ({n_427, n_428, n_429, n_430, n_431, n_432,
       n_433, n_434, n_435, n_436, n_437, n_438, n_439, n_440, n_441,
       n_442, n_443, n_444, n_445, n_446, n_447, n_448, n_449, n_450,
       n_451, n_452, n_453, n_454, n_455, n_456, n_457, n_458}));
  add_signed add_155_74(.A (integral_error_accumulator), .B ({n_408,
       n_421, n_420, n_419, n_418, n_417, n_416, n_415, n_414}), .Z
       ({n_490, n_491, n_492, n_493, n_494, n_495, n_496, n_497, n_498,
       n_499, n_500, n_501, n_502, n_503, n_504, n_505}));
  csa_tree_add_153_58_group_2 csa_tree_add_153_58_groupi(.in_0
       ({current_speed[7:2], n_396, current_speed[0]}), .in_1 ({n_413,
       n_412, n_411, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, n_409,
       n_410, UNCONNECTED_HIER_Z}), .in_2 ({total_power_consumed[31:1],
       UNCONNECTED_HIER_Z2}), .out_0 ({n_459, n_460, n_461, n_462,
       n_463, n_464, n_465, n_466, n_467, n_468, n_469, n_470, n_471,
       n_472, n_473, n_474, n_475, n_476, n_477, n_478, n_479, n_480,
       n_481, n_482, n_483, n_484, n_485, n_486, n_487, n_488, n_489,
       UNCONNECTED}));
  CLKINVX20 g2860(.A (n_398), .Y (acceleration[0]));
  BUFX2 g2864(.A (current_speed[1]), .Y (n_396));
  CLKINVX4 g2861(.A (\acceleration[0]_1483 ), .Y (n_398));
  DFFRHQX4 \acceleration_reg[1] (.RN (n_14), .CK (clk), .D (n_226), .Q
       (n_392));
  DFFRHQX1 destination_reached_reg_reg(.RN (n_14), .CK (clk), .D
       (destination_reached), .Q (destination_reached_reg));
  DFFRHQX1 \front_obstacle_history_reg[0] (.RN (n_14), .CK (clk), .D
       (front_obstacle_detected), .Q (front_obstacle_history[0]));
  DFFRHQX1 \front_obstacle_history_reg[1] (.RN (n_14), .CK (clk), .D
       (front_obstacle_history[0]), .Q (front_obstacle_history[1]));
  DFFRHQX1 \front_obstacle_history_reg[2] (.RN (n_14), .CK (clk), .D
       (front_obstacle_history[1]), .Q (front_obstacle_history[2]));
  DFFRHQX1 front_obstacle_slow_reg_reg(.RN (n_14), .CK (clk), .D
       (front_obstacle_slow), .Q (front_obstacle_slow_reg));
  DFFRHQX1 lane_clear_left_reg_reg(.RN (n_14), .CK (clk), .D
       (lane_clear_left), .Q (lane_clear_left_reg));
  DFFRHQX1 lane_clear_right_reg_reg(.RN (n_14), .CK (clk), .D
       (lane_clear_right), .Q (lane_clear_right_reg));
  DFFRHQX1 \left_obstacle_history_reg[0] (.RN (n_14), .CK (clk), .D
       (left_obstacle_detected), .Q (left_obstacle_history[0]));
  DFFRHQX1 \left_obstacle_history_reg[1] (.RN (n_14), .CK (clk), .D
       (left_obstacle_history[0]), .Q (left_obstacle_history[1]));
  DFFRHQX1 \left_obstacle_history_reg[2] (.RN (n_14), .CK (clk), .D
       (left_obstacle_history[1]), .Q (left_obstacle_history[2]));
  DFFRHQX1 \right_obstacle_history_reg[0] (.RN (n_14), .CK (clk), .D
       (right_obstacle_detected), .Q (right_obstacle_history[0]));
  DFFRHQX1 \right_obstacle_history_reg[1] (.RN (n_14), .CK (clk), .D
       (right_obstacle_history[0]), .Q (right_obstacle_history[1]));
  DFFRHQX1 \right_obstacle_history_reg[2] (.RN (n_14), .CK (clk), .D
       (right_obstacle_history[1]), .Q (right_obstacle_history[2]));
  DFFRHQX1 \speed_limit_zone_reg_reg[0] (.RN (n_14), .CK (clk), .D
       (speed_limit_zone[0]), .Q (speed_limit_zone_reg[0]));
  NAND2X4 g9672(.A (n_312), .B (n_316), .Y (n_410));
  CLKAND2X3 g9673(.A (n_314), .B (n_409), .Y (n_412));
  CLKAND2X3 g9674(.A (n_241), .B (n_314), .Y (n_411));
  CLKAND2X2 g9675(.A (n_307), .B (n_313), .Y (n_316));
  CLKINVX2 g9676(.A (n_315), .Y (n_409));
  CLKINVX2 g9678(.A (n_314), .Y (n_413));
  NOR2X2 g9679(.A (n_309), .B (n_308), .Y (n_315));
  NAND2X2 g9680(.A (n_303), .B (n_308), .Y (n_314));
  NAND2XL g9681(.A (n_310), .B (n_300), .Y (n_313));
  NOR2BX2 g9682(.AN (n_311), .B (n_302), .Y (n_312));
  NAND2XL g9683(.A (n_305), .B (n_295), .Y (n_311));
  NOR2XL g9684(.A (n_304), .B (n_289), .Y (n_310));
  NOR2X1 g9685(.A (n_286), .B (n_306), .Y (n_309));
  OAI21X1 g9686(.A0 (n_250), .A1 (n_510), .B0 (n_241), .Y (n_307));
  OA21X1 g9687(.A0 (n_169), .A1 (n_298), .B0 (n_408), .Y (n_421));
  AOI21X2 g9688(.A0 (n_296), .A1 (n_301), .B0 (n_306), .Y (n_308));
  CLKINVX1 g9689(.A (n_305), .Y (n_306));
  CLKINVX1 g9690(.A (n_304), .Y (n_305));
  NAND2X1 g9691(.A (n_169), .B (n_298), .Y (n_408));
  NAND2X1 g9692(.A (n_241), .B (n_297), .Y (n_304));
  NAND2X1 g9693(.A (n_299), .B (n_296), .Y (n_303));
  NOR2X1 g9694(.A (n_300), .B (n_290), .Y (n_302));
  CLKINVX1 g9695(.A (n_300), .Y (n_301));
  NOR3X1 g9696(.A (n_283), .B (n_287), .C (n_295), .Y (n_299));
  NAND2BX2 g9697(.AN (n_288), .B (n_294), .Y (n_300));
  INVXL g9698(.A (n_297), .Y (n_510));
  CLKINVX1 g9699(.A (n_296), .Y (n_420));
  NAND2XL g9700(.A (n_173), .B (n_291), .Y (n_298));
  AOI211X2 g9701(.A0 (n_262), .A1 (n_164), .B0 (n_266), .C0 (n_275), .Y
       (n_297));
  NOR2BX2 g9702(.AN (n_292), .B (n_293), .Y (n_296));
  BUFX2 g9703(.A (n_295), .Y (n_419));
  INVX1 g9704(.A (n_294), .Y (n_295));
  NOR2BX2 g9706(.AN (n_250), .B (n_165), .Y (n_293));
  OAI211XL g9707(.A0 (n_561), .A1 (n_273), .B0 (n_249), .C0 (n_280), .Y
       (n_292));
  CLKAND2X2 g9708(.A (n_284), .B (n_285), .Y (n_294));
  OR2X1 g9709(.A (n_162), .B (n_165), .Y (n_291));
  NAND2X1 g9710(.A (n_241), .B (n_286), .Y (n_290));
  NOR2X1 g9711(.A (n_283), .B (n_287), .Y (n_289));
  BUFX2 g9712(.A (n_288), .Y (n_418));
  MXI2XL g9713(.A (n_278), .B (n_561), .S0 (n_244), .Y (n_288));
  CLKINVX1 g9715(.A (n_287), .Y (n_286));
  OAI21X1 g9716(.A0 (n_170), .A1 (n_561), .B0 (n_274), .Y (n_285));
  AOI21XL g9717(.A0 (n_278), .A1 (n_277), .B0 (n_276), .Y (n_284));
  NAND2X2 g9718(.A (n_281), .B (n_282), .Y (n_287));
  AND2X1 g9719(.A (n_414), .B (n_416), .Y (n_283));
  NAND2X1 g9720(.A (n_415), .B (n_416), .Y (n_282));
  INVXL g9721(.A (n_281), .Y (n_417));
  AOI2BB2X2 g9723(.A0N (n_163), .A1N (n_271), .B0 (n_972), .B1 (n_272),
       .Y (n_281));
  AOI21X1 g9727(.A0 (n_240), .A1 (n_260), .B0 (n_261), .Y (n_280));
  AOI21X1 g9728(.A0 (n_159), .A1 (n_260), .B0 (n_170), .Y (n_277));
  AOI21XL g9729(.A0 (n_159), .A1 (n_260), .B0 (n_957), .Y (n_276));
  NAND2X2 g9730(.A (n_267), .B (n_263), .Y (n_278));
  OAI2BB1X1 g9731(.A0N (n_159), .A1N (n_245), .B0 (n_264), .Y (n_275));
  NOR2BX1 g9732(.AN (n_260), .B (n_269), .Y (n_274));
  BMXIX2 g9733(.A (n_414), .M0 (current_speed[1]), .M1 (n_6), .S
       (n_219), .X2 (n_231), .PPN (n_415));
  NAND2X2 g9734(.A (n_265), .B (n_268), .Y (n_416));
  BUFX3 g9736(.A (n_271), .Y (n_272));
  OAI2BB1XL g9737(.A0N (n_6), .A1N (n_231), .B0 (n_243), .Y (n_270));
  NAND2XL g9738(.A (n_959), .B (n_260), .Y (n_273));
  NAND2XL g9739(.A (n_957), .B (n_159), .Y (n_269));
  NAND2X1 g9740(.A (n_248), .B (n_259), .Y (n_268));
  AOI21X1 g9741(.A0 (n_248), .A1 (n_256), .B0 (n_255), .Y (n_271));
  AOI21X1 g9742(.A0 (n_252), .A1 (n_237), .B0 (n_242), .Y (n_267));
  NAND2XL g9743(.A (n_251), .B (n_260), .Y (n_266));
  NAND3BX1 g9744(.AN (n_248), .B (n_256), .C (n_253), .Y (n_265));
  NAND2XL g9745(.A (n_246), .B (n_159), .Y (n_264));
  NAND3X2 g9746(.A (n_256), .B (n_237), .C (n_248), .Y (n_263));
  INVX1 g9747(.A (n_261), .Y (n_262));
  INVX1 g9748(.A (n_159), .Y (n_261));
  NAND2X1 g9750(.A (n_256), .B (n_254), .Y (n_259));
  NAND2X2 g9751(.A (current_speed[5]), .B (n_258), .Y (n_260));
  CLKINVX1 g9753(.A (n_257), .Y (n_258));
  INVX1 g9754(.A (n_254), .Y (n_255));
  CLKINVX1 g9755(.A (n_252), .Y (n_254));
  INVXL g9757(.A (n_252), .Y (n_253));
  NOR2BX1 g9758(.AN (n_169), .B (n_162), .Y (n_251));
  NAND2X2 g9760(.A (n_232), .B (n_236), .Y (n_257));
  NAND2X2 g9761(.A (current_speed[2]), .B (n_238), .Y (n_256));
  NOR2X2 g9762(.A (current_speed[2]), .B (n_238), .Y (n_252));
  CLKINVX1 g9763(.A (n_249), .Y (n_250));
  NAND2XL g9764(.A (n_173), .B (n_957), .Y (n_247));
  NOR2XL g9765(.A (n_959), .B (n_172), .Y (n_246));
  NOR2XL g9766(.A (n_172), .B (n_237), .Y (n_245));
  NAND2XL g9767(.A (n_959), .B (n_957), .Y (n_244));
  NOR2XL g9768(.A (n_162), .B (n_172), .Y (n_249));
  OAI21X2 g9769(.A0 (n_225), .A1 (n_230), .B0 (n_224), .Y (n_248));
  CLKINVX1 g9770(.A (n_242), .Y (n_243));
  INVXL g9771(.A (n_957), .Y (n_240));
  CLKINVX1 g9774(.A (n_172), .Y (n_173));
  NOR2X1 g9775(.A (current_speed[3]), .B (n_234), .Y (n_242));
  NOR2BX1 g9776(.AN (n_980), .B (\acceleration[0]_1483 ), .Y (n_241));
  NOR2X1 g9778(.A (current_speed[6]), .B (n_232), .Y (n_172));
  CLKINVX1 g9783(.A (n_959), .Y (n_170));
  AOI21X2 g9784(.A0 (current_speed[5]), .A1 (n_536), .B0 (n_229), .Y
       (n_236));
  AOI22X2 g9785(.A0 (n_196), .A1 (n_226), .B0 (current_speed[2]), .B1
       (n_536), .Y (n_238));
  NAND2X2 g9787(.A (n_234), .B (n_223), .Y (n_237));
  NAND2X2 g9794(.A (n_166), .B (n_226), .Y (n_234));
  INVXL g9796(.A (n_230), .Y (n_231));
  AOI21X1 g9797(.A0 (n_215), .A1 (n_208), .B0 (n_195), .Y (n_229));
  NAND2X2 g9798(.A (n_194), .B (n_226), .Y (n_232));
  NOR3BX2 g9799(.AN (n_216), .B (n_518), .C (n_517), .Y (n_230));
  BUFX20 g9800(.A (n_388), .Y (indicators[0]));
  BUFX20 g9801(.A (n_389), .Y (indicators[1]));
  NAND2XL g9808(.A (current_speed[7]), .B (n_221), .Y (n_169));
  NOR2X1 g9809(.A (n_218), .B (n_6), .Y (n_225));
  NAND2XL g9810(.A (n_218), .B (n_6), .Y (n_224));
  AND2X1 g9811(.A (current_speed[3]), .B (n_221), .Y (n_223));
  NAND3X4 g9813(.A (n_208), .B (n_213), .C (n_207), .Y (n_226));
  BUFX20 g9814(.A (n_391), .Y (steering[1]));
  BUFX20 g9815(.A (n_390), .Y (steering[0]));
  CLKINVX1 g9818(.A (n_414), .Y (n_219));
  CLKINVX1 g9819(.A (n_218), .Y (n_414));
  NOR2X2 g9822(.A (n_209), .B (n_211), .Y (n_221));
  OAI21X1 g9823(.A0 (n_1225), .A1 (n_205), .B0 (current_speed[0]), .Y
       (n_218));
  OR2X1 g9824(.A (n_422), .B (next_state[7]), .Y (n_217));
  NAND2XL g9825(.A (n_197), .B (n_206), .Y (n_216));
  OAI21XL g9827(.A0 (n_204), .A1 (n_160), .B0 (n_190), .Y (n_215));
  INVXL g9829(.A (n_213), .Y (n_424));
  INVX1 g9830(.A (n_212), .Y (next_state[5]));
  INVXL g9831(.A (n_211), .Y (n_212));
  INVX1 g9833(.A (n_210), .Y (next_state[7]));
  INVXL g9834(.A (n_209), .Y (n_210));
  NAND2X2 g9835(.A (n_190), .B (n_204), .Y (n_213));
  NOR2X2 g9836(.A (n_425), .B (n_203), .Y (n_211));
  NOR2X2 g9837(.A (n_425), .B (n_202), .Y (n_209));
  INVX2 g9838(.A (n_206), .Y (n_207));
  CLKBUFX2 g9841(.A (n_206), .Y (n_423));
  NOR3BX1 g9842(.AN (n_405), .B (n_193), .C (n_544), .Y (n_422));
  NAND3X4 g9843(.A (n_192), .B (n_548), .C (n_405), .Y (n_208));
  NOR2X2 g9844(.A (n_425), .B (n_200), .Y (n_206));
  AOI22XL g9849(.A0 (n_185), .A1 (n_167), .B0 (n_168), .B1 (n_184), .Y
       (n_205));
  NAND2X2 g9850(.A (n_191), .B (n_190), .Y (n_200));
  NOR2X2 g9852(.A (n_407), .B (n_188), .Y (n_204));
  NAND2X2 g9853(.A (n_404), .B (n_186), .Y (n_203));
  NAND2X2 g9854(.A (n_404), .B (n_187), .Y (n_202));
  NAND2XL g9855(.A (current_speed[1]), .B (n_548), .Y (n_201));
  INVX1 g9856(.A (n_197), .Y (n_198));
  NAND2XL g9860(.A (speed_limit_zone_reg[1]), .B
       (speed_limit_zone_reg[0]), .Y (n_196));
  NAND2XL g9861(.A (speed_limit_zone_reg[0]), .B (n_166), .Y (n_195));
  NOR2XL g9862(.A (speed_limit_zone_reg[0]), .B (n_166), .Y (n_194));
  NOR2XL g9866(.A (speed_limit_zone_reg[1]), .B
       (speed_limit_zone_reg[0]), .Y (n_197));
  CLKAND2X3 g9867(.A (n_174), .B (n_406), .Y (n_404));
  INVXL g9868(.A (n_192), .Y (n_193));
  NAND2X1 g9874(.A (n_179), .B (n_182), .Y (n_188));
  CLKAND2X2 g9875(.A (n_167), .B (n_185), .Y (n_187));
  CLKAND2X2 g9876(.A (n_168), .B (n_184), .Y (n_186));
  CLKAND2X2 g9877(.A (current_state[7]), .B (n_406), .Y (n_192));
  NOR3X2 g9878(.A (n_560), .B (current_state[4]), .C
       (current_state[7]), .Y (n_191));
  CLKAND2X3 g9879(.A (n_406), .B (n_183), .Y (n_190));
  CLKAND2X2 g9880(.A (n_181), .B (n_168), .Y (n_405));
  NAND2X6 g9881(.A (n_178), .B (n_180), .Y (n_425));
  BUFX20 g9882(.A (n_329), .Y (total_power_consumed_out[13]));
  BUFX20 g9883(.A (n_361), .Y (distance_travelled_out[13]));
  BUFX20 g9884(.A (n_328), .Y (total_power_consumed_out[12]));
  BUFX20 g9885(.A (n_385), .Y (current_speed_out[5]));
  BUFX20 g9886(.A (n_377), .Y (distance_travelled_out[29]));
  BUFX20 g9887(.A (n_327), .Y (total_power_consumed_out[11]));
  BUFX20 g9888(.A (n_326), .Y (total_power_consumed_out[10]));
  BUFX20 g9889(.A (n_325), .Y (total_power_consumed_out[9]));
  BUFX20 g9890(.A (n_324), .Y (total_power_consumed_out[8]));
  BUFX20 g9891(.A (n_323), .Y (total_power_consumed_out[7]));
  BUFX20 g9892(.A (n_322), .Y (total_power_consumed_out[6]));
  BUFX20 g9893(.A (n_375), .Y (distance_travelled_out[27]));
  BUFX20 g9894(.A (n_350), .Y (distance_travelled_out[2]));
  BUFX20 g9895(.A (n_321), .Y (total_power_consumed_out[5]));
  BUFX20 g9896(.A (n_357), .Y (distance_travelled_out[9]));
  BUFX20 g9897(.A (n_320), .Y (total_power_consumed_out[4]));
  BUFX20 g9898(.A (n_356), .Y (distance_travelled_out[8]));
  BUFX20 g9899(.A (n_319), .Y (total_power_consumed_out[3]));
  BUFX20 g9900(.A (n_318), .Y (total_power_consumed_out[2]));
  BUFX20 g9901(.A (n_362), .Y (distance_travelled_out[14]));
  BUFX20 g9902(.A (n_317), .Y (total_power_consumed_out[1]));
  BUFX20 g9903(.A (n_374), .Y (distance_travelled_out[26]));
  BUFX20 g9904(.A (n_359), .Y (distance_travelled_out[11]));
  BUFX20 g9905(.A (n_355), .Y (distance_travelled_out[7]));
  BUFX20 g9906(.A (n_354), .Y (distance_travelled_out[6]));
  BUFX20 g9907(.A (n_384), .Y (current_speed_out[4]));
  BUFX20 g9908(.A (n_353), .Y (distance_travelled_out[5]));
  BUFX20 g9909(.A (n_383), .Y (current_speed_out[3]));
  BUFX20 g9910(.A (n_373), .Y (distance_travelled_out[25]));
  BUFX20 g9911(.A (n_352), .Y (distance_travelled_out[4]));
  BUFX20 g9912(.A (n_376), .Y (distance_travelled_out[28]));
  BUFX20 g9913(.A (n_379), .Y (distance_travelled_out[31]));
  BUFX20 g9914(.A (n_358), .Y (distance_travelled_out[10]));
  BUFX20 g9915(.A (n_351), .Y (distance_travelled_out[3]));
  BUFX20 g9916(.A (n_372), .Y (distance_travelled_out[24]));
  BUFX20 g9917(.A (n_382), .Y (current_speed_out[2]));
  BUFX20 g9918(.A (n_349), .Y (distance_travelled_out[1]));
  BUFX20 g9919(.A (n_371), .Y (distance_travelled_out[23]));
  BUFX20 g9920(.A (n_378), .Y (distance_travelled_out[30]));
  BUFX20 g9921(.A (n_348), .Y (distance_travelled_out[0]));
  BUFX20 g9922(.A (n_370), .Y (distance_travelled_out[22]));
  BUFX20 g9923(.A (n_347), .Y (total_power_consumed_out[31]));
  BUFX20 g9924(.A (n_346), .Y (total_power_consumed_out[30]));
  BUFX20 g9970(.A (n_369), .Y (distance_travelled_out[21]));
  BUFX20 g9971(.A (n_345), .Y (total_power_consumed_out[29]));
  BUFX20 g9972(.A (n_344), .Y (total_power_consumed_out[28]));
  BUFX20 g9973(.A (n_343), .Y (total_power_consumed_out[27]));
  BUFX20 g9974(.A (n_381), .Y (current_speed_out[1]));
  BUFX20 g9975(.A (n_368), .Y (distance_travelled_out[20]));
  BUFX20 g9976(.A (n_342), .Y (total_power_consumed_out[26]));
  BUFX20 g9977(.A (n_387), .Y (current_speed_out[7]));
  BUFX20 g9978(.A (n_367), .Y (distance_travelled_out[19]));
  BUFX20 g9979(.A (n_341), .Y (total_power_consumed_out[25]));
  BUFX20 g9980(.A (n_340), .Y (total_power_consumed_out[24]));
  BUFX20 g9981(.A (n_380), .Y (current_speed_out[0]));
  BUFX20 g9982(.A (n_339), .Y (total_power_consumed_out[23]));
  BUFX20 g9983(.A (n_366), .Y (distance_travelled_out[18]));
  BUFX20 g9984(.A (n_338), .Y (total_power_consumed_out[22]));
  BUFX20 g9985(.A (n_360), .Y (distance_travelled_out[12]));
  BUFX20 g9986(.A (n_337), .Y (total_power_consumed_out[21]));
  BUFX20 g9987(.A (n_365), .Y (distance_travelled_out[17]));
  BUFX20 g9988(.A (n_336), .Y (total_power_consumed_out[20]));
  BUFX20 g9989(.A (n_386), .Y (current_speed_out[6]));
  BUFX20 g9990(.A (n_364), .Y (distance_travelled_out[16]));
  BUFX20 g9991(.A (n_335), .Y (total_power_consumed_out[19]));
  BUFX20 g9992(.A (n_334), .Y (total_power_consumed_out[18]));
  BUFX20 g9993(.A (n_333), .Y (total_power_consumed_out[17]));
  BUFX20 g9994(.A (n_363), .Y (distance_travelled_out[15]));
  BUFX20 g9995(.A (n_332), .Y (total_power_consumed_out[16]));
  BUFX20 g9996(.A (n_331), .Y (total_power_consumed_out[15]));
  BUFX20 g9997(.A (n_330), .Y (total_power_consumed_out[14]));
  CLKINVX1 g10001(.A (n_167), .Y (n_407));
  NOR2X1 g10016(.A (current_state[6]), .B (current_state[3]), .Y
       (n_183));
  NOR2BX1 g10019(.AN (current_state[1]), .B (current_state[7]), .Y
       (n_182));
  NOR2BX1 g10021(.AN (current_state[6]), .B (current_state[3]), .Y
       (n_185));
  NOR2BX1 g10027(.AN (current_state[4]), .B (current_state[3]), .Y
       (n_184));
  NOR2XL g10038(.A (current_state[3]), .B (current_state[4]), .Y
       (n_181));
  NOR2X4 g10039(.A (current_state[2]), .B (current_state[1]), .Y
       (n_180));
  NOR2X1 g10040(.A (current_state[2]), .B (current_state[0]), .Y
       (n_179));
  NOR2X1 g10042(.A (current_state[5]), .B (current_state[6]), .Y
       (n_168));
  NOR2X1 g10044(.A (current_state[5]), .B (current_state[4]), .Y
       (n_167));
  NOR2X4 g10045(.A (current_state[10]), .B (current_state[8]), .Y
       (n_406));
  CLKINVX2 g10048(.A (current_state[0]), .Y (n_178));
  INVXL g10051(.A (rst), .Y (n_14));
  CLKINVX1 g10053(.A (current_state[7]), .Y (n_174));
  DFFRX1 \speed_limit_zone_reg_reg[1] (.RN (n_14), .CK (clk), .D
       (speed_limit_zone[1]), .Q (speed_limit_zone_reg[1]), .QN
       (n_166));
  OA21X1 g2(.A0 (n_273), .A1 (n_561), .B0 (n_280), .Y (n_165));
  NOR3BX1 g10056(.AN (n_253), .B (n_270), .C (n_247), .Y (n_164));
  AND2X1 g10057(.A (n_243), .B (n_237), .Y (n_163));
  NOR2BX1 g10058(.AN (n_232), .B (n_1224), .Y (n_162));
  NAND2BX1 g10059(.AN (n_423), .B (n_212), .Y (n_161));
  NOR2BXL g10060(.AN (n_191), .B (n_425), .Y (n_160));
  NAND2BX2 g10062(.AN (current_speed[5]), .B (n_257), .Y (n_159));
  DFFSHQX2 \acceleration_reg[0] (.SN (n_14), .CK (clk), .D (n_115), .Q
       (\acceleration[0]_1483 ));
  DFFRHQX4 \current_state_reg[1] (.RN (n_14), .CK (clk), .D (n_138), .Q
       (current_state[1]));
  DFFRHQX4 \current_state_reg[2] (.RN (n_14), .CK (clk), .D (n_134), .Q
       (current_state[2]));
  DFFRHQX4 \current_state_reg[4] (.RN (n_14), .CK (clk), .D (n_109), .Q
       (current_state[4]));
  DFFRHQX4 \current_state_reg[6] (.RN (n_14), .CK (clk), .D (n_4), .Q
       (current_state[6]));
  DFFRHQX4 \current_state_reg[7] (.RN (n_14), .CK (clk), .D
       (next_state[7]), .Q (current_state[7]));
  DFFRHQX4 \current_state_reg[10] (.RN (n_14), .CK (clk), .D (n_122),
       .Q (current_state[10]));
  DFFRHQX1 \distance_travelled_reg[0] (.RN (n_14), .CK (clk), .D
       (n_458), .Q (distance_travelled[0]));
  DFFRHQX1 \distance_travelled_reg[1] (.RN (n_14), .CK (clk), .D
       (n_457), .Q (distance_travelled[1]));
  DFFRHQX1 \distance_travelled_reg[2] (.RN (n_14), .CK (clk), .D
       (n_456), .Q (distance_travelled[2]));
  DFFRHQX1 \distance_travelled_reg[3] (.RN (n_14), .CK (clk), .D
       (n_455), .Q (distance_travelled[3]));
  DFFRHQX1 \distance_travelled_reg[4] (.RN (n_14), .CK (clk), .D
       (n_454), .Q (distance_travelled[4]));
  DFFRHQX1 \distance_travelled_reg[5] (.RN (n_14), .CK (clk), .D
       (n_453), .Q (distance_travelled[5]));
  DFFRHQX1 \distance_travelled_reg[6] (.RN (n_14), .CK (clk), .D
       (n_452), .Q (distance_travelled[6]));
  DFFRHQX1 \distance_travelled_reg[7] (.RN (n_14), .CK (clk), .D
       (n_451), .Q (distance_travelled[7]));
  DFFRHQX1 \distance_travelled_reg[8] (.RN (n_14), .CK (clk), .D
       (n_450), .Q (distance_travelled[8]));
  DFFRHQX1 \distance_travelled_reg[9] (.RN (n_14), .CK (clk), .D
       (n_449), .Q (distance_travelled[9]));
  DFFRHQX1 \distance_travelled_reg[10] (.RN (n_14), .CK (clk), .D
       (n_448), .Q (distance_travelled[10]));
  DFFRHQX1 \distance_travelled_reg[11] (.RN (n_14), .CK (clk), .D
       (n_447), .Q (distance_travelled[11]));
  DFFRHQX1 \distance_travelled_reg[12] (.RN (n_14), .CK (clk), .D
       (n_446), .Q (distance_travelled[12]));
  DFFRHQX1 \distance_travelled_reg[13] (.RN (n_14), .CK (clk), .D
       (n_445), .Q (distance_travelled[13]));
  DFFRHQX1 \distance_travelled_reg[14] (.RN (n_14), .CK (clk), .D
       (n_444), .Q (distance_travelled[14]));
  DFFRHQX1 \distance_travelled_reg[15] (.RN (n_14), .CK (clk), .D
       (n_443), .Q (distance_travelled[15]));
  DFFRHQX1 \distance_travelled_reg[16] (.RN (n_14), .CK (clk), .D
       (n_442), .Q (distance_travelled[16]));
  DFFRHQX1 \distance_travelled_reg[17] (.RN (n_14), .CK (clk), .D
       (n_441), .Q (distance_travelled[17]));
  DFFRHQX1 \distance_travelled_reg[18] (.RN (n_14), .CK (clk), .D
       (n_440), .Q (distance_travelled[18]));
  DFFRHQX1 \distance_travelled_reg[19] (.RN (n_14), .CK (clk), .D
       (n_439), .Q (distance_travelled[19]));
  DFFRHQX1 \distance_travelled_reg[20] (.RN (n_14), .CK (clk), .D
       (n_438), .Q (distance_travelled[20]));
  DFFRHQX1 \distance_travelled_reg[21] (.RN (n_14), .CK (clk), .D
       (n_437), .Q (distance_travelled[21]));
  DFFRHQX1 \distance_travelled_reg[22] (.RN (n_14), .CK (clk), .D
       (n_436), .Q (distance_travelled[22]));
  DFFRHQX1 \distance_travelled_reg[23] (.RN (n_14), .CK (clk), .D
       (n_435), .Q (distance_travelled[23]));
  DFFRHQX1 \distance_travelled_reg[24] (.RN (n_14), .CK (clk), .D
       (n_434), .Q (distance_travelled[24]));
  DFFRHQX1 \distance_travelled_reg[25] (.RN (n_14), .CK (clk), .D
       (n_433), .Q (distance_travelled[25]));
  DFFRHQX1 \distance_travelled_reg[26] (.RN (n_14), .CK (clk), .D
       (n_432), .Q (distance_travelled[26]));
  DFFRHQX1 \distance_travelled_reg[27] (.RN (n_14), .CK (clk), .D
       (n_431), .Q (distance_travelled[27]));
  DFFRHQX1 \distance_travelled_reg[28] (.RN (n_14), .CK (clk), .D
       (n_430), .Q (distance_travelled[28]));
  DFFRHQX1 \distance_travelled_reg[29] (.RN (n_14), .CK (clk), .D
       (n_429), .Q (distance_travelled[29]));
  DFFRHQX1 \distance_travelled_reg[30] (.RN (n_14), .CK (clk), .D
       (n_428), .Q (distance_travelled[30]));
  DFFRHQX1 \distance_travelled_reg[31] (.RN (n_14), .CK (clk), .D
       (n_427), .Q (distance_travelled[31]));
  DFFRHQX1 \integral_error_accumulator_reg[0] (.RN (n_14), .CK (clk),
       .D (n_85), .Q (integral_error_accumulator[0]));
  DFFRHQX1 \integral_error_accumulator_reg[1] (.RN (n_14), .CK (clk),
       .D (n_75), .Q (integral_error_accumulator[1]));
  DFFRHQX1 \integral_error_accumulator_reg[2] (.RN (n_14), .CK (clk),
       .D (n_84), .Q (integral_error_accumulator[2]));
  DFFRHQX1 \integral_error_accumulator_reg[3] (.RN (n_14), .CK (clk),
       .D (n_76), .Q (integral_error_accumulator[3]));
  DFFRHQX1 \integral_error_accumulator_reg[4] (.RN (n_14), .CK (clk),
       .D (n_83), .Q (integral_error_accumulator[4]));
  DFFRHQX1 \integral_error_accumulator_reg[5] (.RN (n_14), .CK (clk),
       .D (n_65), .Q (integral_error_accumulator[5]));
  DFFRHQX1 \integral_error_accumulator_reg[6] (.RN (n_14), .CK (clk),
       .D (n_68), .Q (integral_error_accumulator[6]));
  DFFRHQX1 \integral_error_accumulator_reg[7] (.RN (n_14), .CK (clk),
       .D (n_80), .Q (integral_error_accumulator[7]));
  DFFRHQX1 \integral_error_accumulator_reg[8] (.RN (n_14), .CK (clk),
       .D (n_82), .Q (integral_error_accumulator[8]));
  DFFRHQX1 \integral_error_accumulator_reg[9] (.RN (n_14), .CK (clk),
       .D (n_67), .Q (integral_error_accumulator[9]));
  DFFRHQX1 \integral_error_accumulator_reg[10] (.RN (n_14), .CK (clk),
       .D (n_64), .Q (integral_error_accumulator[10]));
  DFFRHQX1 \integral_error_accumulator_reg[11] (.RN (n_14), .CK (clk),
       .D (n_66), .Q (integral_error_accumulator[11]));
  DFFRHQX1 \integral_error_accumulator_reg[12] (.RN (n_14), .CK (clk),
       .D (n_81), .Q (integral_error_accumulator[12]));
  DFFRHQX1 \integral_error_accumulator_reg[13] (.RN (n_14), .CK (clk),
       .D (n_79), .Q (integral_error_accumulator[13]));
  DFFRHQX1 \integral_error_accumulator_reg[14] (.RN (n_14), .CK (clk),
       .D (n_78), .Q (integral_error_accumulator[14]));
  DFFRHQX1 \integral_error_accumulator_reg[15] (.RN (n_14), .CK (clk),
       .D (n_77), .Q (integral_error_accumulator[15]));
  DFFRHQX1 \total_power_consumed_reg[1] (.RN (n_14), .CK (clk), .D
       (n_489), .Q (total_power_consumed[1]));
  DFFRHQX1 \total_power_consumed_reg[2] (.RN (n_14), .CK (clk), .D
       (n_488), .Q (total_power_consumed[2]));
  DFFRHQX1 \total_power_consumed_reg[3] (.RN (n_14), .CK (clk), .D
       (n_487), .Q (total_power_consumed[3]));
  DFFRHQX1 \total_power_consumed_reg[4] (.RN (n_14), .CK (clk), .D
       (n_486), .Q (total_power_consumed[4]));
  DFFRHQX1 \total_power_consumed_reg[5] (.RN (n_14), .CK (clk), .D
       (n_485), .Q (total_power_consumed[5]));
  DFFRHQX1 \total_power_consumed_reg[6] (.RN (n_14), .CK (clk), .D
       (n_484), .Q (total_power_consumed[6]));
  DFFRHQX1 \total_power_consumed_reg[7] (.RN (n_14), .CK (clk), .D
       (n_483), .Q (total_power_consumed[7]));
  DFFRHQX1 \total_power_consumed_reg[8] (.RN (n_14), .CK (clk), .D
       (n_482), .Q (total_power_consumed[8]));
  DFFRHQX1 \total_power_consumed_reg[9] (.RN (n_14), .CK (clk), .D
       (n_481), .Q (total_power_consumed[9]));
  DFFRHQX1 \total_power_consumed_reg[10] (.RN (n_14), .CK (clk), .D
       (n_480), .Q (total_power_consumed[10]));
  DFFRHQX1 \total_power_consumed_reg[11] (.RN (n_14), .CK (clk), .D
       (n_479), .Q (total_power_consumed[11]));
  DFFRHQX1 \total_power_consumed_reg[12] (.RN (n_14), .CK (clk), .D
       (n_478), .Q (total_power_consumed[12]));
  DFFRHQX8 \total_power_consumed_reg[13] (.RN (n_14), .CK (clk), .D
       (n_477), .Q (total_power_consumed[13]));
  DFFRHQX1 \total_power_consumed_reg[14] (.RN (n_14), .CK (clk), .D
       (n_476), .Q (total_power_consumed[14]));
  DFFRHQX1 \total_power_consumed_reg[15] (.RN (n_14), .CK (clk), .D
       (n_475), .Q (total_power_consumed[15]));
  DFFRHQX8 \total_power_consumed_reg[16] (.RN (n_14), .CK (clk), .D
       (n_474), .Q (total_power_consumed[16]));
  DFFRHQX1 \total_power_consumed_reg[17] (.RN (n_14), .CK (clk), .D
       (n_473), .Q (total_power_consumed[17]));
  DFFRHQX8 \total_power_consumed_reg[18] (.RN (n_14), .CK (clk), .D
       (n_472), .Q (total_power_consumed[18]));
  DFFRHQX8 \total_power_consumed_reg[19] (.RN (n_14), .CK (clk), .D
       (n_471), .Q (total_power_consumed[19]));
  DFFRHQX8 \total_power_consumed_reg[20] (.RN (n_14), .CK (clk), .D
       (n_470), .Q (total_power_consumed[20]));
  DFFRHQX1 \total_power_consumed_reg[21] (.RN (n_14), .CK (clk), .D
       (n_469), .Q (total_power_consumed[21]));
  DFFRHQX8 \total_power_consumed_reg[22] (.RN (n_14), .CK (clk), .D
       (n_468), .Q (total_power_consumed[22]));
  DFFRHQX1 \total_power_consumed_reg[23] (.RN (n_14), .CK (clk), .D
       (n_467), .Q (total_power_consumed[23]));
  DFFRHQX8 \total_power_consumed_reg[24] (.RN (n_14), .CK (clk), .D
       (n_466), .Q (total_power_consumed[24]));
  DFFRHQX8 \total_power_consumed_reg[25] (.RN (n_14), .CK (clk), .D
       (n_465), .Q (total_power_consumed[25]));
  DFFRHQX8 \total_power_consumed_reg[26] (.RN (n_14), .CK (clk), .D
       (n_464), .Q (total_power_consumed[26]));
  DFFRHQX1 \total_power_consumed_reg[27] (.RN (n_14), .CK (clk), .D
       (n_463), .Q (total_power_consumed[27]));
  DFFRHQX8 \total_power_consumed_reg[28] (.RN (n_14), .CK (clk), .D
       (n_462), .Q (total_power_consumed[28]));
  DFFRHQX1 \total_power_consumed_reg[29] (.RN (n_14), .CK (clk), .D
       (n_461), .Q (total_power_consumed[29]));
  DFFRHQX8 \total_power_consumed_reg[30] (.RN (n_14), .CK (clk), .D
       (n_460), .Q (total_power_consumed[30]));
  DFFRHQX8 \total_power_consumed_reg[31] (.RN (n_14), .CK (clk), .D
       (n_459), .Q (total_power_consumed[31]));
  OAI21X1 g5715(.A0 (n_978), .A1 (n_156), .B0 (n_137), .Y (n_158));
  OAI222XL g5717(.A0 (n_11), .A1 (n_124), .B0 (n_978), .B1 (n_153), .C0
       (n_116), .C1 (current_speed[6]), .Y (n_157));
  AOI21X1 g5718(.A0 (n_95), .A1 (n_154), .B0 (n_155), .Y (n_156));
  NOR2XL g5719(.A (n_95), .B (n_154), .Y (n_155));
  ADDFXL g5720(.A (n_20), .B (n_37), .CI (n_151), .CO (n_154), .S
       (n_153));
  OAI211X1 g5722(.A0 (n_978), .A1 (n_149), .B0 (n_116), .C0 (n_123), .Y
       (n_152));
  AOI21X1 g5724(.A0 (n_86), .A1 (n_146), .B0 (n_87), .Y (n_151));
  OAI222XL g5725(.A0 (n_63), .A1 (n_71), .B0 (n_978), .B1 (n_147), .C0
       (n_19), .C1 (n_12), .Y (n_150));
  AOI21X1 g5726(.A0 (n_94), .A1 (n_146), .B0 (n_148), .Y (n_149));
  NOR2XL g5727(.A (n_94), .B (n_146), .Y (n_148));
  INVXL g5728(.A (n_145), .Y (n_147));
  ADDFX1 g5729(.A (n_100), .B (n_30), .CI (n_141), .CO (n_146), .S
       (n_145));
  INVXL g5731(.A (n_571), .Y (n_144));
  ADDFX1 g5733(.A (n_45), .B (n_101), .CI (n_129), .CO (n_141), .S
       (n_142));
  INVXL g5735(.A (n_569), .Y (n_140));
  NAND4BXL g5742(.AN (n_69), .B (n_111), .C (n_25), .D (n_958), .Y
       (n_138));
  AOI21X1 g5743(.A0 (current_speed[7]), .A1 (n_125), .B0 (n_120), .Y
       (n_137));
  OAI22X1 g5745(.A0 (n_9), .A1 (n_128), .B0 (n_54), .B1 (n_73), .Y
       (n_136));
  AO22XL g5746(.A0 (n_528), .A1 (n_127), .B0 (n_40), .B1 (n_98), .Y
       (n_135));
  AO22XL g5747(.A0 (current_state[2]), .A1 (n_127), .B0 (n_97), .B1
       (n_510), .Y (n_134));
  OAI222XL g5748(.A0 (n_98), .A1 (n_103), .B0 (n_10), .B1 (n_128), .C0
       (n_50), .C1 (n_3), .Y (n_133));
  OAI21X1 g5751(.A0 (n_107), .A1 (n_118), .B0 (n_126), .Y (n_130));
  OAI2BB1X1 g5752(.A0N (n_112), .A1N (n_107), .B0 (n_5), .Y (n_129));
  INVX1 g5755(.A (n_128), .Y (n_127));
  NAND2XL g5756(.A (n_107), .B (n_118), .Y (n_126));
  OAI21X1 g5757(.A0 (n_11), .A1 (n_71), .B0 (n_124), .Y (n_125));
  AOI2BB1X1 g5758(.A0N (destination_reached_reg), .A1N (n_519), .B0
       (n_121), .Y (n_128));
  NAND2XL g5759(.A (current_speed[5]), .B (n_117), .Y (n_123));
  AOI21X1 g5760(.A0 (current_speed[5]), .A1 (n_70), .B0 (n_117), .Y
       (n_124));
  OAI2BB1XL g5762(.A0N (destination_reached_reg), .A1N (n_110), .B0
       (n_1), .Y (n_122));
  OAI211X1 g5763(.A0 (n_96), .A1 (n_510), .B0 (n_90), .C0 (n_104), .Y
       (n_121));
  NOR3X1 g5764(.A (current_speed[6]), .B (current_speed[7]), .C
       (n_116), .Y (n_120));
  OAI31X1 g5765(.A0 (current_speed[0]), .A1 (n_978), .A2 (n_36), .B0
       (n_113), .Y (n_119));
  NAND2XL g5766(.A (n_112), .B (n_5), .Y (n_118));
  OAI21X1 g5768(.A0 (n_58), .A1 (n_71), .B0 (n_19), .Y (n_117));
  OAI21X1 g5770(.A0 (n_24), .A1 (n_21), .B0 (n_102), .Y (n_115));
  MXI2XL g5771(.A (current_speed[1]), .B (n_6), .S0 (n_88), .Y (n_114));
  OAI31X1 g5772(.A0 (n_18), .A1 (n_70), .A2 (n_36), .B0
       (current_speed[0]), .Y (n_113));
  NAND3X1 g5773(.A (n_7), .B (n_58), .C (n_70), .Y (n_116));
  NAND4BXL g5774(.AN (n_72), .B (n_57), .C (n_60), .D (n_56), .Y
       (n_111));
  OAI21X1 g5775(.A0 (n_55), .A1 (n_73), .B0 (n_0), .Y (n_110));
  NOR2XL g5776(.A (n_57), .B (n_93), .Y (n_109));
  NAND2BX1 g5778(.AN (n_74), .B (n_26), .Y (n_112));
  AOI21XL g5781(.A0 (current_speed[1]), .A1 (n_18), .B0 (n_99), .Y
       (n_105));
  NAND4XL g5782(.A (front_obstacle_slow_reg), .B (n_57), .C (n_60), .D
       (n_92), .Y (n_104));
  NAND4XL g5783(.A (n_0), .B (n_50), .C (n_25), .D (n_62), .Y (n_103));
  AOI21X1 g5784(.A0 (n_24), .A1 (n_21), .B0 (n_89), .Y (n_102));
  OAI21X1 g5785(.A0 (n_6), .A1 (n_71), .B0 (n_19), .Y (n_108));
  OAI2BB1X1 g5786(.A0N (current_speed[1]), .A1N (n_2), .B0 (n_91), .Y
       (n_107));
  ADDFXL g5787(.A (current_speed[3]), .B
       (integral_error_accumulator[11]), .CI (n_413), .CO (n_100), .S
       (n_101));
  INVXL g5801(.A (n_96), .Y (n_97));
  INVX1 g5802(.A (n_92), .Y (n_93));
  OAI21X1 g5803(.A0 (current_speed[1]), .A1 (n_2), .B0 (n_59), .Y
       (n_91));
  NAND2BX1 g5804(.AN (n_50), .B (n_3), .Y (n_90));
  OAI211XL g5805(.A0 (n_551), .A1 (n_404), .B0 (n_34), .C0 (n_46), .Y
       (n_89));
  NOR2XL g5806(.A (current_speed[1]), .B (n_71), .Y (n_99));
  NAND2XL g5807(.A (n_72), .B (n_73), .Y (n_98));
  NAND3BX1 g5808(.AN (destination_reached_reg), .B (n_56), .C (n_424),
       .Y (n_96));
  XNOR2X1 g5809(.A (n_2), .B (n_59), .Y (n_88));
  AOI21X1 g5810(.A0 (n_22), .A1 (n_35), .B0 (n_61), .Y (n_95));
  NAND2BX1 g5811(.AN (n_87), .B (n_86), .Y (n_94));
  NOR2XL g5812(.A (n_40), .B (n_72), .Y (n_92));
  AND2XL g5816(.A (n_48), .B (n_505), .Y (n_85));
  AND2XL g5817(.A (n_48), .B (n_503), .Y (n_84));
  AND2XL g5818(.A (n_48), .B (n_501), .Y (n_83));
  AND2XL g5819(.A (n_48), .B (n_497), .Y (n_82));
  AND2XL g5820(.A (n_48), .B (n_493), .Y (n_81));
  AND2XL g5821(.A (n_48), .B (n_498), .Y (n_80));
  AND2XL g5822(.A (n_48), .B (n_492), .Y (n_79));
  AND2XL g5823(.A (n_48), .B (n_491), .Y (n_78));
  AND2XL g5824(.A (n_48), .B (n_490), .Y (n_77));
  AND2XL g5825(.A (n_48), .B (n_502), .Y (n_76));
  AND2XL g5826(.A (n_48), .B (n_504), .Y (n_75));
  NOR2XL g5827(.A (n_28), .B (n_42), .Y (n_87));
  NAND2XL g5828(.A (n_28), .B (n_42), .Y (n_86));
  CLKINVX1 g5829(.A (n_71), .Y (n_70));
  NOR3X1 g5830(.A (destination_reached_reg), .B (n_40), .C (n_0), .Y
       (n_69));
  AND2XL g5831(.A (n_48), .B (n_499), .Y (n_68));
  AND2XL g5832(.A (n_48), .B (n_496), .Y (n_67));
  AND2XL g5833(.A (n_48), .B (n_494), .Y (n_66));
  AND2XL g5834(.A (n_48), .B (n_500), .Y (n_65));
  AND2XL g5835(.A (n_48), .B (n_495), .Y (n_64));
  AOI21X1 g5836(.A0 (current_speed[4]), .A1 (n_41), .B0 (n_58), .Y
       (n_63));
  NOR3BX1 g5837(.AN (n_1), .B (next_state[5]), .C (next_state[7]), .Y
       (n_62));
  NOR2XL g5838(.A (n_22), .B (n_35), .Y (n_61));
  AOI21XL g5840(.A0 (n_44), .A1 (n_412), .B0 (n_53), .Y (n_74));
  NOR2XL g5841(.A (n_424), .B (n_48), .Y (n_73));
  NAND2XL g5842(.A (n_404), .B (n_47), .Y (n_72));
  NAND3BX1 g5843(.AN (\acceleration[0]_1483 ), .B (n_978), .C (n_51),
       .Y (n_71));
  INVXL g5846(.A (n_56), .Y (n_55));
  NAND2XL g5847(.A (front_obstacle_slow_reg), .B (n_39), .Y (n_54));
  NOR2XL g5848(.A (n_44), .B (n_412), .Y (n_53));
  OAI2BB1XL g5849(.A0N (current_speed[2]), .A1N (current_speed[3]), .B0
       (n_41), .Y (n_52));
  NAND2XL g5850(.A (lane_clear_right_reg), .B (n_33), .Y (n_60));
  OAI2BB1X1 g5851(.A0N (current_speed[0]), .A1N
       (integral_error_accumulator[8]), .B0 (n_38), .Y (n_59));
  NOR2XL g5852(.A (current_speed[4]), .B (n_41), .Y (n_58));
  NAND2XL g5853(.A (lane_clear_left_reg), .B (n_31), .Y (n_57));
  NOR2XL g5854(.A (front_obstacle_slow_reg), .B (n_40), .Y (n_56));
  INVXL g5856(.A (n_0), .Y (n_49));
  NOR4XL g5857(.A (current_state[6]), .B (n_9), .C (n_407), .D (n_544),
       .Y (n_47));
  AOI222XL g5858(.A0 (n_525), .A1 (n_528), .B0 (n_559), .B1
       (current_state[3]), .C0 (n_17), .C1 (current_state[7]), .Y
       (n_46));
  NAND4XL g5860(.A (n_7), .B (n_29), .C (n_11), .D (n_32), .Y (n_51));
  NAND3BX1 g5861(.AN (n_525), .B (n_528), .C (n_43), .Y (n_50));
  OAI2BB1X1 g5863(.A0N (n_27), .A1N (n_412), .B0 (n_23), .Y (n_45));
  AND4X1 g5864(.A (current_state[2]), .B (n_10), .C (n_405), .D (n_21),
       .Y (n_48));
  INVX1 g5865(.A (n_40), .Y (n_39));
  OAI21XL g5866(.A0 (integral_error_accumulator[8]), .A1
       (current_speed[0]), .B0 (n_969), .Y (n_38));
  AND2X1 g5867(.A (n_23), .B (n_27), .Y (n_44));
  NOR3BX1 g5868(.AN (n_405), .B (current_state[7]), .C (n_544), .Y
       (n_43));
  OAI21X1 g5869(.A0 (current_speed[5]), .A1
       (integral_error_accumulator[13]), .B0 (n_20), .Y (n_42));
  OAI21X1 g5870(.A0 (current_speed[6]), .A1
       (integral_error_accumulator[14]), .B0 (n_22), .Y (n_37));
  NAND2XL g5871(.A (n_6), .B (n_29), .Y (n_41));
  AND3X1 g5872(.A (front_obstacle_history[2]), .B
       (front_obstacle_history[0]), .C (front_obstacle_history[1]), .Y
       (n_40));
  NOR4XL g5873(.A (current_state[2]), .B (current_state[4]), .C
       (current_state[6]), .D (current_state[0]), .Y (n_34));
  NAND3X1 g5874(.A (right_obstacle_history[2]), .B
       (right_obstacle_history[0]), .C (right_obstacle_history[1]), .Y
       (n_33));
  NOR3X1 g5875(.A (current_speed[0]), .B (current_speed[4]), .C
       (current_speed[7]), .Y (n_32));
  NAND3X1 g5876(.A (left_obstacle_history[2]), .B
       (left_obstacle_history[0]), .C (left_obstacle_history[1]), .Y
       (n_31));
  XNOR2X1 g5877(.A (integral_error_accumulator[8]), .B (n_969), .Y
       (n_36));
  MXI2XL g5878(.A (current_speed[7]), .B (n_8), .S0
       (integral_error_accumulator[15]), .Y (n_35));
  MXI2XL g5880(.A (n_12), .B (current_speed[4]), .S0
       (integral_error_accumulator[12]), .Y (n_30));
  CLKINVX1 g5919(.A (n_19), .Y (n_18));
  NOR2XL g5945(.A (current_speed[2]), .B (current_speed[3]), .Y (n_29));
  NAND2XL g5946(.A (current_speed[4]), .B
       (integral_error_accumulator[12]), .Y (n_28));
  NAND2BX1 g5947(.AN (integral_error_accumulator[10]), .B (n_13), .Y
       (n_27));
  NAND2XL g5948(.A (integral_error_accumulator[9]), .B (n_411), .Y
       (n_26));
  NOR2XL g5949(.A (n_423), .B (n_422), .Y (n_25));
  NOR2XL g5950(.A (current_state[3]), .B (n_559), .Y (n_24));
  NAND2XL g5951(.A (current_speed[2]), .B
       (integral_error_accumulator[10]), .Y (n_23));
  NAND2XL g5953(.A (current_speed[6]), .B
       (integral_error_accumulator[14]), .Y (n_22));
  AND2X1 g5955(.A (n_551), .B (n_404), .Y (n_21));
  NAND2XL g5956(.A (current_speed[5]), .B
       (integral_error_accumulator[13]), .Y (n_20));
  NAND2XL g5957(.A (n_978), .B (\acceleration[0]_1483 ), .Y (n_19));
  INVXL g5966(.A (n_406), .Y (n_17));
  DFFRX2 \current_speed_reg[1] (.RN (n_14), .CK (clk), .D (n_572), .Q
       (current_speed[1]), .QN (n_6));
  DFFRX4 \current_speed_reg[2] (.RN (n_14), .CK (clk), .D (n_140), .Q
       (current_speed[2]), .QN (n_13));
  DFFRX4 \current_speed_reg[3] (.RN (n_14), .CK (clk), .D (n_144), .Q
       (current_speed[3]), .QN (UNCONNECTED0));
  DFFRX2 \current_speed_reg[4] (.RN (n_14), .CK (clk), .D (n_150), .Q
       (current_speed[4]), .QN (n_12));
  DFFRX2 \current_speed_reg[5] (.RN (n_14), .CK (clk), .D (n_152), .Q
       (current_speed[5]), .QN (n_7));
  DFFRX2 \current_speed_reg[6] (.RN (n_14), .CK (clk), .D (n_157), .Q
       (current_speed[6]), .QN (n_11));
  DFFRX1 \current_speed_reg[7] (.RN (n_14), .CK (clk), .D (n_158), .Q
       (current_speed[7]), .QN (n_8));
  DFFSX2 \current_state_reg[0] (.SN (n_14), .CK (clk), .D (n_133), .Q
       (current_state[0]), .QN (n_10));
  DFFRX2 \current_state_reg[3] (.RN (n_14), .CK (clk), .D (n_136), .Q
       (current_state[3]), .QN (n_9));
  NAND2BX1 g10063(.AN (n_26), .B (n_74), .Y (n_5));
  NOR3BXL g5990(.AN (n_57), .B (n_60), .C (n_93), .Y (n_4));
  NAND3BX1 g5991(.AN (n_51), .B (n_6), .C (n_39), .Y (n_3));
  CLKXOR2X1 g5992(.A (n_411), .B (integral_error_accumulator[9]), .Y
       (n_2));
  NAND3BXL g5993(.AN (n_528), .B (n_525), .C (n_43), .Y (n_1));
  NAND4BXL g5994(.AN (current_state[2]), .B (current_state[0]), .C
       (n_405), .D (n_21), .Y (n_0));
  AOI21X1 g10064(.A0 (n_208), .A1 (n_213), .B0 (n_198), .Y (n_517));
  AOI21X1 g10065(.A0 (n_202), .A1 (n_203), .B0 (n_201), .Y (n_518));
  AOI22X1 g10066(.A0 (n_56), .A1 (n_48), .B0 (n_40), .B1 (n_49), .Y
       (n_519));
  CLKBUFX2 fopt10068(.A (current_state[10]), .Y (n_525));
  CLKINVX1 fopt10071(.A (n_531), .Y (n_528));
  INVXL fopt10074(.A (n_221), .Y (n_534));
  CLKINVX2 fopt10075(.A (n_221), .Y (n_536));
  CLKINVX1 fopt10083(.A (n_548), .Y (n_544));
  INVX3 fopt10084(.A (n_425), .Y (n_548));
  INVXL fopt10087(.A (current_state[1]), .Y (n_551));
  CLKINVX1 fopt10240(.A (n_560), .Y (n_559));
  CLKINVX2 fopt10242(.A (n_278), .Y (n_561));
  DFFRHQX4 \steering_reg[1] (.RN (n_14), .CK (clk), .D (n_422), .Q
       (n_391));
  DFFRHQX4 \steering_reg[0] (.RN (n_14), .CK (clk), .D (n_423), .Q
       (n_390));
  DFFRHQX4 \indicators_reg[1] (.RN (n_14), .CK (clk), .D (n_217), .Q
       (n_389));
  DFFRHQX4 \indicators_reg[0] (.RN (n_14), .CK (clk), .D (n_161), .Q
       (n_388));
  DFFRHQX4 \current_speed_out_reg[7] (.RN (n_14), .CK (clk), .D
       (current_speed[7]), .Q (n_387));
  DFFRHQX4 \current_speed_out_reg[6] (.RN (n_14), .CK (clk), .D
       (current_speed[6]), .Q (n_386));
  DFFRHQX4 \current_speed_out_reg[5] (.RN (n_14), .CK (clk), .D
       (current_speed[5]), .Q (n_385));
  DFFRHQX4 \current_speed_out_reg[4] (.RN (n_14), .CK (clk), .D
       (current_speed[4]), .Q (n_384));
  DFFRHQX4 \current_speed_out_reg[3] (.RN (n_14), .CK (clk), .D
       (current_speed[3]), .Q (n_383));
  DFFRHQX4 \current_speed_out_reg[2] (.RN (n_14), .CK (clk), .D
       (current_speed[2]), .Q (n_382));
  DFFRHQX4 \current_speed_out_reg[1] (.RN (n_14), .CK (clk), .D
       (current_speed[1]), .Q (n_381));
  AOI222XL g10274(.A0 (current_speed[2]), .A1 (n_108), .B0 (n_13), .B1
       (n_99), .C0 (n_130), .C1 (n_980), .Y (n_569));
  AOI222XL g10275(.A0 (n_52), .A1 (n_70), .B0 (current_speed[3]), .B1
       (n_108), .C0 (n_142), .C1 (n_980), .Y (n_571));
  OAI2BB1XL g10276(.A0N (n_980), .A1N (n_114), .B0 (n_105), .Y (n_572));
  DFFRHQX4 \total_power_consumed_out_reg[16] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[16]), .Q (n_332));
  DFFRHQX4 \distance_travelled_out_reg[4] (.RN (n_14), .CK (clk), .D
       (distance_travelled[4]), .Q (n_352));
  DFFRHQX4 \distance_travelled_out_reg[17] (.RN (n_14), .CK (clk), .D
       (distance_travelled[17]), .Q (n_365));
  DFFRHQX4 \total_power_consumed_out_reg[14] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[14]), .Q (n_330));
  DFFRHQX4 \distance_travelled_out_reg[18] (.RN (n_14), .CK (clk), .D
       (distance_travelled[18]), .Q (n_366));
  DFFRHQX4 \total_power_consumed_out_reg[30] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[30]), .Q (n_346));
  DFFRHQX4 \distance_travelled_out_reg[11] (.RN (n_14), .CK (clk), .D
       (distance_travelled[11]), .Q (n_359));
  DFFRHQX4 \distance_travelled_out_reg[24] (.RN (n_14), .CK (clk), .D
       (distance_travelled[24]), .Q (n_372));
  DFFRHQX4 \total_power_consumed_out_reg[28] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[28]), .Q (n_344));
  DFFRHQX4 \distance_travelled_out_reg[10] (.RN (n_14), .CK (clk), .D
       (distance_travelled[10]), .Q (n_358));
  DFFRHQX4 \total_power_consumed_out_reg[27] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[27]), .Q (n_343));
  DFFRHQX4 \total_power_consumed_out_reg[20] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[20]), .Q (n_336));
  DFFRHQX4 \distance_travelled_out_reg[15] (.RN (n_14), .CK (clk), .D
       (distance_travelled[15]), .Q (n_363));
  DFFRHQX4 \distance_travelled_out_reg[9] (.RN (n_14), .CK (clk), .D
       (distance_travelled[9]), .Q (n_357));
  DFFRHQX4 \total_power_consumed_out_reg[1] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[1]), .Q (n_317));
  DFFRHQX4 \total_power_consumed_out_reg[19] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[19]), .Q (n_335));
  DFFRHQX4 \total_power_consumed_out_reg[3] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[3]), .Q (n_319));
  DFFRHQX4 \total_power_consumed_out_reg[31] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[31]), .Q (n_347));
  DFFRHQX4 \total_power_consumed_out_reg[23] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[23]), .Q (n_339));
  DFFRHQX4 \total_power_consumed_out_reg[15] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[15]), .Q (n_331));
  DFFRHQX4 \total_power_consumed_out_reg[25] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[25]), .Q (n_341));
  DFFRHQX4 \total_power_consumed_out_reg[21] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[21]), .Q (n_337));
  DFFRHQX4 \total_power_consumed_out_reg[13] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[13]), .Q (n_329));
  DFFRHQX4 \distance_travelled_out_reg[29] (.RN (n_14), .CK (clk), .D
       (distance_travelled[29]), .Q (n_377));
  DFFRHQX4 \current_speed_out_reg[0] (.RN (n_14), .CK (clk), .D
       (current_speed[0]), .Q (n_380));
  DFFRHQX4 \total_power_consumed_out_reg[22] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[22]), .Q (n_338));
  DFFRHQX4 \total_power_consumed_out_reg[9] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[9]), .Q (n_325));
  DFFRHQX4 \total_power_consumed_out_reg[17] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[17]), .Q (n_333));
  DFFRHQX4 \total_power_consumed_out_reg[11] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[11]), .Q (n_327));
  DFFRHQX4 \distance_travelled_out_reg[5] (.RN (n_14), .CK (clk), .D
       (distance_travelled[5]), .Q (n_353));
  DFFRHQX4 \total_power_consumed_out_reg[5] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[5]), .Q (n_321));
  DFFRHQX4 \total_power_consumed_out_reg[12] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[12]), .Q (n_328));
  DFFRHQX4 \total_power_consumed_out_reg[18] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[18]), .Q (n_334));
  DFFRHQX4 \distance_travelled_out_reg[7] (.RN (n_14), .CK (clk), .D
       (distance_travelled[7]), .Q (n_355));
  DFFRHQX4 \distance_travelled_out_reg[20] (.RN (n_14), .CK (clk), .D
       (distance_travelled[20]), .Q (n_368));
  DFFRHQX4 \distance_travelled_out_reg[1] (.RN (n_14), .CK (clk), .D
       (distance_travelled[1]), .Q (n_349));
  DFFRHQX4 \distance_travelled_out_reg[23] (.RN (n_14), .CK (clk), .D
       (distance_travelled[23]), .Q (n_371));
  DFFRHQX4 \distance_travelled_out_reg[6] (.RN (n_14), .CK (clk), .D
       (distance_travelled[6]), .Q (n_354));
  DFFRHQX4 \total_power_consumed_out_reg[26] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[26]), .Q (n_342));
  DFFRHQX4 \total_power_consumed_out_reg[2] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[2]), .Q (n_318));
  DFFRHQX4 \total_power_consumed_out_reg[10] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[10]), .Q (n_326));
  DFFRHQX4 \distance_travelled_out_reg[25] (.RN (n_14), .CK (clk), .D
       (distance_travelled[25]), .Q (n_373));
  DFFRHQX4 \total_power_consumed_out_reg[24] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[24]), .Q (n_340));
  DFFRHQX4 \total_power_consumed_out_reg[4] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[4]), .Q (n_320));
  DFFRHQX4 \distance_travelled_out_reg[3] (.RN (n_14), .CK (clk), .D
       (distance_travelled[3]), .Q (n_351));
  DFFRHQX4 \distance_travelled_out_reg[28] (.RN (n_14), .CK (clk), .D
       (distance_travelled[28]), .Q (n_376));
  DFFRHQX4 \distance_travelled_out_reg[22] (.RN (n_14), .CK (clk), .D
       (distance_travelled[22]), .Q (n_370));
  DFFRHQX4 \distance_travelled_out_reg[2] (.RN (n_14), .CK (clk), .D
       (distance_travelled[2]), .Q (n_350));
  DFFRHQX4 \total_power_consumed_out_reg[6] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[6]), .Q (n_322));
  DFFRHQX4 \distance_travelled_out_reg[8] (.RN (n_14), .CK (clk), .D
       (distance_travelled[8]), .Q (n_356));
  DFFRHQX4 \distance_travelled_out_reg[19] (.RN (n_14), .CK (clk), .D
       (distance_travelled[19]), .Q (n_367));
  DFFRHQX4 \distance_travelled_out_reg[30] (.RN (n_14), .CK (clk), .D
       (distance_travelled[30]), .Q (n_378));
  DFFRHQX4 \total_power_consumed_out_reg[8] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[8]), .Q (n_324));
  DFFRHQX4 \distance_travelled_out_reg[16] (.RN (n_14), .CK (clk), .D
       (distance_travelled[16]), .Q (n_364));
  DFFRHQX4 \distance_travelled_out_reg[27] (.RN (n_14), .CK (clk), .D
       (distance_travelled[27]), .Q (n_375));
  DFFRHQX4 \distance_travelled_out_reg[21] (.RN (n_14), .CK (clk), .D
       (distance_travelled[21]), .Q (n_369));
  DFFRHQX4 \distance_travelled_out_reg[31] (.RN (n_14), .CK (clk), .D
       (distance_travelled[31]), .Q (n_379));
  DFFRHQX4 \distance_travelled_out_reg[12] (.RN (n_14), .CK (clk), .D
       (distance_travelled[12]), .Q (n_360));
  DFFRHQX4 \distance_travelled_out_reg[26] (.RN (n_14), .CK (clk), .D
       (distance_travelled[26]), .Q (n_374));
  DFFRHQX4 \distance_travelled_out_reg[0] (.RN (n_14), .CK (clk), .D
       (distance_travelled[0]), .Q (n_348));
  DFFRHQX4 \total_power_consumed_out_reg[7] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[7]), .Q (n_323));
  DFFRHQX4 \total_power_consumed_out_reg[29] (.RN (n_14), .CK (clk), .D
       (total_power_consumed[29]), .Q (n_345));
  DFFRHQX4 \distance_travelled_out_reg[14] (.RN (n_14), .CK (clk), .D
       (distance_travelled[14]), .Q (n_362));
  DFFRHQX4 \distance_travelled_out_reg[13] (.RN (n_14), .CK (clk), .D
       (distance_travelled[13]), .Q (n_361));
  DFFRX2 \current_state_reg[8] (.RN (n_14), .CK (clk), .D (n_135), .Q
       (current_state[8]), .QN (n_531));
  DFFRX1 \current_state_reg[5] (.RN (n_14), .CK (clk), .D
       (next_state[5]), .Q (current_state[5]), .QN (n_560));
  OR2X1 g10715(.A (current_speed[4]), .B (n_234), .Y (n_957));
  NAND2BX1 g10716(.AN (n_551), .B (n_127), .Y (n_958));
  NAND3BX1 g10717(.AN (n_534), .B (current_speed[4]), .C (n_234), .Y
       (n_959));
  CLKBUFX2 fopt10719(.A (n_410), .Y (n_969));
  BUFX3 fopt10720(.A (n_163), .Y (n_972));
  INVX1 fopt10728(.A (n_980), .Y (n_978));
  CLKINVX1 fopt10729(.A (n_987), .Y (n_980));
  CLKINVX20 fopt10730(.A (n_987), .Y (acceleration[1]));
  CLKINVX6 fopt10731(.A (n_392), .Y (n_987));
  NAND2BX1 g10889(.AN (n_534), .B (current_speed[6]), .Y (n_1224));
  NAND2BX1 g10890(.AN (n_425), .B (n_404), .Y (n_1225));
  DFFRHQX1 \current_speed_reg[0] (.RN (n_14), .CK (clk), .D (n_119), .Q
       (current_speed[0]));
endmodule

