###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID edatools-server2.iiitd.edu.in)
#  Generated on:      Sun Nov  9 04:52:34 2025
#  Design:            collision_avoidance_car
#  Command:           create_ccopt_clock_tree_spec -file ccopt_new.spec -keep_all_sdc_clocks -views view1
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 15.500ns) in timing_config sdc1([../IN/sdc/cac_constraints_medium_c_scan.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group

# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 15.5

# Skew group to balance non generated clock:clk in timing_config:sdc1 (sdc ../IN/sdc/cac_constraints_medium_c_scan.sdc)
create_ccopt_skew_group -name clk/sdc1 -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/sdc1 true
set_ccopt_property extracted_from_clock_name -skew_group clk/sdc1 clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/sdc1 sdc1
set_ccopt_property extracted_from_delay_corners -skew_group clk/sdc1 delay1


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

