
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 11 2025 17:25:58 IST (Oct 11 2025 11:55:58 UTC)

// Verification Directory fv/collision_avoidance_car 

module add_unsigned_4(A, B, Z);
  input [31:0] A;
  input [7:0] B;
  output [31:0] Z;
  wire [31:0] A;
  wire [7:0] B;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_15, n_17, n_19;
  wire n_21, n_23, n_26, n_27, n_29, n_31, n_33, n_35;
  wire n_37, n_39, n_41, n_43, n_45, n_47, n_49, n_51;
  wire n_53, n_55, n_57, n_59, n_61, n_63, n_65, n_67;
  wire n_69, n_71, n_73;
  OAI21X1 g443(.A0 (A[31]), .A1 (n_71), .B0 (n_73), .Y (Z[31]));
  NAND2XL g444(.A (A[31]), .B (n_71), .Y (n_73));
  OA21X1 g445(.A0 (A[30]), .A1 (n_69), .B0 (n_71), .Y (Z[30]));
  NAND2XL g446(.A (A[30]), .B (n_69), .Y (n_71));
  AOI21XL g447(.A0 (n_6), .A1 (n_67), .B0 (n_69), .Y (Z[29]));
  NOR2XL g448(.A (n_6), .B (n_67), .Y (n_69));
  OA21X1 g449(.A0 (A[28]), .A1 (n_65), .B0 (n_67), .Y (Z[28]));
  NAND2XL g450(.A (A[28]), .B (n_65), .Y (n_67));
  AOI21XL g451(.A0 (n_10), .A1 (n_63), .B0 (n_65), .Y (Z[27]));
  NOR2XL g452(.A (n_10), .B (n_63), .Y (n_65));
  OA21X1 g453(.A0 (A[26]), .A1 (n_61), .B0 (n_63), .Y (Z[26]));
  NAND2XL g454(.A (A[26]), .B (n_61), .Y (n_63));
  AOI21XL g455(.A0 (n_8), .A1 (n_59), .B0 (n_61), .Y (Z[25]));
  NOR2XL g456(.A (n_8), .B (n_59), .Y (n_61));
  OA21X1 g457(.A0 (A[24]), .A1 (n_57), .B0 (n_59), .Y (Z[24]));
  NAND2XL g458(.A (A[24]), .B (n_57), .Y (n_59));
  AOI21XL g459(.A0 (n_2), .A1 (n_55), .B0 (n_57), .Y (Z[23]));
  NOR2XL g460(.A (n_2), .B (n_55), .Y (n_57));
  OA21X1 g461(.A0 (A[22]), .A1 (n_53), .B0 (n_55), .Y (Z[22]));
  NAND2XL g462(.A (A[22]), .B (n_53), .Y (n_55));
  AOI21XL g463(.A0 (n_9), .A1 (n_51), .B0 (n_53), .Y (Z[21]));
  NOR2XL g464(.A (n_9), .B (n_51), .Y (n_53));
  OA21X1 g465(.A0 (A[20]), .A1 (n_49), .B0 (n_51), .Y (Z[20]));
  NAND2XL g466(.A (A[20]), .B (n_49), .Y (n_51));
  AOI21XL g467(.A0 (n_7), .A1 (n_47), .B0 (n_49), .Y (Z[19]));
  NOR2XL g468(.A (n_7), .B (n_47), .Y (n_49));
  OA21X1 g469(.A0 (A[18]), .A1 (n_45), .B0 (n_47), .Y (Z[18]));
  NAND2XL g470(.A (A[18]), .B (n_45), .Y (n_47));
  AOI21XL g471(.A0 (n_0), .A1 (n_43), .B0 (n_45), .Y (Z[17]));
  NOR2XL g472(.A (n_0), .B (n_43), .Y (n_45));
  OA21X1 g473(.A0 (A[16]), .A1 (n_41), .B0 (n_43), .Y (Z[16]));
  NAND2XL g474(.A (A[16]), .B (n_41), .Y (n_43));
  AOI21XL g475(.A0 (n_3), .A1 (n_39), .B0 (n_41), .Y (Z[15]));
  NOR2XL g476(.A (n_3), .B (n_39), .Y (n_41));
  OA21X1 g477(.A0 (A[14]), .A1 (n_37), .B0 (n_39), .Y (Z[14]));
  NAND2XL g478(.A (A[14]), .B (n_37), .Y (n_39));
  AOI21XL g479(.A0 (n_5), .A1 (n_35), .B0 (n_37), .Y (Z[13]));
  NOR2XL g480(.A (n_5), .B (n_35), .Y (n_37));
  OA21X1 g481(.A0 (A[12]), .A1 (n_33), .B0 (n_35), .Y (Z[12]));
  NAND2XL g482(.A (A[12]), .B (n_33), .Y (n_35));
  AOI21XL g483(.A0 (n_4), .A1 (n_31), .B0 (n_33), .Y (Z[11]));
  NOR2XL g484(.A (n_4), .B (n_31), .Y (n_33));
  OA21XL g485(.A0 (A[10]), .A1 (n_29), .B0 (n_31), .Y (Z[10]));
  NAND2XL g486(.A (A[10]), .B (n_29), .Y (n_31));
  AOI21X1 g487(.A0 (n_1), .A1 (n_27), .B0 (n_29), .Y (Z[9]));
  NOR2XL g488(.A (n_1), .B (n_27), .Y (n_29));
  OA21XL g489(.A0 (A[8]), .A1 (n_26), .B0 (n_27), .Y (Z[8]));
  NAND2XL g490(.A (A[8]), .B (n_26), .Y (n_27));
  ADDFX1 g491(.A (B[7]), .B (A[7]), .CI (n_23), .CO (n_26), .S (Z[7]));
  ADDFX1 g492(.A (B[6]), .B (A[6]), .CI (n_21), .CO (n_23), .S (Z[6]));
  ADDFX1 g493(.A (B[5]), .B (A[5]), .CI (n_19), .CO (n_21), .S (Z[5]));
  ADDFX1 g494(.A (B[4]), .B (A[4]), .CI (n_17), .CO (n_19), .S (Z[4]));
  ADDFX1 g495(.A (B[3]), .B (A[3]), .CI (n_15), .CO (n_17), .S (Z[3]));
  ADDFX1 g496(.A (B[2]), .B (A[2]), .CI (n_13), .CO (n_15), .S (Z[2]));
  ADDFX1 g497(.A (B[1]), .B (A[1]), .CI (n_11), .CO (n_13), .S (Z[1]));
  AOI2BB1X1 g498(.A0N (A[0]), .A1N (B[0]), .B0 (n_11), .Y (Z[0]));
  AND2X1 g499(.A (A[0]), .B (B[0]), .Y (n_11));
  CLKINVX1 g500(.A (A[27]), .Y (n_10));
  CLKINVX1 g501(.A (A[21]), .Y (n_9));
  CLKINVX1 g502(.A (A[25]), .Y (n_8));
  CLKINVX1 g503(.A (A[19]), .Y (n_7));
  CLKINVX1 g504(.A (A[29]), .Y (n_6));
  CLKINVX1 g505(.A (A[13]), .Y (n_5));
  CLKINVX1 g506(.A (A[11]), .Y (n_4));
  CLKINVX1 g507(.A (A[15]), .Y (n_3));
  CLKINVX1 g508(.A (A[23]), .Y (n_2));
  CLKINVX1 g509(.A (A[9]), .Y (n_1));
  CLKINVX1 g510(.A (A[17]), .Y (n_0));
endmodule

module add_signed(A, B, Z);
  input [15:0] A;
  input [8:0] B;
  output [15:0] Z;
  wire [15:0] A;
  wire [8:0] B;
  wire [15:0] Z;
  wire n_0, n_1, n_3, n_5, n_7, n_9, n_11, n_13;
  wire n_15, n_17, n_19, n_21, n_23, n_25, n_27, n_30;
  wire n_31;
  OAI21XL g370(.A0 (n_30), .A1 (n_0), .B0 (n_31), .Y (Z[15]));
  NAND2XL g371(.A (n_0), .B (n_30), .Y (n_31));
  ADDFXL g372(.A (A[14]), .B (B[8]), .CI (n_27), .CO (n_30), .S
       (Z[14]));
  ADDFX1 g373(.A (B[8]), .B (A[13]), .CI (n_25), .CO (n_27), .S
       (Z[13]));
  ADDFX1 g374(.A (B[8]), .B (A[12]), .CI (n_23), .CO (n_25), .S
       (Z[12]));
  ADDFX1 g375(.A (B[8]), .B (A[11]), .CI (n_21), .CO (n_23), .S
       (Z[11]));
  ADDFX1 g376(.A (B[8]), .B (A[10]), .CI (n_19), .CO (n_21), .S
       (Z[10]));
  ADDFX1 g377(.A (B[8]), .B (A[9]), .CI (n_17), .CO (n_19), .S (Z[9]));
  ADDFX1 g378(.A (B[8]), .B (A[8]), .CI (n_15), .CO (n_17), .S (Z[8]));
  ADDFX1 g379(.A (B[7]), .B (A[7]), .CI (n_13), .CO (n_15), .S (Z[7]));
  ADDFX1 g380(.A (B[6]), .B (A[6]), .CI (n_11), .CO (n_13), .S (Z[6]));
  ADDFX1 g381(.A (B[5]), .B (A[5]), .CI (n_9), .CO (n_11), .S (Z[5]));
  ADDFX1 g382(.A (B[4]), .B (A[4]), .CI (n_7), .CO (n_9), .S (Z[4]));
  ADDFX1 g383(.A (B[3]), .B (A[3]), .CI (n_5), .CO (n_7), .S (Z[3]));
  ADDFX1 g384(.A (B[2]), .B (A[2]), .CI (n_3), .CO (n_5), .S (Z[2]));
  ADDFX1 g385(.A (n_1), .B (A[1]), .CI (B[1]), .CO (n_3), .S (Z[1]));
  AOI2BB1X1 g386(.A0N (A[0]), .A1N (B[0]), .B0 (n_1), .Y (Z[0]));
  AND2X1 g388(.A (A[0]), .B (B[0]), .Y (n_1));
  XNOR2XL g2(.A (B[8]), .B (A[15]), .Y (n_0));
endmodule

module csa_tree_add_153_58_group_2(in_0, in_1, in_2, out_0);
  input [7:0] in_0, in_1;
  input [31:0] in_2;
  output [31:0] out_0;
  wire [7:0] in_0, in_1;
  wire [31:0] in_2;
  wire [31:0] out_0;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_159, n_160, n_162, n_163, n_164, n_165, n_167, n_168;
  wire n_170, n_171, n_173, n_174, n_176, n_177, n_180, n_181;
  wire n_183, n_186, n_187, n_189, n_191, n_193, n_195, n_197;
  wire n_199, n_201, n_203, n_205, n_207, n_209, n_211, n_213;
  wire n_215, n_217, n_264;
  OAI21XL g1526(.A0 (n_215), .A1 (in_2[31]), .B0 (n_217), .Y
       (out_0[31]));
  NAND2XL g1527(.A (in_2[31]), .B (n_215), .Y (n_217));
  OA21X1 g1528(.A0 (in_2[30]), .A1 (n_213), .B0 (n_215), .Y
       (out_0[30]));
  NAND2XL g1529(.A (in_2[30]), .B (n_213), .Y (n_215));
  AOI21XL g1530(.A0 (n_8), .A1 (n_211), .B0 (n_213), .Y (out_0[29]));
  NOR2XL g1531(.A (n_8), .B (n_211), .Y (n_213));
  OA21X1 g1532(.A0 (in_2[28]), .A1 (n_209), .B0 (n_211), .Y
       (out_0[28]));
  NAND2XL g1533(.A (in_2[28]), .B (n_209), .Y (n_211));
  AOI21XL g1534(.A0 (n_5), .A1 (n_207), .B0 (n_209), .Y (out_0[27]));
  NOR2XL g1535(.A (n_5), .B (n_207), .Y (n_209));
  OA21X1 g1536(.A0 (in_2[26]), .A1 (n_205), .B0 (n_207), .Y
       (out_0[26]));
  NAND2XL g1537(.A (in_2[26]), .B (n_205), .Y (n_207));
  AOI21XL g1538(.A0 (n_6), .A1 (n_203), .B0 (n_205), .Y (out_0[25]));
  NOR2XL g1539(.A (n_6), .B (n_203), .Y (n_205));
  OA21X1 g1540(.A0 (in_2[24]), .A1 (n_201), .B0 (n_203), .Y
       (out_0[24]));
  NAND2XL g1541(.A (in_2[24]), .B (n_201), .Y (n_203));
  AOI21XL g1542(.A0 (n_10), .A1 (n_199), .B0 (n_201), .Y (out_0[23]));
  NOR2XL g1543(.A (n_10), .B (n_199), .Y (n_201));
  OA21X1 g1544(.A0 (in_2[22]), .A1 (n_197), .B0 (n_199), .Y
       (out_0[22]));
  NAND2XL g1545(.A (in_2[22]), .B (n_197), .Y (n_199));
  AOI21XL g1546(.A0 (n_11), .A1 (n_195), .B0 (n_197), .Y (out_0[21]));
  NOR2XL g1547(.A (n_11), .B (n_195), .Y (n_197));
  OA21X1 g1548(.A0 (in_2[20]), .A1 (n_193), .B0 (n_195), .Y
       (out_0[20]));
  NAND2XL g1549(.A (in_2[20]), .B (n_193), .Y (n_195));
  AOI21XL g1550(.A0 (n_9), .A1 (n_191), .B0 (n_193), .Y (out_0[19]));
  NOR2XL g1551(.A (n_9), .B (n_191), .Y (n_193));
  OA21XL g1552(.A0 (in_2[18]), .A1 (n_189), .B0 (n_191), .Y
       (out_0[18]));
  NAND2XL g1553(.A (in_2[18]), .B (n_189), .Y (n_191));
  AOI21X1 g1554(.A0 (n_7), .A1 (n_187), .B0 (n_189), .Y (out_0[17]));
  NOR2XL g1555(.A (n_7), .B (n_187), .Y (n_189));
  OA21XL g1556(.A0 (in_2[16]), .A1 (n_186), .B0 (n_187), .Y
       (out_0[16]));
  NAND2XL g1557(.A (in_2[16]), .B (n_186), .Y (n_187));
  ADDFX1 g1558(.A (n_103), .B (in_2[15]), .CI (n_183), .CO (n_186), .S
       (out_0[15]));
  ADDFX1 g1559(.A (n_132), .B (n_104), .CI (n_181), .CO (n_183), .S
       (out_0[14]));
  ADDFX1 g1560(.A (n_145), .B (n_133), .CI (n_180), .CO (n_181), .S
       (out_0[13]));
  OAI22X1 g1562(.A0 (n_155), .A1 (n_177), .B0 (n_147), .B1 (n_154), .Y
       (n_180));
  INVXL g1565(.A (n_176), .Y (out_0[11]));
  ADDFX1 g1566(.A (n_153), .B (n_162), .CI (n_173), .CO (n_177), .S
       (n_176));
  INVXL g1567(.A (n_174), .Y (out_0[10]));
  ADDFX1 g1568(.A (n_163), .B (n_159), .CI (n_170), .CO (n_173), .S
       (n_174));
  INVXL g1569(.A (n_171), .Y (out_0[9]));
  ADDFX1 g1570(.A (n_160), .B (n_151), .CI (n_167), .CO (n_170), .S
       (n_171));
  INVXL g1571(.A (n_168), .Y (out_0[8]));
  ADDFX1 g1572(.A (n_152), .B (n_137), .CI (n_164), .CO (n_167), .S
       (n_168));
  INVXL g1573(.A (n_165), .Y (out_0[7]));
  ADDFX1 g1574(.A (n_138), .B (n_128), .CI (n_156), .CO (n_164), .S
       (n_165));
  ADDFXL g1575(.A (n_118), .B (n_140), .CI (n_143), .CO (n_162), .S
       (n_163));
  ADDFXL g1577(.A (n_78), .B (n_141), .CI (n_144), .CO (n_159), .S
       (n_160));
  INVXL g1578(.A (n_157), .Y (out_0[6]));
  ADDFX1 g1579(.A (n_129), .B (n_107), .CI (n_148), .CO (n_156), .S
       (n_157));
  AND2X1 g1580(.A (n_147), .B (n_154), .Y (n_155));
  ADDFXL g1581(.A (n_117), .B (n_139), .CI (n_126), .CO (n_154), .S
       (n_153));
  ADDFXL g1582(.A (n_76), .B (n_130), .CI (n_142), .CO (n_151), .S
       (n_152));
  INVXL g1583(.A (n_149), .Y (out_0[5]));
  ADDFX1 g1584(.A (n_108), .B (n_105), .CI (n_134), .CO (n_148), .S
       (n_149));
  INVX1 g1585(.A (n_146), .Y (n_147));
  ADDFXL g1586(.A (n_111), .B (n_110), .CI (n_127), .CO (n_145), .S
       (n_146));
  ADDFXL g1587(.A (n_75), .B (n_119), .CI (n_116), .CO (n_143), .S
       (n_144));
  ADDFXL g1588(.A (n_79), .B (n_101), .CI (n_120), .CO (n_141), .S
       (n_142));
  ADDFXL g1589(.A (n_12), .B (n_77), .CI (n_115), .CO (n_139), .S
       (n_140));
  ADDFXL g1590(.A (n_73), .B (n_80), .CI (n_131), .CO (n_137), .S
       (n_138));
  INVXL g1591(.A (n_135), .Y (out_0[4]));
  ADDFX1 g1592(.A (n_123), .B (n_81), .CI (n_106), .CO (n_134), .S
       (n_135));
  ADDFXL g1593(.A (n_84), .B (n_97), .CI (n_109), .CO (n_132), .S
       (n_133));
  ADDFXL g1594(.A (n_15), .B (n_95), .CI (n_102), .CO (n_130), .S
       (n_131));
  ADDFXL g1595(.A (n_74), .B (n_99), .CI (n_96), .CO (n_128), .S
       (n_129));
  OAI21X1 g1596(.A0 (n_55), .A1 (n_34), .B0 (n_121), .Y (n_127));
  AOI21X1 g1597(.A0 (n_66), .A1 (n_112), .B0 (n_122), .Y (n_126));
  INVXL g1598(.A (n_124), .Y (out_0[3]));
  ADDFX1 g1599(.A (n_82), .B (n_58), .CI (n_94), .CO (n_123), .S
       (n_124));
  NOR2XL g1600(.A (n_66), .B (n_112), .Y (n_122));
  OAI2BB1XL g1601(.A0N (n_55), .A1N (n_34), .B0 (n_112), .Y (n_121));
  ADDFXL g1602(.A (n_21), .B (n_42), .CI (n_90), .CO (n_119), .S
       (n_120));
  ADDFXL g1603(.A (n_37), .B (n_14), .CI (n_87), .CO (n_117), .S
       (n_118));
  INVX1 g1604(.A (n_114), .Y (n_116));
  INVX1 g1605(.A (n_113), .Y (n_115));
  ADDFXL g1606(.A (n_18), .B (n_2), .CI (n_88), .CO (n_113), .S
       (n_114));
  ADDFXL g1607(.A (n_40), .B (n_1), .CI (n_85), .CO (n_111), .S
       (n_112));
  ADDFXL g1608(.A (n_22), .B (n_39), .CI (n_98), .CO (n_109), .S
       (n_110));
  ADDFXL g1609(.A (n_28), .B (n_38), .CI (n_100), .CO (n_107), .S
       (n_108));
  ADDFXL g1610(.A (n_19), .B (n_30), .CI (n_69), .CO (n_105), .S
       (n_106));
  ADDFXL g1611(.A (in_2[14]), .B (n_44), .CI (n_83), .CO (n_103), .S
       (n_104));
  ADDFXL g1612(.A (n_36), .B (n_63), .CI (n_0), .CO (n_101), .S
       (n_102));
  ADDFXL g1613(.A (n_43), .B (n_57), .CI (n_67), .CO (n_99), .S
       (n_100));
  ADDFXL g1614(.A (in_2[12]), .B (n_35), .CI (n_59), .CO (n_97), .S
       (n_98));
  ADDFX1 g1615(.A (n_62), .B (n_41), .CI (n_68), .CO (n_95), .S (n_96));
  AOI21X1 g1616(.A0 (n_70), .A1 (n_53), .B0 (n_91), .Y (n_94));
  OAI21X1 g1617(.A0 (n_60), .A1 (n_72), .B0 (n_92), .Y (out_0[2]));
  NAND2XL g1618(.A (n_60), .B (n_72), .Y (n_92));
  AOI2BB1X1 g1619(.A0N (n_70), .A1N (n_53), .B0 (n_60), .Y (n_91));
  INVX1 g1620(.A (n_89), .Y (n_90));
  ADDFXL g1621(.A (in_2[8]), .B (n_29), .CI (n_61), .CO (n_88), .S
       (n_89));
  INVX1 g1622(.A (n_86), .Y (n_87));
  ADDFXL g1623(.A (in_2[10]), .B (n_27), .CI (n_65), .CO (n_85), .S
       (n_86));
  ADDFXL g1624(.A (in_2[13]), .B (n_46), .CI (n_17), .CO (n_83), .S
       (n_84));
  ADDFXL g1625(.A (n_4), .B (n_24), .CI (n_52), .CO (n_81), .S (n_82));
  ADDFXL g1626(.A (n_23), .B (n_25), .CI (n_26), .CO (n_79), .S (n_80));
  ADDFX1 g1627(.A (n_20), .B (n_47), .CI (n_16), .CO (n_77), .S (n_78));
  ADDFXL g1628(.A (n_31), .B (n_49), .CI (n_13), .CO (n_75), .S (n_76));
  ADDFXL g1629(.A (n_50), .B (n_48), .CI (n_45), .CO (n_73), .S (n_74));
  MXI2XL g1630(.A (n_54), .B (n_53), .S0 (n_70), .Y (n_72));
  OA21XL g1631(.A0 (in_2[1]), .A1 (n_33), .B0 (n_60), .Y (out_0[1]));
  OAI21X1 g1632(.A0 (in_2[2]), .A1 (n_56), .B0 (n_64), .Y (n_70));
  MXI2XL g1633(.A (n_33), .B (n_32), .S0 (in_2[4]), .Y (n_69));
  MXI2XL g1635(.A (n_51), .B (n_52), .S0 (in_2[6]), .Y (n_68));
  MXI2XL g1638(.A (n_53), .B (n_54), .S0 (in_2[5]), .Y (n_67));
  XNOR2X1 g1639(.A (n_55), .B (n_34), .Y (n_66));
  NOR2BX1 g1640(.AN (in_2[9]), .B (n_50), .Y (n_65));
  NAND2XL g1641(.A (in_2[2]), .B (n_56), .Y (n_64));
  NAND2XL g1642(.A (in_2[6]), .B (n_51), .Y (n_63));
  NAND2XL g1643(.A (in_2[5]), .B (n_53), .Y (n_62));
  NOR2BX1 g1644(.AN (in_2[7]), .B (n_30), .Y (n_61));
  NAND2XL g1645(.A (in_2[1]), .B (n_33), .Y (n_60));
  NOR2BX1 g1646(.AN (in_2[11]), .B (n_31), .Y (n_59));
  NAND2BX1 g1647(.AN (n_56), .B (in_2[2]), .Y (n_58));
  NAND2XL g1648(.A (in_2[4]), .B (n_33), .Y (n_57));
  CLKINVX1 g1649(.A (n_54), .Y (n_53));
  CLKINVX1 g1650(.A (n_52), .Y (n_51));
  NAND2XL g1652(.A (in_0[0]), .B (in_1[2]), .Y (n_56));
  NAND2XL g1653(.A (in_0[2]), .B (in_1[6]), .Y (n_49));
  NAND2XL g1654(.A (in_0[0]), .B (in_1[6]), .Y (n_48));
  NAND2XL g1655(.A (in_0[2]), .B (in_1[7]), .Y (n_47));
  AND2X1 g1656(.A (in_0[6]), .B (in_1[7]), .Y (n_46));
  NAND2XL g1657(.A (in_0[1]), .B (in_1[5]), .Y (n_45));
  AND2X1 g1658(.A (in_0[7]), .B (in_1[7]), .Y (n_44));
  NAND2XL g1659(.A (in_0[3]), .B (in_1[2]), .Y (n_43));
  NAND2XL g1660(.A (in_0[5]), .B (in_1[6]), .Y (n_55));
  NAND2XL g1661(.A (in_0[1]), .B (in_1[7]), .Y (n_42));
  NAND2XL g1662(.A (in_0[4]), .B (in_1[2]), .Y (n_41));
  AND2X1 g1663(.A (in_0[4]), .B (in_1[7]), .Y (n_40));
  AND2X1 g1664(.A (in_0[7]), .B (in_1[5]), .Y (n_39));
  NAND2XL g1665(.A (in_0[0]), .B (in_1[5]), .Y (n_38));
  NAND2XL g1666(.A (in_0[3]), .B (in_1[7]), .Y (n_37));
  NAND2XL g1667(.A (in_0[0]), .B (in_1[7]), .Y (n_36));
  AND2X1 g1668(.A (in_0[5]), .B (in_1[7]), .Y (n_35));
  NAND2XL g1669(.A (in_0[1]), .B (in_1[1]), .Y (n_54));
  NAND2XL g1670(.A (in_0[2]), .B (in_1[1]), .Y (n_52));
  NAND2XL g1671(.A (in_0[5]), .B (in_1[1]), .Y (n_50));
  INVX1 g1672(.A (n_32), .Y (n_33));
  INVX1 g1675(.A (n_28), .Y (n_29));
  INVX1 g1676(.A (n_26), .Y (n_27));
  NAND2XL g1677(.A (in_0[1]), .B (in_1[6]), .Y (n_25));
  NAND2XL g1678(.A (in_0[1]), .B (in_1[2]), .Y (n_24));
  NAND2XL g1679(.A (in_0[5]), .B (in_1[2]), .Y (n_23));
  AND2X1 g1680(.A (in_0[6]), .B (in_1[6]), .Y (n_22));
  NAND2XL g1681(.A (in_0[6]), .B (in_1[2]), .Y (n_21));
  NAND2XL g1682(.A (in_0[3]), .B (in_1[6]), .Y (n_20));
  NAND2XL g1683(.A (in_0[2]), .B (in_1[2]), .Y (n_19));
  AND2X1 g1684(.A (in_0[7]), .B (in_1[2]), .Y (n_18));
  AND2X1 g1685(.A (in_0[7]), .B (in_1[6]), .Y (n_17));
  NAND2XL g1686(.A (in_0[4]), .B (in_1[5]), .Y (n_16));
  NAND2XL g1687(.A (in_0[2]), .B (in_1[5]), .Y (n_15));
  NAND2XL g1688(.A (in_0[4]), .B (in_1[6]), .Y (n_14));
  NAND2XL g1689(.A (in_0[6]), .B (in_1[5]), .Y (n_34));
  NAND2XL g1690(.A (in_0[3]), .B (in_1[5]), .Y (n_13));
  NAND2XL g1691(.A (in_0[5]), .B (in_1[5]), .Y (n_12));
  NAND2XL g1692(.A (in_0[0]), .B (in_1[1]), .Y (n_32));
  NAND2XL g1693(.A (in_0[7]), .B (in_1[1]), .Y (n_31));
  NAND2XL g1694(.A (in_0[3]), .B (in_1[1]), .Y (n_30));
  NAND2XL g1695(.A (in_0[4]), .B (in_1[1]), .Y (n_28));
  NAND2XL g1696(.A (in_0[6]), .B (in_1[1]), .Y (n_26));
  CLKINVX1 g1697(.A (in_2[21]), .Y (n_11));
  CLKINVX1 g1698(.A (in_2[23]), .Y (n_10));
  CLKINVX1 g1699(.A (in_2[19]), .Y (n_9));
  CLKINVX1 g1700(.A (in_2[29]), .Y (n_8));
  CLKINVX1 g1701(.A (in_2[17]), .Y (n_7));
  CLKINVX1 g1702(.A (in_2[25]), .Y (n_6));
  CLKINVX1 g1703(.A (in_2[27]), .Y (n_5));
  INVX1 g1704(.A (in_2[3]), .Y (n_4));
  XNOR2X1 g1705(.A (n_50), .B (in_2[9]), .Y (n_2));
  XNOR2X1 g1706(.A (n_31), .B (in_2[11]), .Y (n_1));
  CLKXOR2X1 g1707(.A (n_30), .B (in_2[7]), .Y (n_0));
  XNOR2XL g1708(.A (n_264), .B (n_177), .Y (out_0[12]));
  MXI2XL g3(.A (n_146), .B (n_147), .S0 (n_154), .Y (n_264));
endmodule

module collision_avoidance_car(clk, rst, front_obstacle_detected,
     left_obstacle_detected, right_obstacle_detected,
     front_obstacle_slow, lane_clear_left, lane_clear_right,
     destination_reached, speed_limit_zone, acceleration, steering,
     indicators, current_speed_out, distance_travelled_out,
     total_power_consumed_out);
  input clk, rst, front_obstacle_detected, left_obstacle_detected,
       right_obstacle_detected, front_obstacle_slow, lane_clear_left,
       lane_clear_right, destination_reached;
  input [1:0] speed_limit_zone;
  output [1:0] acceleration, steering, indicators;
  output [7:0] current_speed_out;
  output [31:0] distance_travelled_out, total_power_consumed_out;
  wire clk, rst, front_obstacle_detected, left_obstacle_detected,
       right_obstacle_detected, front_obstacle_slow, lane_clear_left,
       lane_clear_right, destination_reached;
  wire [1:0] speed_limit_zone;
  wire [1:0] acceleration, steering, indicators;
  wire [7:0] current_speed_out;
  wire [31:0] distance_travelled_out, total_power_consumed_out;
  wire [31:0] distance_travelled;
  wire [7:0] current_speed;
  wire [15:0] integral_error_accumulator;
  wire [31:0] total_power_consumed;
  wire [2:0] front_obstacle_history;
  wire [2:0] left_obstacle_history;
  wire [2:0] right_obstacle_history;
  wire [1:0] speed_limit_zone_reg;
  wire [10:0] next_state;
  wire [10:0] current_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       destination_reached_reg, front_obstacle_slow_reg;
  wire lane_clear_left_reg, lane_clear_right_reg, n_0, n_1, n_2, n_3,
       n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_175, n_176, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_236, n_237, n_238, n_239, n_240, n_241, n_242;
  wire n_243, n_244, n_245, n_246, n_247, n_248, n_249, n_250;
  wire n_251, n_252, n_253, n_254, n_255, n_256, n_257, n_258;
  wire n_259, n_260, n_261, n_262, n_263, n_264, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_295, n_296, n_297, n_298;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_305, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_312, n_313, n_314;
  wire n_315, n_316, n_317, n_318, n_319, n_320, n_321, n_322;
  wire n_323, n_324, n_325, n_326, n_327, n_328, n_329, n_330;
  wire n_331, n_334, n_335, n_336, n_337, n_338, n_339, n_340;
  wire n_341, n_342, n_343, n_344, n_345, n_346, n_347, n_348;
  wire n_349, n_350, n_351, n_352, n_353, n_354, n_355, n_356;
  wire n_358, n_359, n_360, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_368, n_369, n_370, n_371, n_372, n_373;
  wire n_374, n_375, n_376, n_377, n_378, n_379, n_380, n_381;
  wire n_382, n_383, n_384, n_385, n_386, n_387, n_388, n_389;
  wire n_390, n_391, n_392, n_393, n_394, n_395, n_396, n_397;
  wire n_398, n_399, n_400, n_401, n_402, n_403, n_404, n_405;
  wire n_406, n_407, n_408, n_409, n_410, n_411, n_412, n_413;
  wire n_414, n_415, n_416, n_417, n_418, n_419, n_420, n_421;
  wire n_422, n_423, n_424, n_425, n_426, n_427, n_428, n_429;
  wire n_430, n_431, n_432, n_433, n_434, n_435, n_436, n_441;
  wire n_448, n_450, n_453, n_1593_BAR, n_3615_BAR;
  assign total_power_consumed_out[0] = 1'b0;
  add_unsigned_4 add_152_54(.A (distance_travelled), .B
       (current_speed), .Z ({n_358, n_359, n_360, n_361, n_362, n_363,
       n_364, n_365, n_366, n_367, n_368, n_369, n_370, n_371, n_372,
       n_373, n_374, n_375, n_376, n_377, n_378, n_379, n_380, n_381,
       n_382, n_383, n_384, n_385, n_386, n_387, n_388, n_389}));
  add_signed add_155_74(.A (integral_error_accumulator), .B ({n_341,
       n_354, n_353, n_352, n_351, n_350, n_349, n_348, n_347}), .Z
       ({n_421, n_422, n_423, n_424, n_425, n_426, n_427, n_428, n_429,
       n_430, n_431, n_432, n_433, n_434, n_435, n_436}));
  csa_tree_add_153_58_group_2 csa_tree_add_153_58_groupi(.in_0
       (current_speed), .in_1 ({n_346, n_345, n_344,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, n_342, n_343,
       UNCONNECTED_HIER_Z}), .in_2 ({total_power_consumed[31:1],
       UNCONNECTED_HIER_Z2}), .out_0 ({n_390, n_391, n_392, n_393,
       n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401, n_402,
       n_403, n_404, n_405, n_406, n_407, n_408, n_409, n_410, n_411,
       n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419, n_420,
       UNCONNECTED}));
  DFFRX1 \acceleration_reg[1] (.RN (n_12), .CK (clk), .D (n_356), .Q
       (UNCONNECTED0), .QN (n_14));
  DFFRHQX1 \current_speed_out_reg[0] (.RN (n_12), .CK (clk), .D
       (current_speed[0]), .Q (n_320));
  DFFRHQX1 \current_speed_out_reg[1] (.RN (n_12), .CK (clk), .D
       (current_speed[1]), .Q (n_321));
  DFFRHQX1 \current_speed_out_reg[2] (.RN (n_12), .CK (clk), .D
       (current_speed[2]), .Q (n_322));
  DFFRHQX1 \current_speed_out_reg[3] (.RN (n_12), .CK (clk), .D
       (current_speed[3]), .Q (n_323));
  DFFRHQX1 \current_speed_out_reg[4] (.RN (n_12), .CK (clk), .D
       (current_speed[4]), .Q (n_324));
  DFFRHQX1 \current_speed_out_reg[5] (.RN (n_12), .CK (clk), .D
       (current_speed[5]), .Q (n_325));
  DFFRHQX1 \current_speed_out_reg[6] (.RN (n_12), .CK (clk), .D
       (current_speed[6]), .Q (n_326));
  DFFRHQX1 \current_speed_out_reg[7] (.RN (n_12), .CK (clk), .D
       (current_speed[7]), .Q (n_327));
  DFFRHQX1 \distance_travelled_out_reg[0] (.RN (n_12), .CK (clk), .D
       (distance_travelled[0]), .Q (n_288));
  DFFRHQX1 \distance_travelled_out_reg[1] (.RN (n_12), .CK (clk), .D
       (distance_travelled[1]), .Q (n_289));
  DFFRHQX1 \distance_travelled_out_reg[2] (.RN (n_12), .CK (clk), .D
       (distance_travelled[2]), .Q (n_290));
  DFFRHQX1 \distance_travelled_out_reg[3] (.RN (n_12), .CK (clk), .D
       (distance_travelled[3]), .Q (n_291));
  DFFRHQX1 \distance_travelled_out_reg[4] (.RN (n_12), .CK (clk), .D
       (distance_travelled[4]), .Q (n_292));
  DFFRHQX1 \distance_travelled_out_reg[5] (.RN (n_12), .CK (clk), .D
       (distance_travelled[5]), .Q (n_293));
  DFFRHQX1 \distance_travelled_out_reg[6] (.RN (n_12), .CK (clk), .D
       (distance_travelled[6]), .Q (n_294));
  DFFRHQX1 \distance_travelled_out_reg[7] (.RN (n_12), .CK (clk), .D
       (distance_travelled[7]), .Q (n_295));
  DFFRHQX1 \distance_travelled_out_reg[8] (.RN (n_12), .CK (clk), .D
       (distance_travelled[8]), .Q (n_296));
  DFFRHQX1 \distance_travelled_out_reg[9] (.RN (n_12), .CK (clk), .D
       (distance_travelled[9]), .Q (n_297));
  DFFRHQX1 \distance_travelled_out_reg[10] (.RN (n_12), .CK (clk), .D
       (distance_travelled[10]), .Q (n_298));
  DFFRHQX1 \distance_travelled_out_reg[11] (.RN (n_12), .CK (clk), .D
       (distance_travelled[11]), .Q (n_299));
  DFFRHQX1 \distance_travelled_out_reg[12] (.RN (n_12), .CK (clk), .D
       (distance_travelled[12]), .Q (n_300));
  DFFRHQX1 \distance_travelled_out_reg[13] (.RN (n_12), .CK (clk), .D
       (distance_travelled[13]), .Q (n_301));
  DFFRHQX1 \distance_travelled_out_reg[14] (.RN (n_12), .CK (clk), .D
       (distance_travelled[14]), .Q (n_302));
  DFFRHQX1 \distance_travelled_out_reg[15] (.RN (n_12), .CK (clk), .D
       (distance_travelled[15]), .Q (n_303));
  DFFRHQX1 \distance_travelled_out_reg[16] (.RN (n_12), .CK (clk), .D
       (distance_travelled[16]), .Q (n_304));
  DFFRHQX1 \distance_travelled_out_reg[17] (.RN (n_12), .CK (clk), .D
       (distance_travelled[17]), .Q (n_305));
  DFFRHQX1 \distance_travelled_out_reg[18] (.RN (n_12), .CK (clk), .D
       (distance_travelled[18]), .Q (n_306));
  DFFRHQX1 \distance_travelled_out_reg[19] (.RN (n_12), .CK (clk), .D
       (distance_travelled[19]), .Q (n_307));
  DFFRHQX1 \distance_travelled_out_reg[20] (.RN (n_12), .CK (clk), .D
       (distance_travelled[20]), .Q (n_308));
  DFFRHQX1 \distance_travelled_out_reg[21] (.RN (n_12), .CK (clk), .D
       (distance_travelled[21]), .Q (n_309));
  DFFRHQX1 \distance_travelled_out_reg[22] (.RN (n_12), .CK (clk), .D
       (distance_travelled[22]), .Q (n_310));
  DFFRHQX1 \distance_travelled_out_reg[23] (.RN (n_12), .CK (clk), .D
       (distance_travelled[23]), .Q (n_311));
  DFFRHQX1 \distance_travelled_out_reg[24] (.RN (n_12), .CK (clk), .D
       (distance_travelled[24]), .Q (n_312));
  DFFRHQX1 \distance_travelled_out_reg[25] (.RN (n_12), .CK (clk), .D
       (distance_travelled[25]), .Q (n_313));
  DFFRHQX1 \distance_travelled_out_reg[26] (.RN (n_12), .CK (clk), .D
       (distance_travelled[26]), .Q (n_314));
  DFFRHQX1 \distance_travelled_out_reg[27] (.RN (n_12), .CK (clk), .D
       (distance_travelled[27]), .Q (n_315));
  DFFRHQX1 \distance_travelled_out_reg[28] (.RN (n_12), .CK (clk), .D
       (distance_travelled[28]), .Q (n_316));
  DFFRHQX1 \distance_travelled_out_reg[29] (.RN (n_12), .CK (clk), .D
       (distance_travelled[29]), .Q (n_317));
  DFFRHQX1 \distance_travelled_out_reg[30] (.RN (n_12), .CK (clk), .D
       (distance_travelled[30]), .Q (n_318));
  DFFRHQX1 \distance_travelled_out_reg[31] (.RN (n_12), .CK (clk), .D
       (distance_travelled[31]), .Q (n_319));
  DFFRHQX1 \front_obstacle_history_reg[0] (.RN (n_12), .CK (clk), .D
       (front_obstacle_detected), .Q (front_obstacle_history[0]));
  DFFRHQX1 \front_obstacle_history_reg[1] (.RN (n_12), .CK (clk), .D
       (front_obstacle_history[0]), .Q (front_obstacle_history[1]));
  DFFRHQX1 \front_obstacle_history_reg[2] (.RN (n_12), .CK (clk), .D
       (front_obstacle_history[1]), .Q (front_obstacle_history[2]));
  DFFRHQX1 front_obstacle_slow_reg_reg(.RN (n_12), .CK (clk), .D
       (front_obstacle_slow), .Q (front_obstacle_slow_reg));
  DFFRHQX1 \indicators_reg[0] (.RN (n_12), .CK (clk), .D (n_203), .Q
       (n_328));
  DFFRHQX1 \indicators_reg[1] (.RN (n_12), .CK (clk), .D (n_204), .Q
       (n_329));
  DFFRHQX1 lane_clear_left_reg_reg(.RN (n_12), .CK (clk), .D
       (lane_clear_left), .Q (lane_clear_left_reg));
  DFFRHQX1 lane_clear_right_reg_reg(.RN (n_12), .CK (clk), .D
       (lane_clear_right), .Q (lane_clear_right_reg));
  DFFRHQX1 \left_obstacle_history_reg[0] (.RN (n_12), .CK (clk), .D
       (left_obstacle_detected), .Q (left_obstacle_history[0]));
  DFFRHQX1 \left_obstacle_history_reg[1] (.RN (n_12), .CK (clk), .D
       (left_obstacle_history[0]), .Q (left_obstacle_history[1]));
  DFFRHQX1 \left_obstacle_history_reg[2] (.RN (n_12), .CK (clk), .D
       (left_obstacle_history[1]), .Q (left_obstacle_history[2]));
  DFFRHQX1 \right_obstacle_history_reg[0] (.RN (n_12), .CK (clk), .D
       (right_obstacle_detected), .Q (right_obstacle_history[0]));
  DFFRHQX1 \right_obstacle_history_reg[1] (.RN (n_12), .CK (clk), .D
       (right_obstacle_history[0]), .Q (right_obstacle_history[1]));
  DFFRHQX1 \right_obstacle_history_reg[2] (.RN (n_12), .CK (clk), .D
       (right_obstacle_history[1]), .Q (right_obstacle_history[2]));
  DFFRHQX1 \speed_limit_zone_reg_reg[0] (.RN (n_12), .CK (clk), .D
       (speed_limit_zone[0]), .Q (speed_limit_zone_reg[0]));
  DFFRHQX1 \speed_limit_zone_reg_reg[1] (.RN (n_12), .CK (clk), .D
       (speed_limit_zone[1]), .Q (speed_limit_zone_reg[1]));
  DFFRHQX1 \steering_reg[0] (.RN (n_12), .CK (clk), .D (n_200), .Q
       (n_330));
  DFFRHQX1 \steering_reg[1] (.RN (n_12), .CK (clk), .D (n_197), .Q
       (n_331));
  DFFRHQX1 \total_power_consumed_out_reg[1] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[1]), .Q (n_257));
  DFFRHQX1 \total_power_consumed_out_reg[2] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[2]), .Q (n_258));
  DFFRHQX1 \total_power_consumed_out_reg[3] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[3]), .Q (n_259));
  DFFRHQX1 \total_power_consumed_out_reg[4] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[4]), .Q (n_260));
  DFFRHQX1 \total_power_consumed_out_reg[5] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[5]), .Q (n_261));
  DFFRHQX1 \total_power_consumed_out_reg[6] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[6]), .Q (n_262));
  DFFRHQX1 \total_power_consumed_out_reg[7] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[7]), .Q (n_263));
  DFFRHQX1 \total_power_consumed_out_reg[8] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[8]), .Q (n_264));
  DFFRHQX1 \total_power_consumed_out_reg[9] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[9]), .Q (n_265));
  DFFRHQX1 \total_power_consumed_out_reg[10] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[10]), .Q (n_266));
  DFFRHQX1 \total_power_consumed_out_reg[11] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[11]), .Q (n_267));
  DFFRHQX1 \total_power_consumed_out_reg[12] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[12]), .Q (n_268));
  DFFRHQX1 \total_power_consumed_out_reg[13] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[13]), .Q (n_269));
  DFFRHQX1 \total_power_consumed_out_reg[14] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[14]), .Q (n_270));
  DFFRHQX1 \total_power_consumed_out_reg[15] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[15]), .Q (n_271));
  DFFRHQX1 \total_power_consumed_out_reg[16] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[16]), .Q (n_272));
  DFFRHQX1 \total_power_consumed_out_reg[17] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[17]), .Q (n_273));
  DFFRHQX1 \total_power_consumed_out_reg[18] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[18]), .Q (n_274));
  DFFRHQX1 \total_power_consumed_out_reg[19] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[19]), .Q (n_275));
  DFFRHQX1 \total_power_consumed_out_reg[20] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[20]), .Q (n_276));
  DFFRHQX1 \total_power_consumed_out_reg[21] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[21]), .Q (n_277));
  DFFRHQX1 \total_power_consumed_out_reg[22] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[22]), .Q (n_278));
  DFFRHQX1 \total_power_consumed_out_reg[23] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[23]), .Q (n_279));
  DFFRHQX1 \total_power_consumed_out_reg[24] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[24]), .Q (n_280));
  DFFRHQX1 \total_power_consumed_out_reg[25] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[25]), .Q (n_281));
  DFFRHQX1 \total_power_consumed_out_reg[26] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[26]), .Q (n_282));
  DFFRHQX1 \total_power_consumed_out_reg[27] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[27]), .Q (n_283));
  DFFRHQX1 \total_power_consumed_out_reg[28] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[28]), .Q (n_284));
  DFFRHQX1 \total_power_consumed_out_reg[29] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[29]), .Q (n_285));
  DFFRHQX1 \total_power_consumed_out_reg[30] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[30]), .Q (n_286));
  DFFRHQX1 \total_power_consumed_out_reg[31] (.RN (n_12), .CK (clk), .D
       (total_power_consumed[31]), .Q (n_287));
  NAND2XL g5075(.A (n_256), .B (n_255), .Y (n_344));
  NAND2XL g5076(.A (n_173), .B (n_255), .Y (n_343));
  CLKINVX1 g5077(.A (n_256), .Y (n_345));
  NAND2XL g5078(.A (n_173), .B (n_342), .Y (n_256));
  NAND2BX1 g5079(.AN (n_342), .B (n_230), .Y (n_255));
  NOR2BX1 g5080(.AN (n_250), .B (n_254), .Y (n_342));
  CLKINVX1 g5081(.A (n_173), .Y (n_346));
  NOR4X1 g5083(.A (n_244), .B (n_351), .C (n_352), .D (n_353), .Y
       (n_254));
  AOI211X1 g5085(.A0 (n_351), .A1 (n_247), .B0 (n_352), .C0 (n_353), .Y
       (n_253));
  OA21X1 g5086(.A0 (n_206), .A1 (n_252), .B0 (n_341), .Y (n_354));
  NAND2XL g5087(.A (n_206), .B (n_252), .Y (n_341));
  OAI21X1 g5088(.A0 (n_228), .A1 (n_249), .B0 (n_226), .Y (n_252));
  OAI21X1 g5089(.A0 (n_233), .A1 (n_249), .B0 (n_251), .Y (n_353));
  NAND2XL g5090(.A (n_233), .B (n_249), .Y (n_251));
  NOR2BX1 g5091(.AN (n_230), .B (n_441), .Y (n_250));
  AOI21X1 g5092(.A0 (n_229), .A1 (n_246), .B0 (n_222), .Y (n_249));
  OAI21X1 g5093(.A0 (n_234), .A1 (n_246), .B0 (n_248), .Y (n_352));
  NAND2XL g5094(.A (n_234), .B (n_246), .Y (n_248));
  OAI211X1 g5095(.A0 (n_225), .A1 (n_243), .B0 (n_206), .C0 (n_227), .Y
       (n_441));
  AO21X1 g5096(.A0 (n_347), .A1 (n_349), .B0 (n_244), .Y (n_247));
  OAI21X1 g5097(.A0 (n_215), .A1 (n_242), .B0 (n_223), .Y (n_246));
  OAI21X1 g5098(.A0 (n_232), .A1 (n_242), .B0 (n_245), .Y (n_351));
  NAND2XL g5099(.A (n_232), .B (n_242), .Y (n_245));
  AO21X1 g5100(.A0 (n_349), .A1 (n_348), .B0 (n_350), .Y (n_244));
  NOR2BX1 g5101(.AN (n_229), .B (n_240), .Y (n_243));
  OAI21X1 g5102(.A0 (n_231), .A1 (n_239), .B0 (n_241), .Y (n_350));
  AOI21X1 g5103(.A0 (n_216), .A1 (n_239), .B0 (n_220), .Y (n_242));
  NAND2XL g5104(.A (n_231), .B (n_239), .Y (n_241));
  AOI2BB1XL g5105(.A0N (n_215), .A1N (n_238), .B0 (n_222), .Y (n_240));
  OAI21X1 g5106(.A0 (n_218), .A1 (n_237), .B0 (n_212), .Y (n_239));
  CLKXOR2X1 g5107(.A (n_219), .B (n_237), .Y (n_349));
  AOI21X1 g5108(.A0 (n_216), .A1 (n_235), .B0 (n_224), .Y (n_238));
  INVX1 g5109(.A (n_236), .Y (n_348));
  ADDFX1 g5110(.A (n_347), .B (current_speed[1]), .CI (n_211), .CO
       (n_237), .S (n_236));
  OAI211X1 g5111(.A0 (current_speed[1]), .A1 (n_211), .B0 (n_212), .C0
       (n_221), .Y (n_235));
  NAND2BX1 g5112(.AN (n_222), .B (n_229), .Y (n_234));
  NOR2XL g5113(.A (n_228), .B (n_225), .Y (n_233));
  NOR2XL g5114(.A (n_215), .B (n_224), .Y (n_232));
  NAND2XL g5115(.A (n_216), .B (n_221), .Y (n_231));
  CLKINVX1 g5116(.A (n_227), .Y (n_228));
  INVXL g5117(.A (n_225), .Y (n_226));
  NOR2BX1 g5118(.AN (acceleration[1]), .B (acceleration[0]), .Y
       (n_230));
  NAND2XL g5119(.A (current_speed[5]), .B (n_214), .Y (n_229));
  NAND2XL g5120(.A (current_speed[6]), .B (n_213), .Y (n_227));
  NOR2XL g5121(.A (current_speed[6]), .B (n_213), .Y (n_225));
  INVX1 g5122(.A (n_224), .Y (n_223));
  INVX1 g5123(.A (n_220), .Y (n_221));
  NAND2XL g5124(.A (n_217), .B (n_212), .Y (n_219));
  NOR3X1 g5125(.A (current_speed[4]), .B (n_448), .C (n_207), .Y
       (n_224));
  NOR2XL g5126(.A (current_speed[5]), .B (n_214), .Y (n_222));
  NOR3X1 g5127(.A (current_speed[3]), .B (n_448), .C (n_207), .Y
       (n_220));
  CLKINVX8 g5128(.A (n_14), .Y (acceleration[1]));
  INVX1 g5130(.A (n_217), .Y (n_218));
  NAND2XL g5132(.A (current_speed[2]), .B (n_209), .Y (n_217));
  NAND2XL g5133(.A (current_speed[3]), .B (n_207), .Y (n_216));
  NOR2BX1 g5134(.AN (current_speed[4]), .B (n_208), .Y (n_215));
  OAI221X1 g5135(.A0 (speed_limit_zone_reg[0]), .A1 (n_184), .B0
       (current_speed[5]), .B1 (n_176), .C0 (n_210), .Y (n_214));
  NAND3X1 g5136(.A (n_181), .B (n_191), .C (n_202), .Y (n_213));
  NAND3BX1 g5137(.AN (current_speed[2]), .B (n_176), .C (n_205), .Y
       (n_212));
  OAI211X1 g5138(.A0 (current_speed[1]), .A1 (n_176), .B0 (n_181), .C0
       (n_208), .Y (n_211));
  INVXL g5141(.A (n_209), .Y (n_210));
  CLKINVX1 g5142(.A (n_208), .Y (n_207));
  NAND2XL g5143(.A (n_191), .B (n_205), .Y (n_209));
  OAI211X1 g5144(.A0 (n_448), .A1 (n_189), .B0 (n_196), .C0 (n_199), .Y
       (n_356));
  AOI211X1 g5145(.A0 (speed_limit_zone_reg[1]), .A1 (n_176), .B0
       (n_190), .C0 (n_201), .Y (n_208));
  NAND2XL g5148(.A (current_speed[7]), .B (n_198), .Y (n_206));
  AND2X1 g5149(.A (current_speed[0]), .B (n_198), .Y (n_347));
  NAND2BXL g5150(.AN (next_state[7]), .B (n_196), .Y (n_204));
  NAND2XL g5151(.A (n_195), .B (n_199), .Y (n_203));
  AOI211X1 g5152(.A0 (n_175), .A1 (n_448), .B0 (n_183), .C0 (n_201), .Y
       (n_202));
  AOI21X1 g5153(.A0 (speed_limit_zone_reg[1]), .A1 (n_180), .B0
       (n_201), .Y (n_205));
  INVXL g5154(.A (n_199), .Y (n_200));
  OAI21X1 g5155(.A0 (n_448), .A1 (n_194), .B0 (n_179), .Y (n_201));
  NAND3BX1 g5156(.AN (current_state[7]), .B (current_state[5]), .C
       (n_192), .Y (n_199));
  INVXL g5157(.A (n_196), .Y (n_197));
  NAND4BXL g5158(.AN (current_state[8]), .B (n_179), .C (n_448), .D
       (n_188), .Y (n_198));
  NAND3BX1 g5159(.AN (current_state[5]), .B (current_state[7]), .C
       (n_192), .Y (n_196));
  NOR2XL g5160(.A (current_state[4]), .B (n_193), .Y (next_state[7]));
  INVXL g5161(.A (n_195), .Y (next_state[5]));
  NAND3X1 g5162(.A (current_state[4]), .B (n_178), .C (n_355), .Y
       (n_195));
  NOR3BX1 g5163(.AN (n_185), .B (n_450), .C (n_186), .Y (n_194));
  NAND2XL g5164(.A (current_state[6]), .B (n_187), .Y (n_193));
  CLKINVX1 g5165(.A (n_190), .Y (n_191));
  NAND3BX1 g5166(.AN (n_186), .B (current_state[1]), .C (n_13), .Y
       (n_189));
  NOR3X1 g5167(.A (current_state[1]), .B (n_448), .C (n_186), .Y
       (n_192));
  NOR2XL g5168(.A (n_176), .B (n_187), .Y (n_190));
  INVXL g5169(.A (n_188), .Y (n_335));
  NOR2XL g5170(.A (current_state[2]), .B (n_338), .Y (n_188));
  NOR2BX1 g5171(.AN (n_450), .B (n_186), .Y (n_187));
  NOR2XL g5172(.A (current_state[6]), .B (n_338), .Y (n_355));
  NAND2XL g5176(.A (n_13), .B (n_182), .Y (n_339));
  AOI22X1 g5177(.A0 (current_state[1]), .A1 (n_337), .B0
       (current_state[5]), .B1 (current_state[7]), .Y (n_185));
  NAND2XL g5178(.A (n_450), .B (n_182), .Y (n_338));
  NAND2XL g5179(.A (n_178), .B (n_182), .Y (n_186));
  NAND2BX1 g5180(.AN (current_state[10]), .B (n_13), .Y (n_336));
  NOR2XL g5184(.A (current_state[1]), .B (n_337), .Y (n_450));
  INVX1 g5185(.A (n_183), .Y (n_184));
  INVXL g5186(.A (n_181), .Y (n_180));
  NAND2XL g5187(.A (n_13), .B (n_334), .Y (n_340));
  NOR2XL g5189(.A (speed_limit_zone_reg[1]), .B (n_448), .Y (n_183));
  NOR2BX1 g5190(.AN (n_334), .B (current_state[3]), .Y (n_182));
  NAND2XL g5191(.A (speed_limit_zone_reg[0]), .B (n_176), .Y (n_181));
  CLKINVX1 g5236(.A (n_13), .Y (n_337));
  CLKINVX1 g5237(.A (n_176), .Y (n_448));
  NOR2XL g5265(.A (current_state[0]), .B (current_state[3]), .Y
       (n_3615_BAR));
  NAND2XL g5275(.A (current_state[4]), .B (current_state[6]), .Y
       (n_179));
  NOR2XL g5276(.A (current_state[10]), .B (current_state[0]), .Y
       (n_334));
  NOR2XL g5278(.A (current_state[8]), .B (current_state[2]), .Y
       (n_178));
  NOR2XL g5280(.A (current_state[4]), .B (current_state[6]), .Y
       (n_176));
  INVXL g5283(.A (rst), .Y (n_12));
  NAND2BX1 g2(.AN (n_253), .B (n_250), .Y (n_173));
  NAND2BX1 g5284(.AN (current_state[4]), .B (n_178), .Y (n_1593_BAR));
  BUFX8 g5285(.A (n_320), .Y (current_speed_out[0]));
  BUFX8 g5286(.A (n_321), .Y (current_speed_out[1]));
  BUFX8 g5287(.A (n_322), .Y (current_speed_out[2]));
  BUFX8 g5288(.A (n_323), .Y (current_speed_out[3]));
  BUFX8 g5289(.A (n_324), .Y (current_speed_out[4]));
  BUFX8 g5290(.A (n_325), .Y (current_speed_out[5]));
  BUFX8 g5291(.A (n_326), .Y (current_speed_out[6]));
  BUFX8 g5292(.A (n_327), .Y (current_speed_out[7]));
  BUFX8 g5293(.A (n_288), .Y (distance_travelled_out[0]));
  BUFX8 g5294(.A (n_289), .Y (distance_travelled_out[1]));
  BUFX8 g5295(.A (n_290), .Y (distance_travelled_out[2]));
  BUFX8 g5296(.A (n_291), .Y (distance_travelled_out[3]));
  BUFX8 g5297(.A (n_292), .Y (distance_travelled_out[4]));
  BUFX8 g5298(.A (n_293), .Y (distance_travelled_out[5]));
  BUFX8 g5299(.A (n_294), .Y (distance_travelled_out[6]));
  BUFX8 g5300(.A (n_295), .Y (distance_travelled_out[7]));
  BUFX8 g5301(.A (n_296), .Y (distance_travelled_out[8]));
  BUFX8 g5302(.A (n_297), .Y (distance_travelled_out[9]));
  BUFX8 g5303(.A (n_298), .Y (distance_travelled_out[10]));
  BUFX8 g5304(.A (n_299), .Y (distance_travelled_out[11]));
  BUFX8 g5305(.A (n_300), .Y (distance_travelled_out[12]));
  BUFX8 g5306(.A (n_301), .Y (distance_travelled_out[13]));
  BUFX8 g5307(.A (n_302), .Y (distance_travelled_out[14]));
  BUFX8 g5308(.A (n_303), .Y (distance_travelled_out[15]));
  BUFX8 g5309(.A (n_304), .Y (distance_travelled_out[16]));
  BUFX8 g5310(.A (n_305), .Y (distance_travelled_out[17]));
  BUFX8 g5311(.A (n_306), .Y (distance_travelled_out[18]));
  BUFX8 g5312(.A (n_307), .Y (distance_travelled_out[19]));
  BUFX8 g5313(.A (n_308), .Y (distance_travelled_out[20]));
  BUFX8 g5314(.A (n_309), .Y (distance_travelled_out[21]));
  BUFX8 g5315(.A (n_310), .Y (distance_travelled_out[22]));
  BUFX8 g5316(.A (n_311), .Y (distance_travelled_out[23]));
  BUFX8 g5317(.A (n_312), .Y (distance_travelled_out[24]));
  BUFX8 g5318(.A (n_313), .Y (distance_travelled_out[25]));
  BUFX8 g5319(.A (n_314), .Y (distance_travelled_out[26]));
  BUFX8 g5320(.A (n_315), .Y (distance_travelled_out[27]));
  BUFX8 g5321(.A (n_316), .Y (distance_travelled_out[28]));
  BUFX8 g5322(.A (n_317), .Y (distance_travelled_out[29]));
  BUFX8 g5323(.A (n_318), .Y (distance_travelled_out[30]));
  BUFX8 g5324(.A (n_319), .Y (distance_travelled_out[31]));
  BUFX8 g5325(.A (n_328), .Y (indicators[0]));
  BUFX8 g5326(.A (n_329), .Y (indicators[1]));
  BUFX8 g5327(.A (n_330), .Y (steering[0]));
  BUFX8 g5328(.A (n_331), .Y (steering[1]));
  BUFX8 g5329(.A (n_257), .Y (total_power_consumed_out[1]));
  BUFX8 g5330(.A (n_258), .Y (total_power_consumed_out[2]));
  BUFX8 g5331(.A (n_259), .Y (total_power_consumed_out[3]));
  BUFX8 g5332(.A (n_260), .Y (total_power_consumed_out[4]));
  BUFX8 g5333(.A (n_261), .Y (total_power_consumed_out[5]));
  BUFX8 g5334(.A (n_262), .Y (total_power_consumed_out[6]));
  BUFX8 g5335(.A (n_263), .Y (total_power_consumed_out[7]));
  BUFX8 g5336(.A (n_264), .Y (total_power_consumed_out[8]));
  BUFX8 g5337(.A (n_265), .Y (total_power_consumed_out[9]));
  BUFX8 g5338(.A (n_266), .Y (total_power_consumed_out[10]));
  BUFX8 g5339(.A (n_267), .Y (total_power_consumed_out[11]));
  BUFX8 g5340(.A (n_268), .Y (total_power_consumed_out[12]));
  BUFX8 g5341(.A (n_269), .Y (total_power_consumed_out[13]));
  BUFX8 g5342(.A (n_270), .Y (total_power_consumed_out[14]));
  BUFX8 g5343(.A (n_271), .Y (total_power_consumed_out[15]));
  BUFX8 g5344(.A (n_272), .Y (total_power_consumed_out[16]));
  BUFX8 g5345(.A (n_273), .Y (total_power_consumed_out[17]));
  BUFX8 g5346(.A (n_274), .Y (total_power_consumed_out[18]));
  BUFX8 g5347(.A (n_275), .Y (total_power_consumed_out[19]));
  BUFX8 g5348(.A (n_276), .Y (total_power_consumed_out[20]));
  BUFX8 g5349(.A (n_277), .Y (total_power_consumed_out[21]));
  BUFX8 g5350(.A (n_278), .Y (total_power_consumed_out[22]));
  BUFX8 g5351(.A (n_279), .Y (total_power_consumed_out[23]));
  BUFX8 g5352(.A (n_280), .Y (total_power_consumed_out[24]));
  BUFX8 g5353(.A (n_281), .Y (total_power_consumed_out[25]));
  BUFX8 g5354(.A (n_282), .Y (total_power_consumed_out[26]));
  BUFX8 g5355(.A (n_283), .Y (total_power_consumed_out[27]));
  BUFX8 g5356(.A (n_284), .Y (total_power_consumed_out[28]));
  BUFX8 g5357(.A (n_285), .Y (total_power_consumed_out[29]));
  BUFX8 g5358(.A (n_286), .Y (total_power_consumed_out[30]));
  BUFX8 g5359(.A (n_287), .Y (total_power_consumed_out[31]));
  DFFSHQX8 \acceleration_reg[0] (.SN (n_12), .CK (clk), .D (n_113), .Q
       (acceleration[0]));
  SDFFRHQX1 \current_speed_reg[0] (.RN (n_12), .CK (clk), .D (n_15),
       .SI (current_speed[0]), .SE (n_50), .Q (current_speed[0]));
  DFFRHQX1 \current_speed_reg[1] (.RN (n_12), .CK (clk), .D (n_145), .Q
       (current_speed[1]));
  DFFRHQX1 \current_speed_reg[3] (.RN (n_12), .CK (clk), .D (n_158), .Q
       (current_speed[3]));
  DFFSHQX1 \current_state_reg[0] (.SN (n_12), .CK (clk), .D (n_152), .Q
       (current_state[0]));
  DFFRHQX1 \current_state_reg[4] (.RN (n_12), .CK (clk), .D (n_115), .Q
       (current_state[4]));
  DFFRHQX1 \current_state_reg[5] (.RN (n_12), .CK (clk), .D
       (next_state[5]), .Q (current_state[5]));
  DFFRHQX1 \current_state_reg[6] (.RN (n_12), .CK (clk), .D (n_137), .Q
       (current_state[6]));
  DFFRHQX1 \current_state_reg[7] (.RN (n_12), .CK (clk), .D
       (next_state[7]), .Q (current_state[7]));
  DFFRHQX1 \distance_travelled_reg[0] (.RN (n_12), .CK (clk), .D
       (n_389), .Q (distance_travelled[0]));
  DFFRHQX1 \distance_travelled_reg[1] (.RN (n_12), .CK (clk), .D
       (n_388), .Q (distance_travelled[1]));
  DFFRHQX1 \distance_travelled_reg[2] (.RN (n_12), .CK (clk), .D
       (n_387), .Q (distance_travelled[2]));
  DFFRHQX1 \distance_travelled_reg[3] (.RN (n_12), .CK (clk), .D
       (n_386), .Q (distance_travelled[3]));
  DFFRHQX1 \distance_travelled_reg[4] (.RN (n_12), .CK (clk), .D
       (n_385), .Q (distance_travelled[4]));
  DFFRHQX1 \distance_travelled_reg[5] (.RN (n_12), .CK (clk), .D
       (n_384), .Q (distance_travelled[5]));
  DFFRHQX1 \distance_travelled_reg[6] (.RN (n_12), .CK (clk), .D
       (n_383), .Q (distance_travelled[6]));
  DFFRHQX1 \distance_travelled_reg[7] (.RN (n_12), .CK (clk), .D
       (n_382), .Q (distance_travelled[7]));
  DFFRHQX1 \distance_travelled_reg[8] (.RN (n_12), .CK (clk), .D
       (n_381), .Q (distance_travelled[8]));
  DFFRHQX1 \distance_travelled_reg[9] (.RN (n_12), .CK (clk), .D
       (n_380), .Q (distance_travelled[9]));
  DFFRHQX1 \distance_travelled_reg[10] (.RN (n_12), .CK (clk), .D
       (n_379), .Q (distance_travelled[10]));
  DFFRHQX1 \distance_travelled_reg[11] (.RN (n_12), .CK (clk), .D
       (n_378), .Q (distance_travelled[11]));
  DFFRHQX1 \distance_travelled_reg[12] (.RN (n_12), .CK (clk), .D
       (n_377), .Q (distance_travelled[12]));
  DFFRHQX1 \distance_travelled_reg[13] (.RN (n_12), .CK (clk), .D
       (n_376), .Q (distance_travelled[13]));
  DFFRHQX1 \distance_travelled_reg[14] (.RN (n_12), .CK (clk), .D
       (n_375), .Q (distance_travelled[14]));
  DFFRHQX1 \distance_travelled_reg[15] (.RN (n_12), .CK (clk), .D
       (n_374), .Q (distance_travelled[15]));
  DFFRHQX1 \distance_travelled_reg[16] (.RN (n_12), .CK (clk), .D
       (n_373), .Q (distance_travelled[16]));
  DFFRHQX1 \distance_travelled_reg[17] (.RN (n_12), .CK (clk), .D
       (n_372), .Q (distance_travelled[17]));
  DFFRHQX1 \distance_travelled_reg[18] (.RN (n_12), .CK (clk), .D
       (n_371), .Q (distance_travelled[18]));
  DFFRHQX1 \distance_travelled_reg[19] (.RN (n_12), .CK (clk), .D
       (n_370), .Q (distance_travelled[19]));
  DFFRHQX1 \distance_travelled_reg[20] (.RN (n_12), .CK (clk), .D
       (n_369), .Q (distance_travelled[20]));
  DFFRHQX1 \distance_travelled_reg[21] (.RN (n_12), .CK (clk), .D
       (n_368), .Q (distance_travelled[21]));
  DFFRHQX1 \distance_travelled_reg[22] (.RN (n_12), .CK (clk), .D
       (n_367), .Q (distance_travelled[22]));
  DFFRHQX1 \distance_travelled_reg[23] (.RN (n_12), .CK (clk), .D
       (n_366), .Q (distance_travelled[23]));
  DFFRHQX1 \distance_travelled_reg[24] (.RN (n_12), .CK (clk), .D
       (n_365), .Q (distance_travelled[24]));
  DFFRHQX1 \distance_travelled_reg[25] (.RN (n_12), .CK (clk), .D
       (n_364), .Q (distance_travelled[25]));
  DFFRHQX1 \distance_travelled_reg[26] (.RN (n_12), .CK (clk), .D
       (n_363), .Q (distance_travelled[26]));
  DFFRHQX1 \distance_travelled_reg[27] (.RN (n_12), .CK (clk), .D
       (n_362), .Q (distance_travelled[27]));
  DFFRHQX1 \distance_travelled_reg[28] (.RN (n_12), .CK (clk), .D
       (n_361), .Q (distance_travelled[28]));
  DFFRHQX1 \distance_travelled_reg[29] (.RN (n_12), .CK (clk), .D
       (n_360), .Q (distance_travelled[29]));
  DFFRHQX1 \distance_travelled_reg[30] (.RN (n_12), .CK (clk), .D
       (n_359), .Q (distance_travelled[30]));
  DFFRHQX1 \distance_travelled_reg[31] (.RN (n_12), .CK (clk), .D
       (n_358), .Q (distance_travelled[31]));
  DFFRHQX1 \integral_error_accumulator_reg[0] (.RN (n_12), .CK (clk),
       .D (n_89), .Q (integral_error_accumulator[0]));
  DFFRHQX1 \integral_error_accumulator_reg[1] (.RN (n_12), .CK (clk),
       .D (n_88), .Q (integral_error_accumulator[1]));
  DFFRHQX1 \integral_error_accumulator_reg[2] (.RN (n_12), .CK (clk),
       .D (n_87), .Q (integral_error_accumulator[2]));
  DFFRHQX1 \integral_error_accumulator_reg[3] (.RN (n_12), .CK (clk),
       .D (n_80), .Q (integral_error_accumulator[3]));
  DFFRHQX1 \integral_error_accumulator_reg[4] (.RN (n_12), .CK (clk),
       .D (n_86), .Q (integral_error_accumulator[4]));
  DFFRHQX1 \integral_error_accumulator_reg[5] (.RN (n_12), .CK (clk),
       .D (n_78), .Q (integral_error_accumulator[5]));
  DFFRHQX1 \integral_error_accumulator_reg[6] (.RN (n_12), .CK (clk),
       .D (n_85), .Q (integral_error_accumulator[6]));
  DFFRHQX1 \integral_error_accumulator_reg[7] (.RN (n_12), .CK (clk),
       .D (n_77), .Q (integral_error_accumulator[7]));
  DFFRHQX1 \integral_error_accumulator_reg[8] (.RN (n_12), .CK (clk),
       .D (n_84), .Q (integral_error_accumulator[8]));
  DFFRHQX1 \integral_error_accumulator_reg[9] (.RN (n_12), .CK (clk),
       .D (n_70), .Q (integral_error_accumulator[9]));
  DFFRHQX1 \integral_error_accumulator_reg[10] (.RN (n_12), .CK (clk),
       .D (n_83), .Q (integral_error_accumulator[10]));
  DFFRHQX1 \integral_error_accumulator_reg[11] (.RN (n_12), .CK (clk),
       .D (n_71), .Q (integral_error_accumulator[11]));
  DFFRHQX1 \integral_error_accumulator_reg[13] (.RN (n_12), .CK (clk),
       .D (n_63), .Q (integral_error_accumulator[13]));
  DFFRHQX1 \integral_error_accumulator_reg[14] (.RN (n_12), .CK (clk),
       .D (n_79), .Q (integral_error_accumulator[14]));
  DFFRHQX1 \integral_error_accumulator_reg[15] (.RN (n_12), .CK (clk),
       .D (n_81), .Q (integral_error_accumulator[15]));
  DFFRHQX1 \total_power_consumed_reg[1] (.RN (n_12), .CK (clk), .D
       (n_420), .Q (total_power_consumed[1]));
  DFFRHQX1 \total_power_consumed_reg[2] (.RN (n_12), .CK (clk), .D
       (n_419), .Q (total_power_consumed[2]));
  DFFRHQX1 \total_power_consumed_reg[3] (.RN (n_12), .CK (clk), .D
       (n_418), .Q (total_power_consumed[3]));
  DFFRHQX1 \total_power_consumed_reg[4] (.RN (n_12), .CK (clk), .D
       (n_417), .Q (total_power_consumed[4]));
  DFFRHQX1 \total_power_consumed_reg[5] (.RN (n_12), .CK (clk), .D
       (n_416), .Q (total_power_consumed[5]));
  DFFRHQX1 \total_power_consumed_reg[6] (.RN (n_12), .CK (clk), .D
       (n_415), .Q (total_power_consumed[6]));
  DFFRHQX1 \total_power_consumed_reg[7] (.RN (n_12), .CK (clk), .D
       (n_414), .Q (total_power_consumed[7]));
  DFFRHQX1 \total_power_consumed_reg[8] (.RN (n_12), .CK (clk), .D
       (n_413), .Q (total_power_consumed[8]));
  DFFRHQX1 \total_power_consumed_reg[9] (.RN (n_12), .CK (clk), .D
       (n_412), .Q (total_power_consumed[9]));
  DFFRHQX1 \total_power_consumed_reg[10] (.RN (n_12), .CK (clk), .D
       (n_411), .Q (total_power_consumed[10]));
  DFFRHQX1 \total_power_consumed_reg[11] (.RN (n_12), .CK (clk), .D
       (n_410), .Q (total_power_consumed[11]));
  DFFRHQX1 \total_power_consumed_reg[12] (.RN (n_12), .CK (clk), .D
       (n_409), .Q (total_power_consumed[12]));
  DFFRHQX1 \total_power_consumed_reg[13] (.RN (n_12), .CK (clk), .D
       (n_408), .Q (total_power_consumed[13]));
  DFFRHQX1 \total_power_consumed_reg[14] (.RN (n_12), .CK (clk), .D
       (n_407), .Q (total_power_consumed[14]));
  DFFRHQX1 \total_power_consumed_reg[15] (.RN (n_12), .CK (clk), .D
       (n_406), .Q (total_power_consumed[15]));
  DFFRHQX1 \total_power_consumed_reg[16] (.RN (n_12), .CK (clk), .D
       (n_405), .Q (total_power_consumed[16]));
  DFFRHQX1 \total_power_consumed_reg[17] (.RN (n_12), .CK (clk), .D
       (n_404), .Q (total_power_consumed[17]));
  DFFRHQX1 \total_power_consumed_reg[18] (.RN (n_12), .CK (clk), .D
       (n_403), .Q (total_power_consumed[18]));
  DFFRHQX1 \total_power_consumed_reg[19] (.RN (n_12), .CK (clk), .D
       (n_402), .Q (total_power_consumed[19]));
  DFFRHQX1 \total_power_consumed_reg[20] (.RN (n_12), .CK (clk), .D
       (n_401), .Q (total_power_consumed[20]));
  DFFRHQX1 \total_power_consumed_reg[21] (.RN (n_12), .CK (clk), .D
       (n_400), .Q (total_power_consumed[21]));
  DFFRHQX1 \total_power_consumed_reg[22] (.RN (n_12), .CK (clk), .D
       (n_399), .Q (total_power_consumed[22]));
  DFFRHQX1 \total_power_consumed_reg[23] (.RN (n_12), .CK (clk), .D
       (n_398), .Q (total_power_consumed[23]));
  DFFRHQX1 \total_power_consumed_reg[24] (.RN (n_12), .CK (clk), .D
       (n_397), .Q (total_power_consumed[24]));
  DFFRHQX1 \total_power_consumed_reg[25] (.RN (n_12), .CK (clk), .D
       (n_396), .Q (total_power_consumed[25]));
  DFFRHQX1 \total_power_consumed_reg[26] (.RN (n_12), .CK (clk), .D
       (n_395), .Q (total_power_consumed[26]));
  DFFRHQX1 \total_power_consumed_reg[27] (.RN (n_12), .CK (clk), .D
       (n_394), .Q (total_power_consumed[27]));
  DFFRHQX1 \total_power_consumed_reg[28] (.RN (n_12), .CK (clk), .D
       (n_393), .Q (total_power_consumed[28]));
  DFFRHQX1 \total_power_consumed_reg[29] (.RN (n_12), .CK (clk), .D
       (n_392), .Q (total_power_consumed[29]));
  DFFRHQX1 \total_power_consumed_reg[30] (.RN (n_12), .CK (clk), .D
       (n_391), .Q (total_power_consumed[30]));
  DFFRHQX1 \total_power_consumed_reg[31] (.RN (n_12), .CK (clk), .D
       (n_390), .Q (total_power_consumed[31]));
  OAI221X1 g6430(.A0 (n_14), .A1 (n_170), .B0 (current_speed[7]), .B1
       (n_135), .C0 (n_142), .Y (n_172));
  OAI211X1 g6432(.A0 (n_14), .A1 (n_167), .B0 (n_135), .C0 (n_147), .Y
       (n_171));
  AOI21X1 g6433(.A0 (n_98), .A1 (n_168), .B0 (n_169), .Y (n_170));
  NOR2XL g6435(.A (n_98), .B (n_168), .Y (n_169));
  ADDFX1 g6436(.A (n_42), .B (n_22), .CI (n_164), .CO (n_168), .S
       (n_167));
  OAI222XL g6437(.A0 (n_4), .A1 (n_130), .B0 (n_14), .B1 (n_163), .C0
       (n_134), .C1 (current_speed[5]), .Y (n_166));
  OAI211X1 g6439(.A0 (n_3), .A1 (n_146), .B0 (n_134), .C0 (n_162), .Y
       (n_165));
  AOI21X1 g6440(.A0 (n_76), .A1 (n_160), .B0 (n_99), .Y (n_164));
  AOI21XL g6441(.A0 (n_108), .A1 (n_160), .B0 (n_161), .Y (n_163));
  NAND2XL g6443(.A (acceleration[1]), .B (n_159), .Y (n_162));
  NOR2XL g6444(.A (n_108), .B (n_160), .Y (n_161));
  ADDFX1 g6445(.A (n_102), .B (n_36), .CI (n_155), .CO (n_160), .S
       (n_159));
  OAI211X1 g6446(.A0 (current_speed[3]), .A1 (n_143), .B0 (n_148), .C0
       (n_157), .Y (n_158));
  NAND2XL g6448(.A (acceleration[1]), .B (n_156), .Y (n_157));
  ADDFX1 g6449(.A (n_100), .B (n_103), .CI (n_149), .CO (n_155), .S
       (n_156));
  OAI211X1 g6451(.A0 (n_2), .A1 (n_129), .B0 (n_143), .C0 (n_151), .Y
       (n_154));
  OAI21X1 g6453(.A0 (n_45), .A1 (n_144), .B0 (n_109), .Y (n_153));
  OAI211XL g6454(.A0 (n_136), .A1 (n_45), .B0 (n_64), .C0 (n_131), .Y
       (n_152));
  NAND2XL g6456(.A (acceleration[1]), .B (n_150), .Y (n_151));
  ADDFX1 g6457(.A (n_58), .B (n_101), .CI (n_122), .CO (n_149), .S
       (n_150));
  NAND2XL g6458(.A (current_speed[3]), .B (n_141), .Y (n_148));
  NAND2XL g6459(.A (current_speed[6]), .B (n_138), .Y (n_147));
  AOI21X1 g6461(.A0 (n_14), .A1 (current_speed[3]), .B0 (n_141), .Y
       (n_146));
  OAI2BB1XL g6462(.A0N (current_speed[1]), .A1N (n_124), .B0 (n_140),
       .Y (n_145));
  OAI211X1 g6463(.A0 (n_43), .A1 (n_3615_BAR), .B0 (n_51), .C0 (n_139),
       .Y (n_144));
  OAI21X1 g6464(.A0 (n_105), .A1 (n_124), .B0 (current_speed[7]), .Y
       (n_142));
  NAND2XL g6465(.A (n_2), .B (n_133), .Y (n_143));
  AOI21X1 g6469(.A0 (acceleration[1]), .A1 (n_123), .B0 (n_133), .Y
       (n_140));
  NOR2XL g6470(.A (n_34), .B (n_127), .Y (n_139));
  OAI21X1 g6471(.A0 (acceleration[1]), .A1 (n_4), .B0 (n_130), .Y
       (n_138));
  NOR3X1 g6472(.A (current_state[10]), .B (n_21), .C (n_117), .Y
       (n_137));
  AOI221X1 g6473(.A0 (n_27), .A1 (n_339), .B0 (current_state[2]), .B1
       (n_338), .C0 (n_125), .Y (n_136));
  OAI21X1 g6474(.A0 (acceleration[1]), .A1 (n_2), .B0 (n_129), .Y
       (n_141));
  NOR2BX1 g6475(.AN (front_obstacle_slow_reg), .B (n_119), .Y (n_132));
  OAI21X1 g6476(.A0 (current_state[4]), .A1 (n_116), .B0
       (current_state[8]), .Y (n_131));
  NAND2XL g6477(.A (n_96), .B (n_121), .Y (n_135));
  NAND2XL g6478(.A (n_54), .B (n_121), .Y (n_134));
  NOR2XL g6479(.A (current_speed[1]), .B (n_120), .Y (n_133));
  OAI32X1 g6480(.A0 (n_16), .A1 (n_336), .A2 (n_90), .B0 (n_45), .B1
       (n_114), .Y (n_128));
  OAI211X1 g6481(.A0 (n_7), .A1 (n_25), .B0 (n_75), .C0 (n_112), .Y
       (n_127));
  NOR2XL g6482(.A (n_116), .B (n_118), .Y (n_126));
  OAI22X1 g6483(.A0 (n_21), .A1 (n_110), .B0 (n_13), .B1 (n_55), .Y
       (n_125));
  AOI2BB1X1 g6484(.A0N (acceleration[1]), .A1N (n_54), .B0 (n_124), .Y
       (n_130));
  AOI21X1 g6485(.A0 (n_14), .A1 (current_speed[1]), .B0 (n_124), .Y
       (n_129));
  ADDFX1 g6486(.A (n_59), .B (current_speed[1]), .CI (n_56), .CO
       (n_122), .S (n_123));
  NOR2XL g6489(.A (acceleration[1]), .B (n_0), .Y (n_124));
  CLKINVX1 g6491(.A (n_120), .Y (n_121));
  AOI33XL g6492(.A0 (n_20), .A1 (n_61), .A2 (n_91), .B0 (n_43), .B1
       (n_35), .B2 (n_73), .Y (n_119));
  OAI211X1 g6493(.A0 (n_73), .A1 (n_95), .B0 (n_35), .C0 (n_66), .Y
       (n_118));
  OR4XL g6494(.A (n_62), .B (n_60), .C (n_45), .D (n_97), .Y (n_117));
  NAND2XL g6495(.A (n_14), .B (n_0), .Y (n_120));
  NOR3X1 g6496(.A (n_61), .B (current_state[1]), .C (n_453), .Y
       (n_115));
  NAND2XL g6497(.A (n_13), .B (n_107), .Y (n_114));
  NOR2XL g6499(.A (n_44), .B (n_106), .Y (n_116));
  NOR3XL g6500(.A (n_93), .B (n_52), .C (n_356), .Y (n_113));
  NAND2XL g6501(.A (current_state[3]), .B (n_104), .Y (n_112));
  AND4XL g6502(.A (n_41), .B (n_25), .C (n_74), .D (n_441), .Y (n_111));
  AOI221X1 g6503(.A0 (current_state[3]), .A1 (n_340), .B0
       (current_state[0]), .B1 (n_65), .C0 (n_94), .Y (n_110));
  NAND4BXL g6504(.AN (n_441), .B (n_27), .C (n_25), .D (n_74), .Y
       (n_109));
  AOI21X1 g6505(.A0 (n_55), .A1 (n_68), .B0 (n_334), .Y (n_107));
  NAND2BX1 g6506(.AN (n_99), .B (n_76), .Y (n_108));
  NOR2XL g6509(.A (acceleration[1]), .B (n_96), .Y (n_105));
  NAND2BX1 g6510(.AN (n_97), .B (n_62), .Y (n_104));
  NAND3X1 g6511(.A (n_15), .B (n_9), .C (n_96), .Y (n_106));
  ADDFXL g6512(.A (current_speed[3]), .B
       (integral_error_accumulator[11]), .CI (n_346), .CO (n_102), .S
       (n_103));
  ADDFXL g6513(.A (current_speed[2]), .B
       (integral_error_accumulator[10]), .CI (n_345), .CO (n_100), .S
       (n_101));
  OAI31X1 g6527(.A0 (n_33), .A1 (n_8), .A2 (n_46), .B0 (n_67), .Y
       (n_95));
  NOR2XL g6528(.A (current_state[10]), .B (n_75), .Y (n_94));
  NOR4X1 g6529(.A (current_state[6]), .B (n_1593_BAR), .C (n_18), .D
       (n_57), .Y (n_93));
  NOR3BX1 g6531(.AN (n_62), .B (n_60), .C (n_46), .Y (n_91));
  NOR3X1 g6532(.A (n_3), .B (n_11), .C (n_49), .Y (n_99));
  AOI21X1 g6533(.A0 (n_30), .A1 (n_40), .B0 (n_72), .Y (n_98));
  NAND3X1 g6534(.A (n_61), .B (n_7), .C (n_13), .Y (n_97));
  NAND2XL g6535(.A (n_41), .B (n_74), .Y (n_90));
  NOR3BX1 g6538(.AN (n_54), .B (current_speed[5]), .C
       (current_speed[6]), .Y (n_96));
  NOR2BX1 g6540(.AN (n_436), .B (n_53), .Y (n_89));
  NOR2BX1 g6541(.AN (n_435), .B (n_53), .Y (n_88));
  NOR2BX1 g6542(.AN (n_434), .B (n_53), .Y (n_87));
  NOR2BX1 g6543(.AN (n_432), .B (n_53), .Y (n_86));
  NOR2BX1 g6544(.AN (n_430), .B (n_53), .Y (n_85));
  NOR2BX1 g6545(.AN (n_428), .B (n_53), .Y (n_84));
  NOR2BX1 g6546(.AN (n_426), .B (n_53), .Y (n_83));
  NOR2BX1 g6547(.AN (n_424), .B (n_53), .Y (n_82));
  NOR2BX1 g6548(.AN (n_421), .B (n_53), .Y (n_81));
  NOR2BX1 g6549(.AN (n_433), .B (n_53), .Y (n_80));
  NOR2BX1 g6550(.AN (n_422), .B (n_53), .Y (n_79));
  NOR2BX1 g6551(.AN (n_431), .B (n_53), .Y (n_78));
  NOR2BX1 g6552(.AN (n_429), .B (n_53), .Y (n_77));
  NOR2XL g6553(.A (n_30), .B (n_40), .Y (n_72));
  NOR2BX1 g6554(.AN (n_425), .B (n_53), .Y (n_71));
  NOR2BX1 g6555(.AN (n_427), .B (n_53), .Y (n_70));
  NAND3X1 g6557(.A (destination_reached_reg), .B (n_10), .C (n_47), .Y
       (n_68));
  NAND3X1 g6558(.A (current_state[8]), .B (n_47), .C (n_23), .Y (n_67));
  OAI22X1 g6559(.A0 (n_21), .A1 (n_19), .B0 (n_43), .B1
       (current_state[3]), .Y (n_66));
  AO22XL g6560(.A0 (n_16), .A1 (n_44), .B0 (n_8), .B1 (n_336), .Y
       (n_65));
  AOI22X1 g6561(.A0 (n_45), .A1 (n_335), .B0 (current_state[6]), .B1
       (n_28), .Y (n_64));
  NOR2BX1 g6562(.AN (n_423), .B (n_53), .Y (n_63));
  OAI21X1 g6563(.A0 (n_11), .A1 (n_3), .B0 (n_49), .Y (n_76));
  NAND2XL g6564(.A (n_24), .B (n_37), .Y (n_75));
  NOR4BX1 g6565(.AN (n_24), .B (front_obstacle_slow_reg), .C (n_44), .D
       (n_45), .Y (n_74));
  NOR3X1 g6566(.A (current_state[3]), .B (n_20), .C (n_46), .Y (n_73));
  ADDHX1 g6567(.A (integral_error_accumulator[9]), .B (n_344), .CO
       (n_58), .S (n_59));
  OAI21X1 g6568(.A0 (current_state[3]), .A1 (n_34), .B0 (n_450), .Y
       (n_57));
  NAND2XL g6569(.A (lane_clear_right_reg), .B (n_39), .Y (n_62));
  NAND2XL g6570(.A (lane_clear_left_reg), .B (n_38), .Y (n_61));
  NAND2XL g6571(.A (n_43), .B (current_state[3]), .Y (n_60));
  OAI21X1 g6572(.A0 (n_15), .A1 (n_31), .B0 (n_32), .Y (n_56));
  NOR4BX1 g6573(.AN (n_355), .B (current_state[2]), .C
       (current_state[4]), .D (n_6), .Y (n_52));
  OAI21X1 g6574(.A0 (front_obstacle_slow_reg), .A1 (n_21), .B0 (n_48),
       .Y (n_51));
  NAND3BX1 g6575(.AN (n_31), .B (acceleration[1]), .C (n_32), .Y
       (n_50));
  NAND3X1 g6576(.A (current_state[10]), .B (n_20), .C (n_24), .Y
       (n_55));
  NOR4X1 g6577(.A (current_speed[1]), .B (current_speed[2]), .C
       (current_speed[3]), .D (current_speed[4]), .Y (n_54));
  NAND3X1 g6578(.A (current_state[2]), .B (n_29), .C (n_355), .Y
       (n_53));
  INVXL g6579(.A (n_47), .Y (n_48));
  CLKINVX1 g6580(.A (n_44), .Y (n_43));
  OAI21X1 g6581(.A0 (current_speed[5]), .A1
       (integral_error_accumulator[13]), .B0 (n_22), .Y (n_49));
  NOR2XL g6582(.A (current_state[3]), .B (n_21), .Y (n_47));
  NAND2XL g6583(.A (n_6), .B (n_23), .Y (n_46));
  OAI21X1 g6584(.A0 (current_speed[6]), .A1
       (integral_error_accumulator[14]), .B0 (n_30), .Y (n_42));
  NAND2BX1 g6585(.AN (current_state[6]), .B (n_29), .Y (n_45));
  NOR2BX1 g6586(.AN (front_obstacle_history[0]), .B (n_33), .Y (n_44));
  NAND3X1 g6587(.A (right_obstacle_history[2]), .B
       (right_obstacle_history[1]), .C (right_obstacle_history[0]), .Y
       (n_39));
  NAND3X1 g6588(.A (left_obstacle_history[2]), .B
       (left_obstacle_history[1]), .C (left_obstacle_history[0]), .Y
       (n_38));
  OAI21X1 g6589(.A0 (current_state[1]), .A1 (n_1), .B0 (n_26), .Y
       (n_41));
  XNOR2XL g6590(.A (current_state[5]), .B (current_state[7]), .Y
       (n_37));
  MXI2XL g6591(.A (current_speed[7]), .B (n_9), .S0
       (integral_error_accumulator[15]), .Y (n_40));
  OAI22X1 g6592(.A0 (integral_error_accumulator[12]), .A1 (n_3), .B0
       (current_speed[4]), .B1 (n_11), .Y (n_36));
  INVXL g6633(.A (n_29), .Y (n_28));
  CLKINVX1 g6634(.A (n_26), .Y (n_27));
  CLKINVX1 g6635(.A (n_21), .Y (n_20));
  NOR2XL g6658(.A (front_obstacle_history[0]), .B (n_8), .Y (n_19));
  NOR2XL g6660(.A (n_334), .B (n_8), .Y (n_18));
  NAND2XL g6662(.A (current_state[1]), .B (current_state[2]), .Y
       (n_35));
  NOR2XL g6663(.A (current_state[0]), .B (n_10), .Y (n_34));
  NAND2XL g6664(.A (front_obstacle_history[2]), .B
       (front_obstacle_history[1]), .Y (n_33));
  NAND2XL g6665(.A (integral_error_accumulator[8]), .B (n_343), .Y
       (n_32));
  NOR2XL g6666(.A (integral_error_accumulator[8]), .B (n_343), .Y
       (n_31));
  NAND2XL g6667(.A (current_speed[6]), .B
       (integral_error_accumulator[14]), .Y (n_30));
  NOR2XL g6668(.A (current_state[4]), .B (current_state[8]), .Y (n_29));
  NAND2XL g6669(.A (current_state[1]), .B (n_1), .Y (n_26));
  NOR2XL g6670(.A (destination_reached_reg), .B (n_336), .Y (n_25));
  NOR2XL g6671(.A (current_state[3]), .B (current_state[0]), .Y (n_24));
  NOR2XL g6672(.A (n_448), .B (n_340), .Y (n_23));
  NAND2XL g6675(.A (current_speed[5]), .B
       (integral_error_accumulator[13]), .Y (n_22));
  NAND2XL g6676(.A (n_5), .B (n_1), .Y (n_21));
  CLKINVX1 g6686(.A (current_speed[0]), .Y (n_15));
  INVX1 g6722(.A (current_state[0]), .Y (n_7));
  DFFRX1 \current_speed_reg[2] (.RN (n_12), .CK (clk), .D (n_154), .Q
       (current_speed[2]), .QN (n_2));
  DFFRX1 \current_speed_reg[4] (.RN (n_12), .CK (clk), .D (n_165), .Q
       (current_speed[4]), .QN (n_3));
  DFFRX1 \current_speed_reg[5] (.RN (n_12), .CK (clk), .D (n_166), .Q
       (current_speed[5]), .QN (n_4));
  DFFRX1 \current_speed_reg[7] (.RN (n_12), .CK (clk), .D (n_172), .Q
       (current_speed[7]), .QN (n_9));
  DFFRX1 \current_state_reg[1] (.RN (n_12), .CK (clk), .D (n_153), .Q
       (current_state[1]), .QN (n_5));
  DFFRX1 \current_state_reg[2] (.RN (n_12), .CK (clk), .D (n_111), .Q
       (current_state[2]), .QN (n_1));
  DFFRX1 \current_state_reg[3] (.RN (n_12), .CK (clk), .D (n_132), .Q
       (current_state[3]), .QN (n_8));
  DFFRX1 \current_state_reg[8] (.RN (n_12), .CK (clk), .D (n_126), .Q
       (current_state[8]), .QN (n_6));
  DFFRX1 \current_state_reg[10] (.RN (n_12), .CK (clk), .D (n_128), .Q
       (current_state[10]), .QN (n_10));
  DFFRX1 \integral_error_accumulator_reg[12] (.RN (n_12), .CK (clk), .D
       (n_82), .Q (integral_error_accumulator[12]), .QN (n_11));
  NOR2BX1 g5360(.AN (n_106), .B (acceleration[0]), .Y (n_0));
  NOR2XL g6789(.A (current_state[5]), .B (current_state[7]), .Y (n_13));
  DFFRX1 \current_speed_reg[6] (.RN (n_12), .CK (clk), .D (n_171), .Q
       (current_speed[6]), .QN (n_175));
  DFFRX1 destination_reached_reg_reg(.RN (n_12), .CK (clk), .D
       (destination_reached), .Q (destination_reached_reg), .QN (n_16));
  NAND3BX1 g6795(.AN (n_60), .B (n_178), .C (n_23), .Y (n_453));
endmodule

